/******************************************************************************
 * This file was generated by ZenStack CLI.
 ******************************************************************************/

/* eslint-disable */

import type { ModelMeta } from "@zenstackhq/runtime";

const metadata: ModelMeta = {
    models: {
        aimags: {
            name: 'aimags', fields: {
                id: {
                    name: "id",
                    type: "String",
                    isId: true,
                    attributes: [{ "name": "@default", "args": [{ "name": "value" }] }],
                }, name: {
                    name: "name",
                    type: "String",
                }, name_en: {
                    name: "name_en",
                    type: "String",
                    isOptional: true,
                }, code: {
                    name: "code",
                    type: "String",
                }, type: {
                    name: "type",
                    type: "AimagType",
                    attributes: [{ "name": "@default", "args": [{ "name": "value" }] }],
                }, sort_order: {
                    name: "sort_order",
                    type: "Int",
                    attributes: [{ "name": "@default", "args": [{ "name": "value", "value": 0 }] }],
                }, is_active: {
                    name: "is_active",
                    type: "Boolean",
                    attributes: [{ "name": "@default", "args": [{ "name": "value", "value": true }] }],
                }, created_at: {
                    name: "created_at",
                    type: "DateTime",
                    attributes: [{ "name": "@default", "args": [{ "name": "value" }] }],
                }, updated_at: {
                    name: "updated_at",
                    type: "DateTime",
                    attributes: [{ "name": "@updatedAt", "args": [] }],
                }, districts: {
                    name: "districts",
                    type: "districts",
                    isDataModel: true,
                    isArray: true,
                    backLink: 'aimag',
                }, listings: {
                    name: "listings",
                    type: "listings",
                    isDataModel: true,
                    isArray: true,
                    backLink: 'aimag',
                }, requests: {
                    name: "requests",
                    type: "listing_requests",
                    isDataModel: true,
                    isArray: true,
                    backLink: 'aimag',
                },
            }, uniqueConstraints: {
                id: {
                    name: "id",
                    fields: ["id"]
                }, name: {
                    name: "name",
                    fields: ["name"]
                }, code: {
                    name: "code",
                    fields: ["code"]
                },
            },
        },
        districts: {
            name: 'districts', fields: {
                id: {
                    name: "id",
                    type: "String",
                    isId: true,
                    attributes: [{ "name": "@default", "args": [{ "name": "value" }] }],
                }, aimag_id: {
                    name: "aimag_id",
                    type: "String",
                    isForeignKey: true,
                    relationField: 'aimag',
                }, name: {
                    name: "name",
                    type: "String",
                }, name_en: {
                    name: "name_en",
                    type: "String",
                    isOptional: true,
                }, type: {
                    name: "type",
                    type: "DistrictType",
                    attributes: [{ "name": "@default", "args": [{ "name": "value" }] }],
                }, sort_order: {
                    name: "sort_order",
                    type: "Int",
                    attributes: [{ "name": "@default", "args": [{ "name": "value", "value": 0 }] }],
                }, is_active: {
                    name: "is_active",
                    type: "Boolean",
                    attributes: [{ "name": "@default", "args": [{ "name": "value", "value": true }] }],
                }, created_at: {
                    name: "created_at",
                    type: "DateTime",
                    attributes: [{ "name": "@default", "args": [{ "name": "value" }] }],
                }, updated_at: {
                    name: "updated_at",
                    type: "DateTime",
                    attributes: [{ "name": "@updatedAt", "args": [] }],
                }, aimag: {
                    name: "aimag",
                    type: "aimags",
                    isDataModel: true,
                    backLink: 'districts',
                    isRelationOwner: true,
                    onDeleteAction: 'Cascade',
                    foreignKeyMapping: { "id": "aimag_id" },
                }, khoroos: {
                    name: "khoroos",
                    type: "khoroos",
                    isDataModel: true,
                    isArray: true,
                    backLink: 'district',
                }, listings: {
                    name: "listings",
                    type: "listings",
                    isDataModel: true,
                    isArray: true,
                    backLink: 'district',
                }, requests: {
                    name: "requests",
                    type: "listing_requests",
                    isDataModel: true,
                    isArray: true,
                    backLink: 'district',
                },
            }, uniqueConstraints: {
                id: {
                    name: "id",
                    fields: ["id"]
                }, aimag_id_name: {
                    name: "aimag_id_name",
                    fields: ["aimag_id", "name"]
                },
            },
        },
        khoroos: {
            name: 'khoroos', fields: {
                id: {
                    name: "id",
                    type: "String",
                    isId: true,
                    attributes: [{ "name": "@default", "args": [{ "name": "value" }] }],
                }, district_id: {
                    name: "district_id",
                    type: "String",
                    isForeignKey: true,
                    relationField: 'district',
                }, name: {
                    name: "name",
                    type: "String",
                }, number: {
                    name: "number",
                    type: "Int",
                    isOptional: true,
                }, sort_order: {
                    name: "sort_order",
                    type: "Int",
                    attributes: [{ "name": "@default", "args": [{ "name": "value", "value": 0 }] }],
                }, is_active: {
                    name: "is_active",
                    type: "Boolean",
                    attributes: [{ "name": "@default", "args": [{ "name": "value", "value": true }] }],
                }, created_at: {
                    name: "created_at",
                    type: "DateTime",
                    attributes: [{ "name": "@default", "args": [{ "name": "value" }] }],
                }, updated_at: {
                    name: "updated_at",
                    type: "DateTime",
                    attributes: [{ "name": "@updatedAt", "args": [] }],
                }, district: {
                    name: "district",
                    type: "districts",
                    isDataModel: true,
                    backLink: 'khoroos',
                    isRelationOwner: true,
                    onDeleteAction: 'Cascade',
                    foreignKeyMapping: { "id": "district_id" },
                }, listings: {
                    name: "listings",
                    type: "listings",
                    isDataModel: true,
                    isArray: true,
                    backLink: 'khoroo',
                }, requests: {
                    name: "requests",
                    type: "listing_requests",
                    isDataModel: true,
                    isArray: true,
                    backLink: 'khoroo',
                },
            }, uniqueConstraints: {
                id: {
                    name: "id",
                    fields: ["id"]
                }, district_id_name: {
                    name: "district_id_name",
                    fields: ["district_id", "name"]
                }, district_id_number: {
                    name: "district_id_number",
                    fields: ["district_id", "number"]
                },
            },
        },
        categories: {
            name: 'categories', fields: {
                id: {
                    name: "id",
                    type: "String",
                    isId: true,
                    attributes: [{ "name": "@default", "args": [{ "name": "value" }] }],
                }, slug: {
                    name: "slug",
                    type: "String",
                }, name: {
                    name: "name",
                    type: "String",
                }, icon: {
                    name: "icon",
                    type: "String",
                    isOptional: true,
                }, parent_id: {
                    name: "parent_id",
                    type: "String",
                    isOptional: true,
                    isForeignKey: true,
                    relationField: 'parent',
                }, parent: {
                    name: "parent",
                    type: "categories",
                    isDataModel: true,
                    isOptional: true,
                    backLink: 'children',
                    isRelationOwner: true,
                    foreignKeyMapping: { "id": "parent_id" },
                }, children: {
                    name: "children",
                    type: "categories",
                    isDataModel: true,
                    isArray: true,
                    backLink: 'parent',
                }, sort_order: {
                    name: "sort_order",
                    type: "Int",
                    attributes: [{ "name": "@default", "args": [{ "name": "value", "value": 0 }] }],
                }, is_active: {
                    name: "is_active",
                    type: "Boolean",
                    attributes: [{ "name": "@default", "args": [{ "name": "value", "value": true }] }],
                }, created_at: {
                    name: "created_at",
                    type: "DateTime",
                    attributes: [{ "name": "@default", "args": [{ "name": "value" }] }],
                }, updated_at: {
                    name: "updated_at",
                    type: "DateTime",
                    attributes: [{ "name": "@updatedAt", "args": [] }],
                }, listings: {
                    name: "listings",
                    type: "listings",
                    isDataModel: true,
                    isArray: true,
                    backLink: 'category',
                },
            }, uniqueConstraints: {
                id: {
                    name: "id",
                    fields: ["id"]
                }, slug: {
                    name: "slug",
                    fields: ["slug"]
                },
            },
        },
        profiles: {
            name: 'profiles', fields: {
                id: {
                    name: "id",
                    type: "String",
                    isId: true,
                }, first_name: {
                    name: "first_name",
                    type: "String",
                    isOptional: true,
                }, last_name: {
                    name: "last_name",
                    type: "String",
                    isOptional: true,
                }, phone_number: {
                    name: "phone_number",
                    type: "String",
                    isOptional: true,
                }, is_company: {
                    name: "is_company",
                    type: "Boolean",
                    attributes: [{ "name": "@default", "args": [{ "name": "value", "value": false }] }],
                }, avatar_url: {
                    name: "avatar_url",
                    type: "String",
                    isOptional: true,
                }, about: {
                    name: "about",
                    type: "String",
                    isOptional: true,
                }, role: {
                    name: "role",
                    type: "UserRole",
                    attributes: [{ "name": "@default", "args": [{ "name": "value" }] }],
                }, created_at: {
                    name: "created_at",
                    type: "DateTime",
                    attributes: [{ "name": "@default", "args": [{ "name": "value" }] }],
                }, updated_at: {
                    name: "updated_at",
                    type: "DateTime",
                    attributes: [{ "name": "@default", "args": [{ "name": "value" }] }],
                }, company_name: {
                    name: "company_name",
                    type: "String",
                    isOptional: true,
                }, registration_number: {
                    name: "registration_number",
                    type: "String",
                    isOptional: true,
                }, is_deleted: {
                    name: "is_deleted",
                    type: "Boolean",
                    attributes: [{ "name": "@default", "args": [{ "name": "value", "value": false }] }],
                }, avg_rating: {
                    name: "avg_rating",
                    type: "Decimal",
                    isOptional: true,
                }, reviews_count: {
                    name: "reviews_count",
                    type: "Int",
                    attributes: [{ "name": "@default", "args": [{ "name": "value", "value": 0 }] }],
                }, completed_jobs_count: {
                    name: "completed_jobs_count",
                    type: "Int",
                    attributes: [{ "name": "@default", "args": [{ "name": "value", "value": 0 }] }],
                }, push_subscriptions: {
                    name: "push_subscriptions",
                    type: "profiles_push_subscriptions",
                    isDataModel: true,
                    isArray: true,
                    backLink: 'profile',
                }, notification_settings: {
                    name: "notification_settings",
                    type: "profiles_notification_settings",
                    isDataModel: true,
                    isOptional: true,
                    backLink: 'profile',
                }, educations: {
                    name: "educations",
                    type: "profiles_educations",
                    isDataModel: true,
                    isArray: true,
                    backLink: 'user',
                }, work_experiences: {
                    name: "work_experiences",
                    type: "profiles_work_experiences",
                    isDataModel: true,
                    isArray: true,
                    backLink: 'user',
                }, listings: {
                    name: "listings",
                    type: "listings",
                    isDataModel: true,
                    isArray: true,
                    backLink: 'user',
                }, viewed_listings: {
                    name: "viewed_listings",
                    type: "listings_views",
                    isDataModel: true,
                    isArray: true,
                    backLink: 'viewer',
                }, favorites: {
                    name: "favorites",
                    type: "user_favorites",
                    isDataModel: true,
                    isArray: true,
                    backLink: 'user',
                }, sent_requests: {
                    name: "sent_requests",
                    type: "listing_requests",
                    isDataModel: true,
                    isArray: true,
                    backLink: 'client',
                }, received_requests: {
                    name: "received_requests",
                    type: "listing_requests",
                    isDataModel: true,
                    isArray: true,
                    backLink: 'provider',
                }, received_notifications: {
                    name: "received_notifications",
                    type: "notifications",
                    isDataModel: true,
                    isArray: true,
                    backLink: 'user',
                }, triggered_notifications: {
                    name: "triggered_notifications",
                    type: "notifications",
                    isDataModel: true,
                    isArray: true,
                    backLink: 'actor',
                }, chat_messages: {
                    name: "chat_messages",
                    type: "chat_messages",
                    isDataModel: true,
                    isArray: true,
                    backLink: 'sender',
                }, reviews_given: {
                    name: "reviews_given",
                    type: "reviews",
                    isDataModel: true,
                    isArray: true,
                    backLink: 'client',
                }, reviews_received: {
                    name: "reviews_received",
                    type: "reviews",
                    isDataModel: true,
                    isArray: true,
                    backLink: 'provider',
                }, location_tracks: {
                    name: "location_tracks",
                    type: "request_locations",
                    isDataModel: true,
                    isArray: true,
                    backLink: 'user',
                },
            }, uniqueConstraints: {
                id: {
                    name: "id",
                    fields: ["id"]
                },
            },
        },
        profiles_push_subscriptions: {
            name: 'profiles_push_subscriptions', fields: {
                id: {
                    name: "id",
                    type: "String",
                    isId: true,
                    attributes: [{ "name": "@default", "args": [{ "name": "value" }] }],
                }, user_id: {
                    name: "user_id",
                    type: "String",
                    isForeignKey: true,
                    relationField: 'profile',
                }, endpoint: {
                    name: "endpoint",
                    type: "String",
                }, p256dh: {
                    name: "p256dh",
                    type: "String",
                    isOptional: true,
                }, auth: {
                    name: "auth",
                    type: "String",
                    isOptional: true,
                }, expires_at: {
                    name: "expires_at",
                    type: "DateTime",
                    isOptional: true,
                }, created_at: {
                    name: "created_at",
                    type: "DateTime",
                    attributes: [{ "name": "@default", "args": [{ "name": "value" }] }],
                }, updated_at: {
                    name: "updated_at",
                    type: "DateTime",
                    attributes: [{ "name": "@default", "args": [{ "name": "value" }] }],
                }, profile: {
                    name: "profile",
                    type: "profiles",
                    isDataModel: true,
                    backLink: 'push_subscriptions',
                    isRelationOwner: true,
                    onDeleteAction: 'Cascade',
                    foreignKeyMapping: { "id": "user_id" },
                },
            }, uniqueConstraints: {
                id: {
                    name: "id",
                    fields: ["id"]
                }, user_id_endpoint: {
                    name: "user_id_endpoint",
                    fields: ["user_id", "endpoint"]
                },
            },
        },
        profiles_notification_settings: {
            name: 'profiles_notification_settings', fields: {
                id: {
                    name: "id",
                    type: "String",
                    isId: true,
                    attributes: [{ "name": "@default", "args": [{ "name": "value" }] }],
                }, user_id: {
                    name: "user_id",
                    type: "String",
                    isForeignKey: true,
                    relationField: 'profile',
                }, push_enabled: {
                    name: "push_enabled",
                    type: "Boolean",
                    attributes: [{ "name": "@default", "args": [{ "name": "value", "value": false }] }],
                }, push_new_requests: {
                    name: "push_new_requests",
                    type: "Boolean",
                    attributes: [{ "name": "@default", "args": [{ "name": "value", "value": true }] }],
                }, push_new_messages: {
                    name: "push_new_messages",
                    type: "Boolean",
                    attributes: [{ "name": "@default", "args": [{ "name": "value", "value": true }] }],
                }, push_status_changes: {
                    name: "push_status_changes",
                    type: "Boolean",
                    attributes: [{ "name": "@default", "args": [{ "name": "value", "value": true }] }],
                }, email_enabled: {
                    name: "email_enabled",
                    type: "Boolean",
                    attributes: [{ "name": "@default", "args": [{ "name": "value", "value": true }] }],
                }, email_new_requests: {
                    name: "email_new_requests",
                    type: "Boolean",
                    attributes: [{ "name": "@default", "args": [{ "name": "value", "value": true }] }],
                }, email_new_messages: {
                    name: "email_new_messages",
                    type: "Boolean",
                    attributes: [{ "name": "@default", "args": [{ "name": "value", "value": true }] }],
                }, email_digest: {
                    name: "email_digest",
                    type: "Boolean",
                    attributes: [{ "name": "@default", "args": [{ "name": "value", "value": true }] }],
                }, email_digest_frequency: {
                    name: "email_digest_frequency",
                    type: "String",
                    attributes: [{ "name": "@default", "args": [{ "name": "value", "value": "daily" }] }],
                }, quiet_hours_enabled: {
                    name: "quiet_hours_enabled",
                    type: "Boolean",
                    attributes: [{ "name": "@default", "args": [{ "name": "value", "value": false }] }],
                }, quiet_hours_start: {
                    name: "quiet_hours_start",
                    type: "String",
                    attributes: [{ "name": "@default", "args": [{ "name": "value", "value": "22:00" }] }],
                }, quiet_hours_end: {
                    name: "quiet_hours_end",
                    type: "String",
                    attributes: [{ "name": "@default", "args": [{ "name": "value", "value": "08:00" }] }],
                }, created_at: {
                    name: "created_at",
                    type: "DateTime",
                    attributes: [{ "name": "@default", "args": [{ "name": "value" }] }],
                }, updated_at: {
                    name: "updated_at",
                    type: "DateTime",
                    attributes: [{ "name": "@default", "args": [{ "name": "value" }] }],
                }, profile: {
                    name: "profile",
                    type: "profiles",
                    isDataModel: true,
                    backLink: 'notification_settings',
                    isRelationOwner: true,
                    onDeleteAction: 'Cascade',
                    foreignKeyMapping: { "id": "user_id" },
                },
            }, uniqueConstraints: {
                id: {
                    name: "id",
                    fields: ["id"]
                }, user_id: {
                    name: "user_id",
                    fields: ["user_id"]
                },
            },
        },
        profiles_educations: {
            name: 'profiles_educations', fields: {
                id: {
                    name: "id",
                    type: "String",
                    isId: true,
                    attributes: [{ "name": "@default", "args": [{ "name": "value" }] }],
                }, user_id: {
                    name: "user_id",
                    type: "String",
                    isForeignKey: true,
                    relationField: 'user',
                }, degree: {
                    name: "degree",
                    type: "String",
                }, institution: {
                    name: "institution",
                    type: "String",
                }, field_of_study: {
                    name: "field_of_study",
                    type: "String",
                    isOptional: true,
                }, start_date: {
                    name: "start_date",
                    type: "DateTime",
                }, end_date: {
                    name: "end_date",
                    type: "DateTime",
                    isOptional: true,
                }, is_current: {
                    name: "is_current",
                    type: "Boolean",
                    attributes: [{ "name": "@default", "args": [{ "name": "value", "value": false }] }],
                }, created_at: {
                    name: "created_at",
                    type: "DateTime",
                    attributes: [{ "name": "@default", "args": [{ "name": "value" }] }],
                }, updated_at: {
                    name: "updated_at",
                    type: "DateTime",
                    attributes: [{ "name": "@default", "args": [{ "name": "value" }] }],
                }, user: {
                    name: "user",
                    type: "profiles",
                    isDataModel: true,
                    backLink: 'educations',
                    isRelationOwner: true,
                    onDeleteAction: 'Cascade',
                    foreignKeyMapping: { "id": "user_id" },
                },
            }, uniqueConstraints: {
                id: {
                    name: "id",
                    fields: ["id"]
                },
            },
        },
        profiles_work_experiences: {
            name: 'profiles_work_experiences', fields: {
                id: {
                    name: "id",
                    type: "String",
                    isId: true,
                    attributes: [{ "name": "@default", "args": [{ "name": "value" }] }],
                }, user_id: {
                    name: "user_id",
                    type: "String",
                    isForeignKey: true,
                    relationField: 'user',
                }, company: {
                    name: "company",
                    type: "String",
                }, position: {
                    name: "position",
                    type: "String",
                }, description: {
                    name: "description",
                    type: "String",
                    isOptional: true,
                }, start_date: {
                    name: "start_date",
                    type: "DateTime",
                }, end_date: {
                    name: "end_date",
                    type: "DateTime",
                    isOptional: true,
                }, is_current: {
                    name: "is_current",
                    type: "Boolean",
                    attributes: [{ "name": "@default", "args": [{ "name": "value", "value": false }] }],
                }, created_at: {
                    name: "created_at",
                    type: "DateTime",
                    attributes: [{ "name": "@default", "args": [{ "name": "value" }] }],
                }, updated_at: {
                    name: "updated_at",
                    type: "DateTime",
                    attributes: [{ "name": "@default", "args": [{ "name": "value" }] }],
                }, user: {
                    name: "user",
                    type: "profiles",
                    isDataModel: true,
                    backLink: 'work_experiences',
                    isRelationOwner: true,
                    onDeleteAction: 'Cascade',
                    foreignKeyMapping: { "id": "user_id" },
                },
            }, uniqueConstraints: {
                id: {
                    name: "id",
                    fields: ["id"]
                },
            },
        },
        listings: {
            name: 'listings', fields: {
                id: {
                    name: "id",
                    type: "String",
                    isId: true,
                    attributes: [{ "name": "@default", "args": [{ "name": "value" }] }],
                }, user_id: {
                    name: "user_id",
                    type: "String",
                    isForeignKey: true,
                    relationField: 'user',
                }, category_id: {
                    name: "category_id",
                    type: "String",
                    isOptional: true,
                    isForeignKey: true,
                    relationField: 'category',
                }, title: {
                    name: "title",
                    type: "String",
                }, slug: {
                    name: "slug",
                    type: "String",
                }, description: {
                    name: "description",
                    type: "String",
                }, price: {
                    name: "price",
                    type: "Decimal",
                    isOptional: true,
                }, currency: {
                    name: "currency",
                    type: "String",
                    attributes: [{ "name": "@default", "args": [{ "name": "value", "value": "MNT" }] }],
                }, is_negotiable: {
                    name: "is_negotiable",
                    type: "Boolean",
                    attributes: [{ "name": "@default", "args": [{ "name": "value", "value": false }] }],
                }, duration_minutes: {
                    name: "duration_minutes",
                    type: "Int",
                    isOptional: true,
                }, work_hours_start: {
                    name: "work_hours_start",
                    type: "String",
                    isOptional: true,
                    attributes: [{ "name": "@default", "args": [{ "name": "value", "value": "09:00" }] }],
                }, work_hours_end: {
                    name: "work_hours_end",
                    type: "String",
                    isOptional: true,
                    attributes: [{ "name": "@default", "args": [{ "name": "value", "value": "18:00" }] }],
                }, service_type: {
                    name: "service_type",
                    type: "ServiceType",
                    attributes: [{ "name": "@default", "args": [{ "name": "value" }] }],
                }, aimag_id: {
                    name: "aimag_id",
                    type: "String",
                    isOptional: true,
                    isForeignKey: true,
                    relationField: 'aimag',
                }, district_id: {
                    name: "district_id",
                    type: "String",
                    isOptional: true,
                    isForeignKey: true,
                    relationField: 'district',
                }, khoroo_id: {
                    name: "khoroo_id",
                    type: "String",
                    isOptional: true,
                    isForeignKey: true,
                    relationField: 'khoroo',
                }, address: {
                    name: "address",
                    type: "String",
                    isOptional: true,
                }, latitude: {
                    name: "latitude",
                    type: "Decimal",
                    isOptional: true,
                }, longitude: {
                    name: "longitude",
                    type: "Decimal",
                    isOptional: true,
                }, status: {
                    name: "status",
                    type: "ListingStatus",
                    attributes: [{ "name": "@default", "args": [{ "name": "value" }] }],
                }, is_active: {
                    name: "is_active",
                    type: "Boolean",
                    attributes: [{ "name": "@default", "args": [{ "name": "value", "value": true }] }],
                }, views_count: {
                    name: "views_count",
                    type: "Int",
                    attributes: [{ "name": "@default", "args": [{ "name": "value", "value": 0 }] }],
                }, favorites_count: {
                    name: "favorites_count",
                    type: "Int",
                    attributes: [{ "name": "@default", "args": [{ "name": "value", "value": 0 }] }],
                }, search_vector: {
                    name: "search_vector",
                    type: "undefined",
                    isOptional: true,
                }, created_at: {
                    name: "created_at",
                    type: "DateTime",
                    attributes: [{ "name": "@default", "args": [{ "name": "value" }] }],
                }, updated_at: {
                    name: "updated_at",
                    type: "DateTime",
                    attributes: [{ "name": "@updatedAt", "args": [] }],
                }, published_at: {
                    name: "published_at",
                    type: "DateTime",
                    isOptional: true,
                }, user: {
                    name: "user",
                    type: "profiles",
                    isDataModel: true,
                    backLink: 'listings',
                    isRelationOwner: true,
                    onDeleteAction: 'Cascade',
                    foreignKeyMapping: { "id": "user_id" },
                }, category: {
                    name: "category",
                    type: "categories",
                    isDataModel: true,
                    isOptional: true,
                    backLink: 'listings',
                    isRelationOwner: true,
                    foreignKeyMapping: { "id": "category_id" },
                }, aimag: {
                    name: "aimag",
                    type: "aimags",
                    isDataModel: true,
                    isOptional: true,
                    backLink: 'listings',
                    isRelationOwner: true,
                    foreignKeyMapping: { "id": "aimag_id" },
                }, district: {
                    name: "district",
                    type: "districts",
                    isDataModel: true,
                    isOptional: true,
                    backLink: 'listings',
                    isRelationOwner: true,
                    foreignKeyMapping: { "id": "district_id" },
                }, khoroo: {
                    name: "khoroo",
                    type: "khoroos",
                    isDataModel: true,
                    isOptional: true,
                    backLink: 'listings',
                    isRelationOwner: true,
                    foreignKeyMapping: { "id": "khoroo_id" },
                }, images: {
                    name: "images",
                    type: "listings_images",
                    isDataModel: true,
                    isArray: true,
                    backLink: 'listing',
                }, views: {
                    name: "views",
                    type: "listings_views",
                    isDataModel: true,
                    isArray: true,
                    backLink: 'listing',
                }, favorites: {
                    name: "favorites",
                    type: "user_favorites",
                    isDataModel: true,
                    isArray: true,
                    backLink: 'listing',
                }, requests: {
                    name: "requests",
                    type: "listing_requests",
                    isDataModel: true,
                    isArray: true,
                    backLink: 'listing',
                },
            }, uniqueConstraints: {
                id: {
                    name: "id",
                    fields: ["id"]
                }, slug: {
                    name: "slug",
                    fields: ["slug"]
                },
            },
        },
        listings_images: {
            name: 'listings_images', fields: {
                id: {
                    name: "id",
                    type: "String",
                    isId: true,
                    attributes: [{ "name": "@default", "args": [{ "name": "value" }] }],
                }, listing_id: {
                    name: "listing_id",
                    type: "String",
                    isForeignKey: true,
                    relationField: 'listing',
                }, url: {
                    name: "url",
                    type: "String",
                }, alt: {
                    name: "alt",
                    type: "String",
                    isOptional: true,
                }, sort_order: {
                    name: "sort_order",
                    type: "Int",
                    attributes: [{ "name": "@default", "args": [{ "name": "value", "value": 0 }] }],
                }, is_cover: {
                    name: "is_cover",
                    type: "Boolean",
                    attributes: [{ "name": "@default", "args": [{ "name": "value", "value": false }] }],
                }, created_at: {
                    name: "created_at",
                    type: "DateTime",
                    attributes: [{ "name": "@default", "args": [{ "name": "value" }] }],
                }, listing: {
                    name: "listing",
                    type: "listings",
                    isDataModel: true,
                    backLink: 'images',
                    isRelationOwner: true,
                    onDeleteAction: 'Cascade',
                    foreignKeyMapping: { "id": "listing_id" },
                },
            }, uniqueConstraints: {
                id: {
                    name: "id",
                    fields: ["id"]
                },
            },
        },
        listings_views: {
            name: 'listings_views', fields: {
                id: {
                    name: "id",
                    type: "String",
                    isId: true,
                    attributes: [{ "name": "@default", "args": [{ "name": "value" }] }],
                }, listing_id: {
                    name: "listing_id",
                    type: "String",
                    isForeignKey: true,
                    relationField: 'listing',
                }, viewer_id: {
                    name: "viewer_id",
                    type: "String",
                    isOptional: true,
                    isForeignKey: true,
                    relationField: 'viewer',
                }, ip_address: {
                    name: "ip_address",
                    type: "String",
                    isOptional: true,
                }, viewed_at: {
                    name: "viewed_at",
                    type: "DateTime",
                    attributes: [{ "name": "@default", "args": [{ "name": "value" }] }],
                }, listing: {
                    name: "listing",
                    type: "listings",
                    isDataModel: true,
                    backLink: 'views',
                    isRelationOwner: true,
                    onDeleteAction: 'Cascade',
                    foreignKeyMapping: { "id": "listing_id" },
                }, viewer: {
                    name: "viewer",
                    type: "profiles",
                    isDataModel: true,
                    isOptional: true,
                    backLink: 'viewed_listings',
                    isRelationOwner: true,
                    onDeleteAction: 'SetNull',
                    foreignKeyMapping: { "id": "viewer_id" },
                },
            }, uniqueConstraints: {
                id: {
                    name: "id",
                    fields: ["id"]
                },
            },
        },
        user_favorites: {
            name: 'user_favorites', fields: {
                id: {
                    name: "id",
                    type: "String",
                    isId: true,
                    attributes: [{ "name": "@default", "args": [{ "name": "value" }] }],
                }, user_id: {
                    name: "user_id",
                    type: "String",
                    isForeignKey: true,
                    relationField: 'user',
                }, listing_id: {
                    name: "listing_id",
                    type: "String",
                    isForeignKey: true,
                    relationField: 'listing',
                }, created_at: {
                    name: "created_at",
                    type: "DateTime",
                    attributes: [{ "name": "@default", "args": [{ "name": "value" }] }],
                }, user: {
                    name: "user",
                    type: "profiles",
                    isDataModel: true,
                    backLink: 'favorites',
                    isRelationOwner: true,
                    onDeleteAction: 'Cascade',
                    foreignKeyMapping: { "id": "user_id" },
                }, listing: {
                    name: "listing",
                    type: "listings",
                    isDataModel: true,
                    backLink: 'favorites',
                    isRelationOwner: true,
                    onDeleteAction: 'Cascade',
                    foreignKeyMapping: { "id": "listing_id" },
                },
            }, uniqueConstraints: {
                id: {
                    name: "id",
                    fields: ["id"]
                }, user_id_listing_id: {
                    name: "user_id_listing_id",
                    fields: ["user_id", "listing_id"]
                },
            },
        },
        listing_requests: {
            name: 'listing_requests', fields: {
                id: {
                    name: "id",
                    type: "String",
                    isId: true,
                    attributes: [{ "name": "@default", "args": [{ "name": "value" }] }],
                }, listing_id: {
                    name: "listing_id",
                    type: "String",
                    isForeignKey: true,
                    relationField: 'listing',
                }, client_id: {
                    name: "client_id",
                    type: "String",
                    isForeignKey: true,
                    relationField: 'client',
                }, provider_id: {
                    name: "provider_id",
                    type: "String",
                    isForeignKey: true,
                    relationField: 'provider',
                }, message: {
                    name: "message",
                    type: "String",
                }, status: {
                    name: "status",
                    type: "RequestStatus",
                    attributes: [{ "name": "@default", "args": [{ "name": "value" }] }],
                }, aimag_id: {
                    name: "aimag_id",
                    type: "String",
                    isOptional: true,
                    isForeignKey: true,
                    relationField: 'aimag',
                }, district_id: {
                    name: "district_id",
                    type: "String",
                    isOptional: true,
                    isForeignKey: true,
                    relationField: 'district',
                }, khoroo_id: {
                    name: "khoroo_id",
                    type: "String",
                    isOptional: true,
                    isForeignKey: true,
                    relationField: 'khoroo',
                }, address_detail: {
                    name: "address_detail",
                    type: "String",
                    isOptional: true,
                }, preferred_date: {
                    name: "preferred_date",
                    type: "DateTime",
                    isOptional: true,
                }, preferred_time: {
                    name: "preferred_time",
                    type: "String",
                    isOptional: true,
                }, note: {
                    name: "note",
                    type: "String",
                    isOptional: true,
                }, image_url: {
                    name: "image_url",
                    type: "String",
                    isOptional: true,
                }, provider_response: {
                    name: "provider_response",
                    type: "String",
                    isOptional: true,
                }, completion_description: {
                    name: "completion_description",
                    type: "String",
                    isOptional: true,
                }, completion_photos: {
                    name: "completion_photos",
                    type: "String",
                    isArray: true,
                    attributes: [{ "name": "@default", "args": [{ "name": "value", "value": [] }] }],
                }, created_at: {
                    name: "created_at",
                    type: "DateTime",
                    attributes: [{ "name": "@default", "args": [{ "name": "value" }] }],
                }, updated_at: {
                    name: "updated_at",
                    type: "DateTime",
                    attributes: [{ "name": "@updatedAt", "args": [] }],
                }, accepted_at: {
                    name: "accepted_at",
                    type: "DateTime",
                    isOptional: true,
                }, completed_at: {
                    name: "completed_at",
                    type: "DateTime",
                    isOptional: true,
                }, listing: {
                    name: "listing",
                    type: "listings",
                    isDataModel: true,
                    backLink: 'requests',
                    isRelationOwner: true,
                    onDeleteAction: 'Cascade',
                    foreignKeyMapping: { "id": "listing_id" },
                }, client: {
                    name: "client",
                    type: "profiles",
                    isDataModel: true,
                    backLink: 'sent_requests',
                    isRelationOwner: true,
                    onDeleteAction: 'Cascade',
                    foreignKeyMapping: { "id": "client_id" },
                }, provider: {
                    name: "provider",
                    type: "profiles",
                    isDataModel: true,
                    backLink: 'received_requests',
                    isRelationOwner: true,
                    onDeleteAction: 'Cascade',
                    foreignKeyMapping: { "id": "provider_id" },
                }, aimag: {
                    name: "aimag",
                    type: "aimags",
                    isDataModel: true,
                    isOptional: true,
                    backLink: 'requests',
                    isRelationOwner: true,
                    foreignKeyMapping: { "id": "aimag_id" },
                }, district: {
                    name: "district",
                    type: "districts",
                    isDataModel: true,
                    isOptional: true,
                    backLink: 'requests',
                    isRelationOwner: true,
                    foreignKeyMapping: { "id": "district_id" },
                }, khoroo: {
                    name: "khoroo",
                    type: "khoroos",
                    isDataModel: true,
                    isOptional: true,
                    backLink: 'requests',
                    isRelationOwner: true,
                    foreignKeyMapping: { "id": "khoroo_id" },
                }, notifications: {
                    name: "notifications",
                    type: "notifications",
                    isDataModel: true,
                    isArray: true,
                    backLink: 'request',
                }, chat_messages: {
                    name: "chat_messages",
                    type: "chat_messages",
                    isDataModel: true,
                    isArray: true,
                    backLink: 'request',
                }, review: {
                    name: "review",
                    type: "reviews",
                    isDataModel: true,
                    isOptional: true,
                    backLink: 'request',
                }, locations: {
                    name: "locations",
                    type: "request_locations",
                    isDataModel: true,
                    isArray: true,
                    backLink: 'request',
                },
            }, uniqueConstraints: {
                id: {
                    name: "id",
                    fields: ["id"]
                },
            },
        },
        notifications: {
            name: 'notifications', fields: {
                id: {
                    name: "id",
                    type: "String",
                    isId: true,
                    attributes: [{ "name": "@default", "args": [{ "name": "value" }] }],
                }, user_id: {
                    name: "user_id",
                    type: "String",
                    isForeignKey: true,
                    relationField: 'user',
                }, type: {
                    name: "type",
                    type: "NotificationType",
                }, title: {
                    name: "title",
                    type: "String",
                }, message: {
                    name: "message",
                    type: "String",
                }, is_read: {
                    name: "is_read",
                    type: "Boolean",
                    attributes: [{ "name": "@default", "args": [{ "name": "value", "value": false }] }],
                }, request_id: {
                    name: "request_id",
                    type: "String",
                    isOptional: true,
                    isForeignKey: true,
                    relationField: 'request',
                }, actor_id: {
                    name: "actor_id",
                    type: "String",
                    isOptional: true,
                    isForeignKey: true,
                    relationField: 'actor',
                }, created_at: {
                    name: "created_at",
                    type: "DateTime",
                    attributes: [{ "name": "@default", "args": [{ "name": "value" }] }],
                }, read_at: {
                    name: "read_at",
                    type: "DateTime",
                    isOptional: true,
                }, user: {
                    name: "user",
                    type: "profiles",
                    isDataModel: true,
                    backLink: 'received_notifications',
                    isRelationOwner: true,
                    onDeleteAction: 'Cascade',
                    foreignKeyMapping: { "id": "user_id" },
                }, actor: {
                    name: "actor",
                    type: "profiles",
                    isDataModel: true,
                    isOptional: true,
                    backLink: 'triggered_notifications',
                    isRelationOwner: true,
                    onDeleteAction: 'SetNull',
                    foreignKeyMapping: { "id": "actor_id" },
                }, request: {
                    name: "request",
                    type: "listing_requests",
                    isDataModel: true,
                    isOptional: true,
                    backLink: 'notifications',
                    isRelationOwner: true,
                    onDeleteAction: 'SetNull',
                    foreignKeyMapping: { "id": "request_id" },
                },
            }, uniqueConstraints: {
                id: {
                    name: "id",
                    fields: ["id"]
                },
            },
        },
        chat_messages: {
            name: 'chat_messages', fields: {
                id: {
                    name: "id",
                    type: "String",
                    isId: true,
                    attributes: [{ "name": "@default", "args": [{ "name": "value" }] }],
                }, request_id: {
                    name: "request_id",
                    type: "String",
                    isForeignKey: true,
                    relationField: 'request',
                }, sender_id: {
                    name: "sender_id",
                    type: "String",
                    isForeignKey: true,
                    relationField: 'sender',
                }, message: {
                    name: "message",
                    type: "String",
                }, is_read: {
                    name: "is_read",
                    type: "Boolean",
                    attributes: [{ "name": "@default", "args": [{ "name": "value", "value": false }] }],
                }, created_at: {
                    name: "created_at",
                    type: "DateTime",
                    attributes: [{ "name": "@default", "args": [{ "name": "value" }] }],
                }, read_at: {
                    name: "read_at",
                    type: "DateTime",
                    isOptional: true,
                }, attachment_type: {
                    name: "attachment_type",
                    type: "String",
                    isOptional: true,
                }, attachment_url: {
                    name: "attachment_url",
                    type: "String",
                    isOptional: true,
                }, location_lat: {
                    name: "location_lat",
                    type: "Decimal",
                    isOptional: true,
                }, location_lng: {
                    name: "location_lng",
                    type: "Decimal",
                    isOptional: true,
                }, location_name: {
                    name: "location_name",
                    type: "String",
                    isOptional: true,
                }, request: {
                    name: "request",
                    type: "listing_requests",
                    isDataModel: true,
                    backLink: 'chat_messages',
                    isRelationOwner: true,
                    onDeleteAction: 'Cascade',
                    foreignKeyMapping: { "id": "request_id" },
                }, sender: {
                    name: "sender",
                    type: "profiles",
                    isDataModel: true,
                    backLink: 'chat_messages',
                    isRelationOwner: true,
                    onDeleteAction: 'Cascade',
                    foreignKeyMapping: { "id": "sender_id" },
                },
            }, uniqueConstraints: {
                id: {
                    name: "id",
                    fields: ["id"]
                },
            },
        },
        reviews: {
            name: 'reviews', fields: {
                id: {
                    name: "id",
                    type: "String",
                    isId: true,
                    attributes: [{ "name": "@default", "args": [{ "name": "value" }] }],
                }, request_id: {
                    name: "request_id",
                    type: "String",
                    isForeignKey: true,
                    relationField: 'request',
                }, client_id: {
                    name: "client_id",
                    type: "String",
                    isForeignKey: true,
                    relationField: 'client',
                }, provider_id: {
                    name: "provider_id",
                    type: "String",
                    isForeignKey: true,
                    relationField: 'provider',
                }, rating: {
                    name: "rating",
                    type: "Int",
                }, comment: {
                    name: "comment",
                    type: "String",
                    isOptional: true,
                }, created_at: {
                    name: "created_at",
                    type: "DateTime",
                    attributes: [{ "name": "@default", "args": [{ "name": "value" }] }],
                }, request: {
                    name: "request",
                    type: "listing_requests",
                    isDataModel: true,
                    backLink: 'review',
                    isRelationOwner: true,
                    onDeleteAction: 'Cascade',
                    foreignKeyMapping: { "id": "request_id" },
                }, client: {
                    name: "client",
                    type: "profiles",
                    isDataModel: true,
                    backLink: 'reviews_given',
                    isRelationOwner: true,
                    onDeleteAction: 'Cascade',
                    foreignKeyMapping: { "id": "client_id" },
                }, provider: {
                    name: "provider",
                    type: "profiles",
                    isDataModel: true,
                    backLink: 'reviews_received',
                    isRelationOwner: true,
                    onDeleteAction: 'Cascade',
                    foreignKeyMapping: { "id": "provider_id" },
                },
            }, uniqueConstraints: {
                id: {
                    name: "id",
                    fields: ["id"]
                }, request_id: {
                    name: "request_id",
                    fields: ["request_id"]
                },
            },
        },
        request_locations: {
            name: 'request_locations', fields: {
                id: {
                    name: "id",
                    type: "String",
                    isId: true,
                    attributes: [{ "name": "@default", "args": [{ "name": "value" }] }],
                }, request_id: {
                    name: "request_id",
                    type: "String",
                    isForeignKey: true,
                    relationField: 'request',
                }, user_id: {
                    name: "user_id",
                    type: "String",
                    isForeignKey: true,
                    relationField: 'user',
                }, latitude: {
                    name: "latitude",
                    type: "Float",
                }, longitude: {
                    name: "longitude",
                    type: "Float",
                }, accuracy: {
                    name: "accuracy",
                    type: "Float",
                    isOptional: true,
                }, heading: {
                    name: "heading",
                    type: "Float",
                    isOptional: true,
                }, speed: {
                    name: "speed",
                    type: "Float",
                    isOptional: true,
                }, is_active: {
                    name: "is_active",
                    type: "Boolean",
                    attributes: [{ "name": "@default", "args": [{ "name": "value", "value": true }] }],
                }, updated_at: {
                    name: "updated_at",
                    type: "DateTime",
                    attributes: [{ "name": "@updatedAt", "args": [] }],
                }, request: {
                    name: "request",
                    type: "listing_requests",
                    isDataModel: true,
                    backLink: 'locations',
                    isRelationOwner: true,
                    onDeleteAction: 'Cascade',
                    foreignKeyMapping: { "id": "request_id" },
                }, user: {
                    name: "user",
                    type: "profiles",
                    isDataModel: true,
                    backLink: 'location_tracks',
                    isRelationOwner: true,
                    onDeleteAction: 'Cascade',
                    foreignKeyMapping: { "id": "user_id" },
                },
            }, uniqueConstraints: {
                id: {
                    name: "id",
                    fields: ["id"]
                }, request_id_user_id: {
                    name: "request_id_user_id",
                    fields: ["request_id", "user_id"]
                },
            },
        },

    },
    deleteCascade: {
        aimags: ['districts'],
        districts: ['khoroos'],
        profiles: ['profiles_push_subscriptions', 'profiles_notification_settings', 'profiles_educations', 'profiles_work_experiences', 'listings', 'user_favorites', 'listing_requests', 'notifications', 'chat_messages', 'reviews', 'request_locations'],
        listings: ['listings_images', 'listings_views', 'user_favorites', 'listing_requests'],
        listing_requests: ['chat_messages', 'reviews', 'request_locations'],

    },
    authModel: 'profiles'

};
export default metadata;
