/******************************************************************************
 * This file was generated by ZenStack CLI.
 ******************************************************************************/

/* eslint-disable */

import type { ModelMeta } from "@zenstackhq/runtime";

const metadata: ModelMeta = {
    models: {
        categories: {
            name: 'categories', fields: {
                id: {
                    name: "id",
                    type: "String",
                    isId: true,
                    attributes: [{ "name": "@default", "args": [{ "name": "value" }] }],
                }, slug: {
                    name: "slug",
                    type: "String",
                }, name: {
                    name: "name",
                    type: "String",
                }, icon: {
                    name: "icon",
                    type: "String",
                    isOptional: true,
                }, parent_id: {
                    name: "parent_id",
                    type: "String",
                    isOptional: true,
                    isForeignKey: true,
                    relationField: 'parent',
                }, parent: {
                    name: "parent",
                    type: "categories",
                    isDataModel: true,
                    isOptional: true,
                    backLink: 'children',
                    isRelationOwner: true,
                    foreignKeyMapping: { "id": "parent_id" },
                }, children: {
                    name: "children",
                    type: "categories",
                    isDataModel: true,
                    isArray: true,
                    backLink: 'parent',
                }, sort_order: {
                    name: "sort_order",
                    type: "Int",
                    attributes: [{ "name": "@default", "args": [{ "name": "value", "value": 0 }] }],
                }, is_active: {
                    name: "is_active",
                    type: "Boolean",
                    attributes: [{ "name": "@default", "args": [{ "name": "value", "value": true }] }],
                }, created_at: {
                    name: "created_at",
                    type: "DateTime",
                    attributes: [{ "name": "@default", "args": [{ "name": "value" }] }],
                }, updated_at: {
                    name: "updated_at",
                    type: "DateTime",
                    attributes: [{ "name": "@updatedAt", "args": [] }],
                }, listings: {
                    name: "listings",
                    type: "listings",
                    isDataModel: true,
                    isArray: true,
                    backLink: 'category',
                },
            }, uniqueConstraints: {
                id: {
                    name: "id",
                    fields: ["id"]
                }, slug: {
                    name: "slug",
                    fields: ["slug"]
                },
            },
        },
        profiles: {
            name: 'profiles', fields: {
                id: {
                    name: "id",
                    type: "String",
                    isId: true,
                }, first_name: {
                    name: "first_name",
                    type: "String",
                    isOptional: true,
                }, last_name: {
                    name: "last_name",
                    type: "String",
                    isOptional: true,
                }, phone_number: {
                    name: "phone_number",
                    type: "String",
                    isOptional: true,
                }, is_company: {
                    name: "is_company",
                    type: "Boolean",
                    attributes: [{ "name": "@default", "args": [{ "name": "value", "value": false }] }],
                }, avatar_url: {
                    name: "avatar_url",
                    type: "String",
                    isOptional: true,
                }, about: {
                    name: "about",
                    type: "String",
                    isOptional: true,
                }, role: {
                    name: "role",
                    type: "UserRole",
                    attributes: [{ "name": "@default", "args": [{ "name": "value" }] }],
                }, created_at: {
                    name: "created_at",
                    type: "DateTime",
                    attributes: [{ "name": "@default", "args": [{ "name": "value" }] }],
                }, updated_at: {
                    name: "updated_at",
                    type: "DateTime",
                    attributes: [{ "name": "@default", "args": [{ "name": "value" }] }],
                }, company_name: {
                    name: "company_name",
                    type: "String",
                    isOptional: true,
                }, registration_number: {
                    name: "registration_number",
                    type: "String",
                    isOptional: true,
                }, is_deleted: {
                    name: "is_deleted",
                    type: "Boolean",
                    attributes: [{ "name": "@default", "args": [{ "name": "value", "value": false }] }],
                }, push_subscriptions: {
                    name: "push_subscriptions",
                    type: "profiles_push_subscriptions",
                    isDataModel: true,
                    isArray: true,
                    backLink: 'profile',
                }, notification_settings: {
                    name: "notification_settings",
                    type: "profiles_notification_settings",
                    isDataModel: true,
                    isOptional: true,
                    backLink: 'profile',
                }, educations: {
                    name: "educations",
                    type: "profiles_educations",
                    isDataModel: true,
                    isArray: true,
                    backLink: 'user',
                }, work_experiences: {
                    name: "work_experiences",
                    type: "profiles_work_experiences",
                    isDataModel: true,
                    isArray: true,
                    backLink: 'user',
                }, listings: {
                    name: "listings",
                    type: "listings",
                    isDataModel: true,
                    isArray: true,
                    backLink: 'user',
                },
            }, uniqueConstraints: {
                id: {
                    name: "id",
                    fields: ["id"]
                },
            },
        },
        profiles_push_subscriptions: {
            name: 'profiles_push_subscriptions', fields: {
                id: {
                    name: "id",
                    type: "String",
                    isId: true,
                    attributes: [{ "name": "@default", "args": [{ "name": "value" }] }],
                }, user_id: {
                    name: "user_id",
                    type: "String",
                    isForeignKey: true,
                    relationField: 'profile',
                }, endpoint: {
                    name: "endpoint",
                    type: "String",
                }, p256dh: {
                    name: "p256dh",
                    type: "String",
                    isOptional: true,
                }, auth: {
                    name: "auth",
                    type: "String",
                    isOptional: true,
                }, expires_at: {
                    name: "expires_at",
                    type: "DateTime",
                    isOptional: true,
                }, created_at: {
                    name: "created_at",
                    type: "DateTime",
                    attributes: [{ "name": "@default", "args": [{ "name": "value" }] }],
                }, updated_at: {
                    name: "updated_at",
                    type: "DateTime",
                    attributes: [{ "name": "@default", "args": [{ "name": "value" }] }],
                }, profile: {
                    name: "profile",
                    type: "profiles",
                    isDataModel: true,
                    backLink: 'push_subscriptions',
                    isRelationOwner: true,
                    onDeleteAction: 'Cascade',
                    foreignKeyMapping: { "id": "user_id" },
                },
            }, uniqueConstraints: {
                id: {
                    name: "id",
                    fields: ["id"]
                }, user_id_endpoint: {
                    name: "user_id_endpoint",
                    fields: ["user_id", "endpoint"]
                },
            },
        },
        profiles_notification_settings: {
            name: 'profiles_notification_settings', fields: {
                id: {
                    name: "id",
                    type: "String",
                    isId: true,
                    attributes: [{ "name": "@default", "args": [{ "name": "value" }] }],
                }, user_id: {
                    name: "user_id",
                    type: "String",
                    isForeignKey: true,
                    relationField: 'profile',
                }, push_enabled: {
                    name: "push_enabled",
                    type: "Boolean",
                    attributes: [{ "name": "@default", "args": [{ "name": "value", "value": false }] }],
                }, push_new_requests: {
                    name: "push_new_requests",
                    type: "Boolean",
                    attributes: [{ "name": "@default", "args": [{ "name": "value", "value": true }] }],
                }, push_new_messages: {
                    name: "push_new_messages",
                    type: "Boolean",
                    attributes: [{ "name": "@default", "args": [{ "name": "value", "value": true }] }],
                }, push_status_changes: {
                    name: "push_status_changes",
                    type: "Boolean",
                    attributes: [{ "name": "@default", "args": [{ "name": "value", "value": true }] }],
                }, email_enabled: {
                    name: "email_enabled",
                    type: "Boolean",
                    attributes: [{ "name": "@default", "args": [{ "name": "value", "value": true }] }],
                }, email_new_requests: {
                    name: "email_new_requests",
                    type: "Boolean",
                    attributes: [{ "name": "@default", "args": [{ "name": "value", "value": true }] }],
                }, email_new_messages: {
                    name: "email_new_messages",
                    type: "Boolean",
                    attributes: [{ "name": "@default", "args": [{ "name": "value", "value": true }] }],
                }, email_digest: {
                    name: "email_digest",
                    type: "Boolean",
                    attributes: [{ "name": "@default", "args": [{ "name": "value", "value": true }] }],
                }, email_digest_frequency: {
                    name: "email_digest_frequency",
                    type: "String",
                    attributes: [{ "name": "@default", "args": [{ "name": "value", "value": "daily" }] }],
                }, quiet_hours_enabled: {
                    name: "quiet_hours_enabled",
                    type: "Boolean",
                    attributes: [{ "name": "@default", "args": [{ "name": "value", "value": false }] }],
                }, quiet_hours_start: {
                    name: "quiet_hours_start",
                    type: "String",
                    attributes: [{ "name": "@default", "args": [{ "name": "value", "value": "22:00" }] }],
                }, quiet_hours_end: {
                    name: "quiet_hours_end",
                    type: "String",
                    attributes: [{ "name": "@default", "args": [{ "name": "value", "value": "08:00" }] }],
                }, created_at: {
                    name: "created_at",
                    type: "DateTime",
                    attributes: [{ "name": "@default", "args": [{ "name": "value" }] }],
                }, updated_at: {
                    name: "updated_at",
                    type: "DateTime",
                    attributes: [{ "name": "@default", "args": [{ "name": "value" }] }],
                }, profile: {
                    name: "profile",
                    type: "profiles",
                    isDataModel: true,
                    backLink: 'notification_settings',
                    isRelationOwner: true,
                    onDeleteAction: 'Cascade',
                    foreignKeyMapping: { "id": "user_id" },
                },
            }, uniqueConstraints: {
                id: {
                    name: "id",
                    fields: ["id"]
                }, user_id: {
                    name: "user_id",
                    fields: ["user_id"]
                },
            },
        },
        profiles_educations: {
            name: 'profiles_educations', fields: {
                id: {
                    name: "id",
                    type: "String",
                    isId: true,
                    attributes: [{ "name": "@default", "args": [{ "name": "value" }] }],
                }, user_id: {
                    name: "user_id",
                    type: "String",
                    isForeignKey: true,
                    relationField: 'user',
                }, degree: {
                    name: "degree",
                    type: "String",
                }, institution: {
                    name: "institution",
                    type: "String",
                }, field_of_study: {
                    name: "field_of_study",
                    type: "String",
                    isOptional: true,
                }, start_date: {
                    name: "start_date",
                    type: "DateTime",
                }, end_date: {
                    name: "end_date",
                    type: "DateTime",
                    isOptional: true,
                }, is_current: {
                    name: "is_current",
                    type: "Boolean",
                    attributes: [{ "name": "@default", "args": [{ "name": "value", "value": false }] }],
                }, created_at: {
                    name: "created_at",
                    type: "DateTime",
                    attributes: [{ "name": "@default", "args": [{ "name": "value" }] }],
                }, updated_at: {
                    name: "updated_at",
                    type: "DateTime",
                    attributes: [{ "name": "@default", "args": [{ "name": "value" }] }],
                }, user: {
                    name: "user",
                    type: "profiles",
                    isDataModel: true,
                    backLink: 'educations',
                    isRelationOwner: true,
                    onDeleteAction: 'Cascade',
                    foreignKeyMapping: { "id": "user_id" },
                },
            }, uniqueConstraints: {
                id: {
                    name: "id",
                    fields: ["id"]
                },
            },
        },
        profiles_work_experiences: {
            name: 'profiles_work_experiences', fields: {
                id: {
                    name: "id",
                    type: "String",
                    isId: true,
                    attributes: [{ "name": "@default", "args": [{ "name": "value" }] }],
                }, user_id: {
                    name: "user_id",
                    type: "String",
                    isForeignKey: true,
                    relationField: 'user',
                }, company: {
                    name: "company",
                    type: "String",
                }, position: {
                    name: "position",
                    type: "String",
                }, description: {
                    name: "description",
                    type: "String",
                    isOptional: true,
                }, start_date: {
                    name: "start_date",
                    type: "DateTime",
                }, end_date: {
                    name: "end_date",
                    type: "DateTime",
                    isOptional: true,
                }, is_current: {
                    name: "is_current",
                    type: "Boolean",
                    attributes: [{ "name": "@default", "args": [{ "name": "value", "value": false }] }],
                }, created_at: {
                    name: "created_at",
                    type: "DateTime",
                    attributes: [{ "name": "@default", "args": [{ "name": "value" }] }],
                }, updated_at: {
                    name: "updated_at",
                    type: "DateTime",
                    attributes: [{ "name": "@default", "args": [{ "name": "value" }] }],
                }, user: {
                    name: "user",
                    type: "profiles",
                    isDataModel: true,
                    backLink: 'work_experiences',
                    isRelationOwner: true,
                    onDeleteAction: 'Cascade',
                    foreignKeyMapping: { "id": "user_id" },
                },
            }, uniqueConstraints: {
                id: {
                    name: "id",
                    fields: ["id"]
                },
            },
        },
        listings: {
            name: 'listings', fields: {
                id: {
                    name: "id",
                    type: "String",
                    isId: true,
                    attributes: [{ "name": "@default", "args": [{ "name": "value" }] }],
                }, user_id: {
                    name: "user_id",
                    type: "String",
                    isForeignKey: true,
                    relationField: 'user',
                }, category_id: {
                    name: "category_id",
                    type: "String",
                    isForeignKey: true,
                    relationField: 'category',
                }, title: {
                    name: "title",
                    type: "String",
                }, slug: {
                    name: "slug",
                    type: "String",
                }, description: {
                    name: "description",
                    type: "String",
                }, price: {
                    name: "price",
                    type: "Decimal",
                    isOptional: true,
                }, currency: {
                    name: "currency",
                    type: "String",
                    attributes: [{ "name": "@default", "args": [{ "name": "value", "value": "MNT" }] }],
                }, is_negotiable: {
                    name: "is_negotiable",
                    type: "Boolean",
                    attributes: [{ "name": "@default", "args": [{ "name": "value", "value": false }] }],
                }, city: {
                    name: "city",
                    type: "String",
                }, district: {
                    name: "district",
                    type: "String",
                    isOptional: true,
                }, address: {
                    name: "address",
                    type: "String",
                    isOptional: true,
                }, latitude: {
                    name: "latitude",
                    type: "Decimal",
                    isOptional: true,
                }, longitude: {
                    name: "longitude",
                    type: "Decimal",
                    isOptional: true,
                }, status: {
                    name: "status",
                    type: "ListingStatus",
                    attributes: [{ "name": "@default", "args": [{ "name": "value" }] }],
                }, is_active: {
                    name: "is_active",
                    type: "Boolean",
                    attributes: [{ "name": "@default", "args": [{ "name": "value", "value": true }] }],
                }, views_count: {
                    name: "views_count",
                    type: "Int",
                    attributes: [{ "name": "@default", "args": [{ "name": "value", "value": 0 }] }],
                }, created_at: {
                    name: "created_at",
                    type: "DateTime",
                    attributes: [{ "name": "@default", "args": [{ "name": "value" }] }],
                }, updated_at: {
                    name: "updated_at",
                    type: "DateTime",
                    attributes: [{ "name": "@updatedAt", "args": [] }],
                }, published_at: {
                    name: "published_at",
                    type: "DateTime",
                    isOptional: true,
                }, user: {
                    name: "user",
                    type: "profiles",
                    isDataModel: true,
                    backLink: 'listings',
                    isRelationOwner: true,
                    onDeleteAction: 'Cascade',
                    foreignKeyMapping: { "id": "user_id" },
                }, category: {
                    name: "category",
                    type: "categories",
                    isDataModel: true,
                    backLink: 'listings',
                    isRelationOwner: true,
                    foreignKeyMapping: { "id": "category_id" },
                }, images: {
                    name: "images",
                    type: "listings_images",
                    isDataModel: true,
                    isArray: true,
                    backLink: 'listing',
                },
            }, uniqueConstraints: {
                id: {
                    name: "id",
                    fields: ["id"]
                }, slug: {
                    name: "slug",
                    fields: ["slug"]
                },
            },
        },
        listings_images: {
            name: 'listings_images', fields: {
                id: {
                    name: "id",
                    type: "String",
                    isId: true,
                    attributes: [{ "name": "@default", "args": [{ "name": "value" }] }],
                }, listing_id: {
                    name: "listing_id",
                    type: "String",
                    isForeignKey: true,
                    relationField: 'listing',
                }, url: {
                    name: "url",
                    type: "String",
                }, alt: {
                    name: "alt",
                    type: "String",
                    isOptional: true,
                }, sort_order: {
                    name: "sort_order",
                    type: "Int",
                    attributes: [{ "name": "@default", "args": [{ "name": "value", "value": 0 }] }],
                }, is_cover: {
                    name: "is_cover",
                    type: "Boolean",
                    attributes: [{ "name": "@default", "args": [{ "name": "value", "value": false }] }],
                }, created_at: {
                    name: "created_at",
                    type: "DateTime",
                    attributes: [{ "name": "@default", "args": [{ "name": "value" }] }],
                }, listing: {
                    name: "listing",
                    type: "listings",
                    isDataModel: true,
                    backLink: 'images',
                    isRelationOwner: true,
                    onDeleteAction: 'Cascade',
                    foreignKeyMapping: { "id": "listing_id" },
                },
            }, uniqueConstraints: {
                id: {
                    name: "id",
                    fields: ["id"]
                },
            },
        },
        aimags: {
            name: 'aimags', fields: {
                id: {
                    name: "id",
                    type: "String",
                    isId: true,
                    attributes: [{ "name": "@default", "args": [{ "name": "value" }] }],
                }, name: {
                    name: "name",
                    type: "String",
                }, name_en: {
                    name: "name_en",
                    type: "String",
                    isOptional: true,
                }, code: {
                    name: "code",
                    type: "String",
                }, type: {
                    name: "type",
                    type: "AimagType",
                    attributes: [{ "name": "@default", "args": [{ "name": "value" }] }],
                }, sort_order: {
                    name: "sort_order",
                    type: "Int",
                    attributes: [{ "name": "@default", "args": [{ "name": "value", "value": 0 }] }],
                }, is_active: {
                    name: "is_active",
                    type: "Boolean",
                    attributes: [{ "name": "@default", "args": [{ "name": "value", "value": true }] }],
                }, created_at: {
                    name: "created_at",
                    type: "DateTime",
                    attributes: [{ "name": "@default", "args": [{ "name": "value" }] }],
                }, updated_at: {
                    name: "updated_at",
                    type: "DateTime",
                    attributes: [{ "name": "@updatedAt", "args": [] }],
                }, districts: {
                    name: "districts",
                    type: "districts",
                    isDataModel: true,
                    isArray: true,
                    backLink: 'aimag',
                },
            }, uniqueConstraints: {
                id: {
                    name: "id",
                    fields: ["id"]
                }, code: {
                    name: "code",
                    fields: ["code"]
                },
            },
        },
        districts: {
            name: 'districts', fields: {
                id: {
                    name: "id",
                    type: "String",
                    isId: true,
                    attributes: [{ "name": "@default", "args": [{ "name": "value" }] }],
                }, aimag_id: {
                    name: "aimag_id",
                    type: "String",
                    isForeignKey: true,
                    relationField: 'aimag',
                }, name: {
                    name: "name",
                    type: "String",
                }, name_en: {
                    name: "name_en",
                    type: "String",
                    isOptional: true,
                }, type: {
                    name: "type",
                    type: "DistrictType",
                    attributes: [{ "name": "@default", "args": [{ "name": "value" }] }],
                }, sort_order: {
                    name: "sort_order",
                    type: "Int",
                    attributes: [{ "name": "@default", "args": [{ "name": "value", "value": 0 }] }],
                }, is_active: {
                    name: "is_active",
                    type: "Boolean",
                    attributes: [{ "name": "@default", "args": [{ "name": "value", "value": true }] }],
                }, created_at: {
                    name: "created_at",
                    type: "DateTime",
                    attributes: [{ "name": "@default", "args": [{ "name": "value" }] }],
                }, updated_at: {
                    name: "updated_at",
                    type: "DateTime",
                    attributes: [{ "name": "@updatedAt", "args": [] }],
                }, aimag: {
                    name: "aimag",
                    type: "aimags",
                    isDataModel: true,
                    backLink: 'districts',
                    isRelationOwner: true,
                    onDeleteAction: 'Cascade',
                    foreignKeyMapping: { "id": "aimag_id" },
                }, khoroos: {
                    name: "khoroos",
                    type: "khoroos",
                    isDataModel: true,
                    isArray: true,
                    backLink: 'district',
                },
            }, uniqueConstraints: {
                id: {
                    name: "id",
                    fields: ["id"]
                },
            },
        },
        khoroos: {
            name: 'khoroos', fields: {
                id: {
                    name: "id",
                    type: "String",
                    isId: true,
                    attributes: [{ "name": "@default", "args": [{ "name": "value" }] }],
                }, district_id: {
                    name: "district_id",
                    type: "String",
                    isForeignKey: true,
                    relationField: 'district',
                }, name: {
                    name: "name",
                    type: "String",
                }, number: {
                    name: "number",
                    type: "Int",
                    isOptional: true,
                }, sort_order: {
                    name: "sort_order",
                    type: "Int",
                    attributes: [{ "name": "@default", "args": [{ "name": "value", "value": 0 }] }],
                }, is_active: {
                    name: "is_active",
                    type: "Boolean",
                    attributes: [{ "name": "@default", "args": [{ "name": "value", "value": true }] }],
                }, created_at: {
                    name: "created_at",
                    type: "DateTime",
                    attributes: [{ "name": "@default", "args": [{ "name": "value" }] }],
                }, updated_at: {
                    name: "updated_at",
                    type: "DateTime",
                    attributes: [{ "name": "@updatedAt", "args": [] }],
                }, district: {
                    name: "district",
                    type: "districts",
                    isDataModel: true,
                    backLink: 'khoroos',
                    isRelationOwner: true,
                    onDeleteAction: 'Cascade',
                    foreignKeyMapping: { "id": "district_id" },
                },
            }, uniqueConstraints: {
                id: {
                    name: "id",
                    fields: ["id"]
                },
            },
        },

    },
    deleteCascade: {
        profiles: ['profiles_push_subscriptions', 'profiles_notification_settings', 'profiles_educations', 'profiles_work_experiences', 'listings'],
        listings: ['listings_images'],
        aimags: ['districts'],
        districts: ['khoroos'],

    },
    authModel: 'profiles'

};
export default metadata;
