/******************************************************************************
 * This file was generated by ZenStack CLI.
 ******************************************************************************/

/* eslint-disable */

import type { Prisma, khoroos } from "@prisma/client";
import type { UseMutationOptions, UseQueryOptions, UseInfiniteQueryOptions, InfiniteData } from '@tanstack/react-query';
import { getHooksContext } from '@zenstackhq/tanstack-query/runtime-v5/react';
import { useModelQuery, useInfiniteModelQuery, useModelMutation } from '@zenstackhq/tanstack-query/runtime-v5/react';
import type { PickEnumerable, CheckSelect, QueryError, ExtraQueryOptions, ExtraMutationOptions } from '@zenstackhq/tanstack-query/runtime-v5';
import type { PolicyCrudKind } from '@zenstackhq/runtime'
import metadata from './__model_meta';
type DefaultError = QueryError;
import { useSuspenseModelQuery, useSuspenseInfiniteModelQuery } from '@zenstackhq/tanstack-query/runtime-v5/react';
import type { UseSuspenseQueryOptions, UseSuspenseInfiniteQueryOptions } from '@tanstack/react-query';

export function useCreatekhoroos(options?: Omit<(UseMutationOptions<(khoroos | undefined), DefaultError, Prisma.khoroosCreateArgs> & ExtraMutationOptions), 'mutationFn'>) {
    const { endpoint, fetch } = getHooksContext();
    const _mutation =
        useModelMutation<Prisma.khoroosCreateArgs, DefaultError, khoroos, true>('khoroos', 'POST', `${endpoint}/khoroos/create`, metadata, options, fetch, true)
        ;
    const mutation = {
        ..._mutation,
        mutateAsync: async <T extends Prisma.khoroosCreateArgs>(
            args: Prisma.SelectSubset<T, Prisma.khoroosCreateArgs>,
            options?: Omit<(UseMutationOptions<(CheckSelect<T, khoroos, Prisma.khoroosGetPayload<T>> | undefined), DefaultError, Prisma.SelectSubset<T, Prisma.khoroosCreateArgs>> & ExtraMutationOptions), 'mutationFn'>
        ) => {
            return (await _mutation.mutateAsync(
                args,
                options as any
            )) as (CheckSelect<T, khoroos, Prisma.khoroosGetPayload<T>> | undefined);
        },
    };
    return mutation;
}

export function useCreateManykhoroos(options?: Omit<(UseMutationOptions<Prisma.BatchPayload, DefaultError, Prisma.khoroosCreateManyArgs> & ExtraMutationOptions), 'mutationFn'>) {
    const { endpoint, fetch } = getHooksContext();
    const _mutation =
        useModelMutation<Prisma.khoroosCreateManyArgs, DefaultError, Prisma.BatchPayload, false>('khoroos', 'POST', `${endpoint}/khoroos/createMany`, metadata, options, fetch, false)
        ;
    const mutation = {
        ..._mutation,
        mutateAsync: async <T extends Prisma.khoroosCreateManyArgs>(
            args: Prisma.SelectSubset<T, Prisma.khoroosCreateManyArgs>,
            options?: Omit<(UseMutationOptions<Prisma.BatchPayload, DefaultError, Prisma.SelectSubset<T, Prisma.khoroosCreateManyArgs>> & ExtraMutationOptions), 'mutationFn'>
        ) => {
            return (await _mutation.mutateAsync(
                args,
                options as any
            )) as Prisma.BatchPayload;
        },
    };
    return mutation;
}

export function useFindManykhoroos<TArgs extends Prisma.khoroosFindManyArgs, TQueryFnData = Array<Prisma.khoroosGetPayload<TArgs> & { $optimistic?: boolean }>, TData = TQueryFnData, TError = DefaultError>(args?: Prisma.SelectSubset<TArgs, Prisma.khoroosFindManyArgs>, options?: (Omit<UseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useModelQuery<TQueryFnData, TData, TError>('khoroos', `${endpoint}/khoroos/findMany`, args, options, fetch);
}

export function useInfiniteFindManykhoroos<TArgs extends Prisma.khoroosFindManyArgs, TQueryFnData = Array<Prisma.khoroosGetPayload<TArgs>>, TData = TQueryFnData, TError = DefaultError>(args?: Prisma.SelectSubset<TArgs, Prisma.khoroosFindManyArgs>, options?: Omit<UseInfiniteQueryOptions<TQueryFnData, TError, InfiniteData<TData>>, 'queryKey' | 'initialPageParam'>) {
    options = options ?? { getNextPageParam: () => null };
    const { endpoint, fetch } = getHooksContext();
    return useInfiniteModelQuery<TQueryFnData, TData, TError>('khoroos', `${endpoint}/khoroos/findMany`, args, options, fetch);
}

export function useSuspenseFindManykhoroos<TArgs extends Prisma.khoroosFindManyArgs, TQueryFnData = Array<Prisma.khoroosGetPayload<TArgs> & { $optimistic?: boolean }>, TData = TQueryFnData, TError = DefaultError>(args?: Prisma.SelectSubset<TArgs, Prisma.khoroosFindManyArgs>, options?: (Omit<UseSuspenseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useSuspenseModelQuery<TQueryFnData, TData, TError>('khoroos', `${endpoint}/khoroos/findMany`, args, options, fetch);
}

export function useSuspenseInfiniteFindManykhoroos<TArgs extends Prisma.khoroosFindManyArgs, TQueryFnData = Array<Prisma.khoroosGetPayload<TArgs>>, TData = TQueryFnData, TError = DefaultError>(args?: Prisma.SelectSubset<TArgs, Prisma.khoroosFindManyArgs>, options?: Omit<UseSuspenseInfiniteQueryOptions<TQueryFnData, TError, InfiniteData<TData>>, 'queryKey' | 'initialPageParam'>) {
    options = options ?? { getNextPageParam: () => null };
    const { endpoint, fetch } = getHooksContext();
    return useSuspenseInfiniteModelQuery<TQueryFnData, TData, TError>('khoroos', `${endpoint}/khoroos/findMany`, args, options, fetch);
}

export function useFindUniquekhoroos<TArgs extends Prisma.khoroosFindUniqueArgs, TQueryFnData = Prisma.khoroosGetPayload<TArgs> & { $optimistic?: boolean }, TData = TQueryFnData, TError = DefaultError>(args: Prisma.SelectSubset<TArgs, Prisma.khoroosFindUniqueArgs>, options?: (Omit<UseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useModelQuery<TQueryFnData, TData, TError>('khoroos', `${endpoint}/khoroos/findUnique`, args, options, fetch);
}

export function useSuspenseFindUniquekhoroos<TArgs extends Prisma.khoroosFindUniqueArgs, TQueryFnData = Prisma.khoroosGetPayload<TArgs> & { $optimistic?: boolean }, TData = TQueryFnData, TError = DefaultError>(args: Prisma.SelectSubset<TArgs, Prisma.khoroosFindUniqueArgs>, options?: (Omit<UseSuspenseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useSuspenseModelQuery<TQueryFnData, TData, TError>('khoroos', `${endpoint}/khoroos/findUnique`, args, options, fetch);
}

export function useFindFirstkhoroos<TArgs extends Prisma.khoroosFindFirstArgs, TQueryFnData = Prisma.khoroosGetPayload<TArgs> & { $optimistic?: boolean }, TData = TQueryFnData, TError = DefaultError>(args?: Prisma.SelectSubset<TArgs, Prisma.khoroosFindFirstArgs>, options?: (Omit<UseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useModelQuery<TQueryFnData, TData, TError>('khoroos', `${endpoint}/khoroos/findFirst`, args, options, fetch);
}

export function useSuspenseFindFirstkhoroos<TArgs extends Prisma.khoroosFindFirstArgs, TQueryFnData = Prisma.khoroosGetPayload<TArgs> & { $optimistic?: boolean }, TData = TQueryFnData, TError = DefaultError>(args?: Prisma.SelectSubset<TArgs, Prisma.khoroosFindFirstArgs>, options?: (Omit<UseSuspenseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useSuspenseModelQuery<TQueryFnData, TData, TError>('khoroos', `${endpoint}/khoroos/findFirst`, args, options, fetch);
}

export function useUpdatekhoroos(options?: Omit<(UseMutationOptions<(khoroos | undefined), DefaultError, Prisma.khoroosUpdateArgs> & ExtraMutationOptions), 'mutationFn'>) {
    const { endpoint, fetch } = getHooksContext();
    const _mutation =
        useModelMutation<Prisma.khoroosUpdateArgs, DefaultError, khoroos, true>('khoroos', 'PUT', `${endpoint}/khoroos/update`, metadata, options, fetch, true)
        ;
    const mutation = {
        ..._mutation,
        mutateAsync: async <T extends Prisma.khoroosUpdateArgs>(
            args: Prisma.SelectSubset<T, Prisma.khoroosUpdateArgs>,
            options?: Omit<(UseMutationOptions<(CheckSelect<T, khoroos, Prisma.khoroosGetPayload<T>> | undefined), DefaultError, Prisma.SelectSubset<T, Prisma.khoroosUpdateArgs>> & ExtraMutationOptions), 'mutationFn'>
        ) => {
            return (await _mutation.mutateAsync(
                args,
                options as any
            )) as (CheckSelect<T, khoroos, Prisma.khoroosGetPayload<T>> | undefined);
        },
    };
    return mutation;
}

export function useUpdateManykhoroos(options?: Omit<(UseMutationOptions<Prisma.BatchPayload, DefaultError, Prisma.khoroosUpdateManyArgs> & ExtraMutationOptions), 'mutationFn'>) {
    const { endpoint, fetch } = getHooksContext();
    const _mutation =
        useModelMutation<Prisma.khoroosUpdateManyArgs, DefaultError, Prisma.BatchPayload, false>('khoroos', 'PUT', `${endpoint}/khoroos/updateMany`, metadata, options, fetch, false)
        ;
    const mutation = {
        ..._mutation,
        mutateAsync: async <T extends Prisma.khoroosUpdateManyArgs>(
            args: Prisma.SelectSubset<T, Prisma.khoroosUpdateManyArgs>,
            options?: Omit<(UseMutationOptions<Prisma.BatchPayload, DefaultError, Prisma.SelectSubset<T, Prisma.khoroosUpdateManyArgs>> & ExtraMutationOptions), 'mutationFn'>
        ) => {
            return (await _mutation.mutateAsync(
                args,
                options as any
            )) as Prisma.BatchPayload;
        },
    };
    return mutation;
}

export function useUpsertkhoroos(options?: Omit<(UseMutationOptions<(khoroos | undefined), DefaultError, Prisma.khoroosUpsertArgs> & ExtraMutationOptions), 'mutationFn'>) {
    const { endpoint, fetch } = getHooksContext();
    const _mutation =
        useModelMutation<Prisma.khoroosUpsertArgs, DefaultError, khoroos, true>('khoroos', 'POST', `${endpoint}/khoroos/upsert`, metadata, options, fetch, true)
        ;
    const mutation = {
        ..._mutation,
        mutateAsync: async <T extends Prisma.khoroosUpsertArgs>(
            args: Prisma.SelectSubset<T, Prisma.khoroosUpsertArgs>,
            options?: Omit<(UseMutationOptions<(CheckSelect<T, khoroos, Prisma.khoroosGetPayload<T>> | undefined), DefaultError, Prisma.SelectSubset<T, Prisma.khoroosUpsertArgs>> & ExtraMutationOptions), 'mutationFn'>
        ) => {
            return (await _mutation.mutateAsync(
                args,
                options as any
            )) as (CheckSelect<T, khoroos, Prisma.khoroosGetPayload<T>> | undefined);
        },
    };
    return mutation;
}

export function useDeletekhoroos(options?: Omit<(UseMutationOptions<(khoroos | undefined), DefaultError, Prisma.khoroosDeleteArgs> & ExtraMutationOptions), 'mutationFn'>) {
    const { endpoint, fetch } = getHooksContext();
    const _mutation =
        useModelMutation<Prisma.khoroosDeleteArgs, DefaultError, khoroos, true>('khoroos', 'DELETE', `${endpoint}/khoroos/delete`, metadata, options, fetch, true)
        ;
    const mutation = {
        ..._mutation,
        mutateAsync: async <T extends Prisma.khoroosDeleteArgs>(
            args: Prisma.SelectSubset<T, Prisma.khoroosDeleteArgs>,
            options?: Omit<(UseMutationOptions<(CheckSelect<T, khoroos, Prisma.khoroosGetPayload<T>> | undefined), DefaultError, Prisma.SelectSubset<T, Prisma.khoroosDeleteArgs>> & ExtraMutationOptions), 'mutationFn'>
        ) => {
            return (await _mutation.mutateAsync(
                args,
                options as any
            )) as (CheckSelect<T, khoroos, Prisma.khoroosGetPayload<T>> | undefined);
        },
    };
    return mutation;
}

export function useDeleteManykhoroos(options?: Omit<(UseMutationOptions<Prisma.BatchPayload, DefaultError, Prisma.khoroosDeleteManyArgs> & ExtraMutationOptions), 'mutationFn'>) {
    const { endpoint, fetch } = getHooksContext();
    const _mutation =
        useModelMutation<Prisma.khoroosDeleteManyArgs, DefaultError, Prisma.BatchPayload, false>('khoroos', 'DELETE', `${endpoint}/khoroos/deleteMany`, metadata, options, fetch, false)
        ;
    const mutation = {
        ..._mutation,
        mutateAsync: async <T extends Prisma.khoroosDeleteManyArgs>(
            args: Prisma.SelectSubset<T, Prisma.khoroosDeleteManyArgs>,
            options?: Omit<(UseMutationOptions<Prisma.BatchPayload, DefaultError, Prisma.SelectSubset<T, Prisma.khoroosDeleteManyArgs>> & ExtraMutationOptions), 'mutationFn'>
        ) => {
            return (await _mutation.mutateAsync(
                args,
                options as any
            )) as Prisma.BatchPayload;
        },
    };
    return mutation;
}

export function useAggregateKhoroos<TArgs extends Prisma.KhoroosAggregateArgs, TQueryFnData = Prisma.GetKhoroosAggregateType<TArgs>, TData = TQueryFnData, TError = DefaultError>(args: Prisma.SelectSubset<TArgs, Prisma.KhoroosAggregateArgs>, options?: (Omit<UseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useModelQuery<TQueryFnData, TData, TError>('Khoroos', `${endpoint}/khoroos/aggregate`, args, options, fetch);
}

export function useSuspenseAggregateKhoroos<TArgs extends Prisma.KhoroosAggregateArgs, TQueryFnData = Prisma.GetKhoroosAggregateType<TArgs>, TData = TQueryFnData, TError = DefaultError>(args: Prisma.SelectSubset<TArgs, Prisma.KhoroosAggregateArgs>, options?: (Omit<UseSuspenseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useSuspenseModelQuery<TQueryFnData, TData, TError>('Khoroos', `${endpoint}/khoroos/aggregate`, args, options, fetch);
}

export function useGroupBykhoroos<TArgs extends Prisma.khoroosGroupByArgs, HasSelectOrTake extends Prisma.Or<Prisma.Extends<'skip', Prisma.Keys<TArgs>>, Prisma.Extends<'take', Prisma.Keys<TArgs>>>, OrderByArg extends Prisma.True extends HasSelectOrTake ? { orderBy: Prisma.khoroosGroupByArgs['orderBy'] } : { orderBy?: Prisma.khoroosGroupByArgs['orderBy'] }, OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<TArgs['orderBy']>>>, ByFields extends Prisma.MaybeTupleToUnion<TArgs['by']>, ByValid extends Prisma.Has<ByFields, OrderFields>, HavingFields extends Prisma.GetHavingFields<TArgs['having']>, HavingValid extends Prisma.Has<ByFields, HavingFields>, ByEmpty extends TArgs['by'] extends never[] ? Prisma.True : Prisma.False, InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
        ? never
        : P extends string
        ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
        : [
            Error,
            'Field ',
            P,
            ` in "having" needs to be provided in "by"`,
        ]
    }[HavingFields]
    : 'take' extends Prisma.Keys<TArgs>
    ? 'orderBy' extends Prisma.Keys<TArgs>
    ? ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
        ? never
        : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
    }[OrderFields]
    : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<TArgs>
    ? 'orderBy' extends Prisma.Keys<TArgs>
    ? ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
        ? never
        : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
    }[OrderFields]
    : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
        ? never
        : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
    }[OrderFields], TQueryFnData = {} extends InputErrors ?
    Array<PickEnumerable<Prisma.KhoroosGroupByOutputType, TArgs['by']> &
    {
        [P in ((keyof TArgs) & (keyof Prisma.KhoroosGroupByOutputType))]: P extends '_count'
        ? TArgs[P] extends boolean
        ? number
        : Prisma.GetScalarType<TArgs[P], Prisma.KhoroosGroupByOutputType[P]>
        : Prisma.GetScalarType<TArgs[P], Prisma.KhoroosGroupByOutputType[P]>
    }
    > : InputErrors, TData = TQueryFnData, TError = DefaultError>(args: Prisma.SelectSubset<TArgs, Prisma.SubsetIntersection<TArgs, Prisma.khoroosGroupByArgs, OrderByArg> & InputErrors>, options?: (Omit<UseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useModelQuery<TQueryFnData, TData, TError>('khoroos', `${endpoint}/khoroos/groupBy`, args, options, fetch);
}

export function useSuspenseGroupBykhoroos<TArgs extends Prisma.khoroosGroupByArgs, HasSelectOrTake extends Prisma.Or<Prisma.Extends<'skip', Prisma.Keys<TArgs>>, Prisma.Extends<'take', Prisma.Keys<TArgs>>>, OrderByArg extends Prisma.True extends HasSelectOrTake ? { orderBy: Prisma.khoroosGroupByArgs['orderBy'] } : { orderBy?: Prisma.khoroosGroupByArgs['orderBy'] }, OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<TArgs['orderBy']>>>, ByFields extends Prisma.MaybeTupleToUnion<TArgs['by']>, ByValid extends Prisma.Has<ByFields, OrderFields>, HavingFields extends Prisma.GetHavingFields<TArgs['having']>, HavingValid extends Prisma.Has<ByFields, HavingFields>, ByEmpty extends TArgs['by'] extends never[] ? Prisma.True : Prisma.False, InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
        ? never
        : P extends string
        ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
        : [
            Error,
            'Field ',
            P,
            ` in "having" needs to be provided in "by"`,
        ]
    }[HavingFields]
    : 'take' extends Prisma.Keys<TArgs>
    ? 'orderBy' extends Prisma.Keys<TArgs>
    ? ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
        ? never
        : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
    }[OrderFields]
    : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<TArgs>
    ? 'orderBy' extends Prisma.Keys<TArgs>
    ? ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
        ? never
        : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
    }[OrderFields]
    : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
        ? never
        : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
    }[OrderFields], TQueryFnData = {} extends InputErrors ?
    Array<PickEnumerable<Prisma.KhoroosGroupByOutputType, TArgs['by']> &
    {
        [P in ((keyof TArgs) & (keyof Prisma.KhoroosGroupByOutputType))]: P extends '_count'
        ? TArgs[P] extends boolean
        ? number
        : Prisma.GetScalarType<TArgs[P], Prisma.KhoroosGroupByOutputType[P]>
        : Prisma.GetScalarType<TArgs[P], Prisma.KhoroosGroupByOutputType[P]>
    }
    > : InputErrors, TData = TQueryFnData, TError = DefaultError>(args: Prisma.SelectSubset<TArgs, Prisma.SubsetIntersection<TArgs, Prisma.khoroosGroupByArgs, OrderByArg> & InputErrors>, options?: (Omit<UseSuspenseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useSuspenseModelQuery<TQueryFnData, TData, TError>('khoroos', `${endpoint}/khoroos/groupBy`, args, options, fetch);
}

export function useCountkhoroos<TArgs extends Prisma.khoroosCountArgs, TQueryFnData = TArgs extends { select: any; } ? TArgs['select'] extends true ? number : Prisma.GetScalarType<TArgs['select'], Prisma.KhoroosCountAggregateOutputType> : number, TData = TQueryFnData, TError = DefaultError>(args?: Prisma.SelectSubset<TArgs, Prisma.khoroosCountArgs>, options?: (Omit<UseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useModelQuery<TQueryFnData, TData, TError>('khoroos', `${endpoint}/khoroos/count`, args, options, fetch);
}

export function useSuspenseCountkhoroos<TArgs extends Prisma.khoroosCountArgs, TQueryFnData = TArgs extends { select: any; } ? TArgs['select'] extends true ? number : Prisma.GetScalarType<TArgs['select'], Prisma.KhoroosCountAggregateOutputType> : number, TData = TQueryFnData, TError = DefaultError>(args?: Prisma.SelectSubset<TArgs, Prisma.khoroosCountArgs>, options?: (Omit<UseSuspenseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useSuspenseModelQuery<TQueryFnData, TData, TError>('khoroos', `${endpoint}/khoroos/count`, args, options, fetch);
}

export function useCheckkhoroos<TError = DefaultError>(args: { operation: PolicyCrudKind; where?: { id?: string; district_id?: string; name?: string; number?: number; sort_order?: number; is_active?: boolean }; }, options?: (Omit<UseQueryOptions<boolean, TError, boolean>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useModelQuery<boolean, boolean, TError>('khoroos', `${endpoint}/khoroos/check`, args, options, fetch);
}
