/******************************************************************************
 * This file was generated by ZenStack CLI.
 ******************************************************************************/

/* eslint-disable */

import type { Prisma, listing_requests } from "@prisma/client";
import type { UseMutationOptions, UseQueryOptions, UseInfiniteQueryOptions, InfiniteData } from '@tanstack/react-query';
import { getHooksContext } from '@zenstackhq/tanstack-query/runtime-v5/react';
import { useModelQuery, useInfiniteModelQuery, useModelMutation } from '@zenstackhq/tanstack-query/runtime-v5/react';
import type { PickEnumerable, CheckSelect, QueryError, ExtraQueryOptions, ExtraMutationOptions } from '@zenstackhq/tanstack-query/runtime-v5';
import type { PolicyCrudKind } from '@zenstackhq/runtime'
import metadata from './__model_meta';
type DefaultError = QueryError;
import { useSuspenseModelQuery, useSuspenseInfiniteModelQuery } from '@zenstackhq/tanstack-query/runtime-v5/react';
import type { UseSuspenseQueryOptions, UseSuspenseInfiniteQueryOptions } from '@tanstack/react-query';

export function useCreatelisting_requests(options?: Omit<(UseMutationOptions<(listing_requests | undefined), DefaultError, Prisma.listing_requestsCreateArgs> & ExtraMutationOptions), 'mutationFn'>) {
    const { endpoint, fetch } = getHooksContext();
    const _mutation =
        useModelMutation<Prisma.listing_requestsCreateArgs, DefaultError, listing_requests, true>('listing_requests', 'POST', `${endpoint}/listing_requests/create`, metadata, options, fetch, true)
        ;
    const mutation = {
        ..._mutation,
        mutateAsync: async <T extends Prisma.listing_requestsCreateArgs>(
            args: Prisma.SelectSubset<T, Prisma.listing_requestsCreateArgs>,
            options?: Omit<(UseMutationOptions<(CheckSelect<T, listing_requests, Prisma.listing_requestsGetPayload<T>> | undefined), DefaultError, Prisma.SelectSubset<T, Prisma.listing_requestsCreateArgs>> & ExtraMutationOptions), 'mutationFn'>
        ) => {
            return (await _mutation.mutateAsync(
                args,
                options as any
            )) as (CheckSelect<T, listing_requests, Prisma.listing_requestsGetPayload<T>> | undefined);
        },
    };
    return mutation;
}

export function useCreateManylisting_requests(options?: Omit<(UseMutationOptions<Prisma.BatchPayload, DefaultError, Prisma.listing_requestsCreateManyArgs> & ExtraMutationOptions), 'mutationFn'>) {
    const { endpoint, fetch } = getHooksContext();
    const _mutation =
        useModelMutation<Prisma.listing_requestsCreateManyArgs, DefaultError, Prisma.BatchPayload, false>('listing_requests', 'POST', `${endpoint}/listing_requests/createMany`, metadata, options, fetch, false)
        ;
    const mutation = {
        ..._mutation,
        mutateAsync: async <T extends Prisma.listing_requestsCreateManyArgs>(
            args: Prisma.SelectSubset<T, Prisma.listing_requestsCreateManyArgs>,
            options?: Omit<(UseMutationOptions<Prisma.BatchPayload, DefaultError, Prisma.SelectSubset<T, Prisma.listing_requestsCreateManyArgs>> & ExtraMutationOptions), 'mutationFn'>
        ) => {
            return (await _mutation.mutateAsync(
                args,
                options as any
            )) as Prisma.BatchPayload;
        },
    };
    return mutation;
}

export function useFindManylisting_requests<TArgs extends Prisma.listing_requestsFindManyArgs, TQueryFnData = Array<Prisma.listing_requestsGetPayload<TArgs> & { $optimistic?: boolean }>, TData = TQueryFnData, TError = DefaultError>(args?: Prisma.SelectSubset<TArgs, Prisma.listing_requestsFindManyArgs>, options?: (Omit<UseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useModelQuery<TQueryFnData, TData, TError>('listing_requests', `${endpoint}/listing_requests/findMany`, args, options, fetch);
}

export function useInfiniteFindManylisting_requests<TArgs extends Prisma.listing_requestsFindManyArgs, TQueryFnData = Array<Prisma.listing_requestsGetPayload<TArgs>>, TData = TQueryFnData, TError = DefaultError>(args?: Prisma.SelectSubset<TArgs, Prisma.listing_requestsFindManyArgs>, options?: Omit<UseInfiniteQueryOptions<TQueryFnData, TError, InfiniteData<TData>>, 'queryKey' | 'initialPageParam'>) {
    options = options ?? { getNextPageParam: () => null };
    const { endpoint, fetch } = getHooksContext();
    return useInfiniteModelQuery<TQueryFnData, TData, TError>('listing_requests', `${endpoint}/listing_requests/findMany`, args, options, fetch);
}

export function useSuspenseFindManylisting_requests<TArgs extends Prisma.listing_requestsFindManyArgs, TQueryFnData = Array<Prisma.listing_requestsGetPayload<TArgs> & { $optimistic?: boolean }>, TData = TQueryFnData, TError = DefaultError>(args?: Prisma.SelectSubset<TArgs, Prisma.listing_requestsFindManyArgs>, options?: (Omit<UseSuspenseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useSuspenseModelQuery<TQueryFnData, TData, TError>('listing_requests', `${endpoint}/listing_requests/findMany`, args, options, fetch);
}

export function useSuspenseInfiniteFindManylisting_requests<TArgs extends Prisma.listing_requestsFindManyArgs, TQueryFnData = Array<Prisma.listing_requestsGetPayload<TArgs>>, TData = TQueryFnData, TError = DefaultError>(args?: Prisma.SelectSubset<TArgs, Prisma.listing_requestsFindManyArgs>, options?: Omit<UseSuspenseInfiniteQueryOptions<TQueryFnData, TError, InfiniteData<TData>>, 'queryKey' | 'initialPageParam'>) {
    options = options ?? { getNextPageParam: () => null };
    const { endpoint, fetch } = getHooksContext();
    return useSuspenseInfiniteModelQuery<TQueryFnData, TData, TError>('listing_requests', `${endpoint}/listing_requests/findMany`, args, options, fetch);
}

export function useFindUniquelisting_requests<TArgs extends Prisma.listing_requestsFindUniqueArgs, TQueryFnData = Prisma.listing_requestsGetPayload<TArgs> & { $optimistic?: boolean }, TData = TQueryFnData, TError = DefaultError>(args: Prisma.SelectSubset<TArgs, Prisma.listing_requestsFindUniqueArgs>, options?: (Omit<UseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useModelQuery<TQueryFnData, TData, TError>('listing_requests', `${endpoint}/listing_requests/findUnique`, args, options, fetch);
}

export function useSuspenseFindUniquelisting_requests<TArgs extends Prisma.listing_requestsFindUniqueArgs, TQueryFnData = Prisma.listing_requestsGetPayload<TArgs> & { $optimistic?: boolean }, TData = TQueryFnData, TError = DefaultError>(args: Prisma.SelectSubset<TArgs, Prisma.listing_requestsFindUniqueArgs>, options?: (Omit<UseSuspenseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useSuspenseModelQuery<TQueryFnData, TData, TError>('listing_requests', `${endpoint}/listing_requests/findUnique`, args, options, fetch);
}

export function useFindFirstlisting_requests<TArgs extends Prisma.listing_requestsFindFirstArgs, TQueryFnData = Prisma.listing_requestsGetPayload<TArgs> & { $optimistic?: boolean }, TData = TQueryFnData, TError = DefaultError>(args?: Prisma.SelectSubset<TArgs, Prisma.listing_requestsFindFirstArgs>, options?: (Omit<UseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useModelQuery<TQueryFnData, TData, TError>('listing_requests', `${endpoint}/listing_requests/findFirst`, args, options, fetch);
}

export function useSuspenseFindFirstlisting_requests<TArgs extends Prisma.listing_requestsFindFirstArgs, TQueryFnData = Prisma.listing_requestsGetPayload<TArgs> & { $optimistic?: boolean }, TData = TQueryFnData, TError = DefaultError>(args?: Prisma.SelectSubset<TArgs, Prisma.listing_requestsFindFirstArgs>, options?: (Omit<UseSuspenseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useSuspenseModelQuery<TQueryFnData, TData, TError>('listing_requests', `${endpoint}/listing_requests/findFirst`, args, options, fetch);
}

export function useUpdatelisting_requests(options?: Omit<(UseMutationOptions<(listing_requests | undefined), DefaultError, Prisma.listing_requestsUpdateArgs> & ExtraMutationOptions), 'mutationFn'>) {
    const { endpoint, fetch } = getHooksContext();
    const _mutation =
        useModelMutation<Prisma.listing_requestsUpdateArgs, DefaultError, listing_requests, true>('listing_requests', 'PUT', `${endpoint}/listing_requests/update`, metadata, options, fetch, true)
        ;
    const mutation = {
        ..._mutation,
        mutateAsync: async <T extends Prisma.listing_requestsUpdateArgs>(
            args: Prisma.SelectSubset<T, Prisma.listing_requestsUpdateArgs>,
            options?: Omit<(UseMutationOptions<(CheckSelect<T, listing_requests, Prisma.listing_requestsGetPayload<T>> | undefined), DefaultError, Prisma.SelectSubset<T, Prisma.listing_requestsUpdateArgs>> & ExtraMutationOptions), 'mutationFn'>
        ) => {
            return (await _mutation.mutateAsync(
                args,
                options as any
            )) as (CheckSelect<T, listing_requests, Prisma.listing_requestsGetPayload<T>> | undefined);
        },
    };
    return mutation;
}

export function useUpdateManylisting_requests(options?: Omit<(UseMutationOptions<Prisma.BatchPayload, DefaultError, Prisma.listing_requestsUpdateManyArgs> & ExtraMutationOptions), 'mutationFn'>) {
    const { endpoint, fetch } = getHooksContext();
    const _mutation =
        useModelMutation<Prisma.listing_requestsUpdateManyArgs, DefaultError, Prisma.BatchPayload, false>('listing_requests', 'PUT', `${endpoint}/listing_requests/updateMany`, metadata, options, fetch, false)
        ;
    const mutation = {
        ..._mutation,
        mutateAsync: async <T extends Prisma.listing_requestsUpdateManyArgs>(
            args: Prisma.SelectSubset<T, Prisma.listing_requestsUpdateManyArgs>,
            options?: Omit<(UseMutationOptions<Prisma.BatchPayload, DefaultError, Prisma.SelectSubset<T, Prisma.listing_requestsUpdateManyArgs>> & ExtraMutationOptions), 'mutationFn'>
        ) => {
            return (await _mutation.mutateAsync(
                args,
                options as any
            )) as Prisma.BatchPayload;
        },
    };
    return mutation;
}

export function useUpsertlisting_requests(options?: Omit<(UseMutationOptions<(listing_requests | undefined), DefaultError, Prisma.listing_requestsUpsertArgs> & ExtraMutationOptions), 'mutationFn'>) {
    const { endpoint, fetch } = getHooksContext();
    const _mutation =
        useModelMutation<Prisma.listing_requestsUpsertArgs, DefaultError, listing_requests, true>('listing_requests', 'POST', `${endpoint}/listing_requests/upsert`, metadata, options, fetch, true)
        ;
    const mutation = {
        ..._mutation,
        mutateAsync: async <T extends Prisma.listing_requestsUpsertArgs>(
            args: Prisma.SelectSubset<T, Prisma.listing_requestsUpsertArgs>,
            options?: Omit<(UseMutationOptions<(CheckSelect<T, listing_requests, Prisma.listing_requestsGetPayload<T>> | undefined), DefaultError, Prisma.SelectSubset<T, Prisma.listing_requestsUpsertArgs>> & ExtraMutationOptions), 'mutationFn'>
        ) => {
            return (await _mutation.mutateAsync(
                args,
                options as any
            )) as (CheckSelect<T, listing_requests, Prisma.listing_requestsGetPayload<T>> | undefined);
        },
    };
    return mutation;
}

export function useDeletelisting_requests(options?: Omit<(UseMutationOptions<(listing_requests | undefined), DefaultError, Prisma.listing_requestsDeleteArgs> & ExtraMutationOptions), 'mutationFn'>) {
    const { endpoint, fetch } = getHooksContext();
    const _mutation =
        useModelMutation<Prisma.listing_requestsDeleteArgs, DefaultError, listing_requests, true>('listing_requests', 'DELETE', `${endpoint}/listing_requests/delete`, metadata, options, fetch, true)
        ;
    const mutation = {
        ..._mutation,
        mutateAsync: async <T extends Prisma.listing_requestsDeleteArgs>(
            args: Prisma.SelectSubset<T, Prisma.listing_requestsDeleteArgs>,
            options?: Omit<(UseMutationOptions<(CheckSelect<T, listing_requests, Prisma.listing_requestsGetPayload<T>> | undefined), DefaultError, Prisma.SelectSubset<T, Prisma.listing_requestsDeleteArgs>> & ExtraMutationOptions), 'mutationFn'>
        ) => {
            return (await _mutation.mutateAsync(
                args,
                options as any
            )) as (CheckSelect<T, listing_requests, Prisma.listing_requestsGetPayload<T>> | undefined);
        },
    };
    return mutation;
}

export function useDeleteManylisting_requests(options?: Omit<(UseMutationOptions<Prisma.BatchPayload, DefaultError, Prisma.listing_requestsDeleteManyArgs> & ExtraMutationOptions), 'mutationFn'>) {
    const { endpoint, fetch } = getHooksContext();
    const _mutation =
        useModelMutation<Prisma.listing_requestsDeleteManyArgs, DefaultError, Prisma.BatchPayload, false>('listing_requests', 'DELETE', `${endpoint}/listing_requests/deleteMany`, metadata, options, fetch, false)
        ;
    const mutation = {
        ..._mutation,
        mutateAsync: async <T extends Prisma.listing_requestsDeleteManyArgs>(
            args: Prisma.SelectSubset<T, Prisma.listing_requestsDeleteManyArgs>,
            options?: Omit<(UseMutationOptions<Prisma.BatchPayload, DefaultError, Prisma.SelectSubset<T, Prisma.listing_requestsDeleteManyArgs>> & ExtraMutationOptions), 'mutationFn'>
        ) => {
            return (await _mutation.mutateAsync(
                args,
                options as any
            )) as Prisma.BatchPayload;
        },
    };
    return mutation;
}

export function useAggregateListing_requests<TArgs extends Prisma.Listing_requestsAggregateArgs, TQueryFnData = Prisma.GetListing_requestsAggregateType<TArgs>, TData = TQueryFnData, TError = DefaultError>(args: Prisma.SelectSubset<TArgs, Prisma.Listing_requestsAggregateArgs>, options?: (Omit<UseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useModelQuery<TQueryFnData, TData, TError>('Listing_requests', `${endpoint}/listing_requests/aggregate`, args, options, fetch);
}

export function useSuspenseAggregateListing_requests<TArgs extends Prisma.Listing_requestsAggregateArgs, TQueryFnData = Prisma.GetListing_requestsAggregateType<TArgs>, TData = TQueryFnData, TError = DefaultError>(args: Prisma.SelectSubset<TArgs, Prisma.Listing_requestsAggregateArgs>, options?: (Omit<UseSuspenseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useSuspenseModelQuery<TQueryFnData, TData, TError>('Listing_requests', `${endpoint}/listing_requests/aggregate`, args, options, fetch);
}

export function useGroupBylisting_requests<TArgs extends Prisma.listing_requestsGroupByArgs, HasSelectOrTake extends Prisma.Or<Prisma.Extends<'skip', Prisma.Keys<TArgs>>, Prisma.Extends<'take', Prisma.Keys<TArgs>>>, OrderByArg extends Prisma.True extends HasSelectOrTake ? { orderBy: Prisma.listing_requestsGroupByArgs['orderBy'] } : { orderBy?: Prisma.listing_requestsGroupByArgs['orderBy'] }, OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<TArgs['orderBy']>>>, ByFields extends Prisma.MaybeTupleToUnion<TArgs['by']>, ByValid extends Prisma.Has<ByFields, OrderFields>, HavingFields extends Prisma.GetHavingFields<TArgs['having']>, HavingValid extends Prisma.Has<ByFields, HavingFields>, ByEmpty extends TArgs['by'] extends never[] ? Prisma.True : Prisma.False, InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
        ? never
        : P extends string
        ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
        : [
            Error,
            'Field ',
            P,
            ` in "having" needs to be provided in "by"`,
        ]
    }[HavingFields]
    : 'take' extends Prisma.Keys<TArgs>
    ? 'orderBy' extends Prisma.Keys<TArgs>
    ? ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
        ? never
        : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
    }[OrderFields]
    : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<TArgs>
    ? 'orderBy' extends Prisma.Keys<TArgs>
    ? ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
        ? never
        : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
    }[OrderFields]
    : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
        ? never
        : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
    }[OrderFields], TQueryFnData = {} extends InputErrors ?
    Array<PickEnumerable<Prisma.Listing_requestsGroupByOutputType, TArgs['by']> &
    {
        [P in ((keyof TArgs) & (keyof Prisma.Listing_requestsGroupByOutputType))]: P extends '_count'
        ? TArgs[P] extends boolean
        ? number
        : Prisma.GetScalarType<TArgs[P], Prisma.Listing_requestsGroupByOutputType[P]>
        : Prisma.GetScalarType<TArgs[P], Prisma.Listing_requestsGroupByOutputType[P]>
    }
    > : InputErrors, TData = TQueryFnData, TError = DefaultError>(args: Prisma.SelectSubset<TArgs, Prisma.SubsetIntersection<TArgs, Prisma.listing_requestsGroupByArgs, OrderByArg> & InputErrors>, options?: (Omit<UseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useModelQuery<TQueryFnData, TData, TError>('listing_requests', `${endpoint}/listing_requests/groupBy`, args, options, fetch);
}

export function useSuspenseGroupBylisting_requests<TArgs extends Prisma.listing_requestsGroupByArgs, HasSelectOrTake extends Prisma.Or<Prisma.Extends<'skip', Prisma.Keys<TArgs>>, Prisma.Extends<'take', Prisma.Keys<TArgs>>>, OrderByArg extends Prisma.True extends HasSelectOrTake ? { orderBy: Prisma.listing_requestsGroupByArgs['orderBy'] } : { orderBy?: Prisma.listing_requestsGroupByArgs['orderBy'] }, OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<TArgs['orderBy']>>>, ByFields extends Prisma.MaybeTupleToUnion<TArgs['by']>, ByValid extends Prisma.Has<ByFields, OrderFields>, HavingFields extends Prisma.GetHavingFields<TArgs['having']>, HavingValid extends Prisma.Has<ByFields, HavingFields>, ByEmpty extends TArgs['by'] extends never[] ? Prisma.True : Prisma.False, InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
        ? never
        : P extends string
        ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
        : [
            Error,
            'Field ',
            P,
            ` in "having" needs to be provided in "by"`,
        ]
    }[HavingFields]
    : 'take' extends Prisma.Keys<TArgs>
    ? 'orderBy' extends Prisma.Keys<TArgs>
    ? ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
        ? never
        : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
    }[OrderFields]
    : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<TArgs>
    ? 'orderBy' extends Prisma.Keys<TArgs>
    ? ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
        ? never
        : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
    }[OrderFields]
    : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
        ? never
        : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
    }[OrderFields], TQueryFnData = {} extends InputErrors ?
    Array<PickEnumerable<Prisma.Listing_requestsGroupByOutputType, TArgs['by']> &
    {
        [P in ((keyof TArgs) & (keyof Prisma.Listing_requestsGroupByOutputType))]: P extends '_count'
        ? TArgs[P] extends boolean
        ? number
        : Prisma.GetScalarType<TArgs[P], Prisma.Listing_requestsGroupByOutputType[P]>
        : Prisma.GetScalarType<TArgs[P], Prisma.Listing_requestsGroupByOutputType[P]>
    }
    > : InputErrors, TData = TQueryFnData, TError = DefaultError>(args: Prisma.SelectSubset<TArgs, Prisma.SubsetIntersection<TArgs, Prisma.listing_requestsGroupByArgs, OrderByArg> & InputErrors>, options?: (Omit<UseSuspenseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useSuspenseModelQuery<TQueryFnData, TData, TError>('listing_requests', `${endpoint}/listing_requests/groupBy`, args, options, fetch);
}

export function useCountlisting_requests<TArgs extends Prisma.listing_requestsCountArgs, TQueryFnData = TArgs extends { select: any; } ? TArgs['select'] extends true ? number : Prisma.GetScalarType<TArgs['select'], Prisma.Listing_requestsCountAggregateOutputType> : number, TData = TQueryFnData, TError = DefaultError>(args?: Prisma.SelectSubset<TArgs, Prisma.listing_requestsCountArgs>, options?: (Omit<UseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useModelQuery<TQueryFnData, TData, TError>('listing_requests', `${endpoint}/listing_requests/count`, args, options, fetch);
}

export function useSuspenseCountlisting_requests<TArgs extends Prisma.listing_requestsCountArgs, TQueryFnData = TArgs extends { select: any; } ? TArgs['select'] extends true ? number : Prisma.GetScalarType<TArgs['select'], Prisma.Listing_requestsCountAggregateOutputType> : number, TData = TQueryFnData, TError = DefaultError>(args?: Prisma.SelectSubset<TArgs, Prisma.listing_requestsCountArgs>, options?: (Omit<UseSuspenseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useSuspenseModelQuery<TQueryFnData, TData, TError>('listing_requests', `${endpoint}/listing_requests/count`, args, options, fetch);
}
import type { RequestStatus } from '@prisma/client';

export function useChecklisting_requests<TError = DefaultError>(args: { operation: PolicyCrudKind; where?: { id?: string; listing_id?: string; client_id?: string; provider_id?: string; message?: string; status?: RequestStatus; aimag_id?: string; district_id?: string; khoroo_id?: string; preferred_time?: string; note?: string; provider_response?: string }; }, options?: (Omit<UseQueryOptions<boolean, TError, boolean>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useModelQuery<boolean, boolean, TError>('listing_requests', `${endpoint}/listing_requests/check`, args, options, fetch);
}
