/******************************************************************************
 * This file was generated by ZenStack CLI.
 ******************************************************************************/

/* eslint-disable */

import type { Prisma, listing_boosts } from "@prisma/client";
import type {
  UseMutationOptions,
  UseQueryOptions,
  UseInfiniteQueryOptions,
  InfiniteData,
} from "@tanstack/react-query";
import { getHooksContext } from "@zenstackhq/tanstack-query/runtime-v5/react";
import {
  useModelQuery,
  useInfiniteModelQuery,
  useModelMutation,
} from "@zenstackhq/tanstack-query/runtime-v5/react";
import type {
  PickEnumerable,
  CheckSelect,
  QueryError,
  ExtraQueryOptions,
  ExtraMutationOptions,
} from "@zenstackhq/tanstack-query/runtime-v5";
import type { PolicyCrudKind } from "@zenstackhq/runtime";
import metadata from "./__model_meta";
type DefaultError = QueryError;
import {
  useSuspenseModelQuery,
  useSuspenseInfiniteModelQuery,
} from "@zenstackhq/tanstack-query/runtime-v5/react";
import type {
  UseSuspenseQueryOptions,
  UseSuspenseInfiniteQueryOptions,
} from "@tanstack/react-query";

export function useCreatelisting_boosts(
  options?: Omit<
    UseMutationOptions<listing_boosts | undefined, DefaultError, Prisma.listing_boostsCreateArgs> &
      ExtraMutationOptions,
    "mutationFn"
  >
) {
  const { endpoint, fetch } = getHooksContext();
  const _mutation = useModelMutation<
    Prisma.listing_boostsCreateArgs,
    DefaultError,
    listing_boosts,
    true
  >("listing_boosts", "POST", `${endpoint}/listing_boosts/create`, metadata, options, fetch, true);
  const mutation = {
    ..._mutation,
    mutateAsync: async <T extends Prisma.listing_boostsCreateArgs>(
      args: Prisma.SelectSubset<T, Prisma.listing_boostsCreateArgs>,
      options?: Omit<
        UseMutationOptions<
          CheckSelect<T, listing_boosts, Prisma.listing_boostsGetPayload<T>> | undefined,
          DefaultError,
          Prisma.SelectSubset<T, Prisma.listing_boostsCreateArgs>
        > &
          ExtraMutationOptions,
        "mutationFn"
      >
    ) => {
      return (await _mutation.mutateAsync(args, options as any)) as
        | CheckSelect<T, listing_boosts, Prisma.listing_boostsGetPayload<T>>
        | undefined;
    },
  };
  return mutation;
}

export function useCreateManylisting_boosts(
  options?: Omit<
    UseMutationOptions<Prisma.BatchPayload, DefaultError, Prisma.listing_boostsCreateManyArgs> &
      ExtraMutationOptions,
    "mutationFn"
  >
) {
  const { endpoint, fetch } = getHooksContext();
  const _mutation = useModelMutation<
    Prisma.listing_boostsCreateManyArgs,
    DefaultError,
    Prisma.BatchPayload,
    false
  >(
    "listing_boosts",
    "POST",
    `${endpoint}/listing_boosts/createMany`,
    metadata,
    options,
    fetch,
    false
  );
  const mutation = {
    ..._mutation,
    mutateAsync: async <T extends Prisma.listing_boostsCreateManyArgs>(
      args: Prisma.SelectSubset<T, Prisma.listing_boostsCreateManyArgs>,
      options?: Omit<
        UseMutationOptions<
          Prisma.BatchPayload,
          DefaultError,
          Prisma.SelectSubset<T, Prisma.listing_boostsCreateManyArgs>
        > &
          ExtraMutationOptions,
        "mutationFn"
      >
    ) => {
      return (await _mutation.mutateAsync(args, options as any)) as Prisma.BatchPayload;
    },
  };
  return mutation;
}

export function useFindManylisting_boosts<
  TArgs extends Prisma.listing_boostsFindManyArgs,
  TQueryFnData = Array<Prisma.listing_boostsGetPayload<TArgs> & { $optimistic?: boolean }>,
  TData = TQueryFnData,
  TError = DefaultError,
>(
  args?: Prisma.SelectSubset<TArgs, Prisma.listing_boostsFindManyArgs>,
  options?: Omit<UseQueryOptions<TQueryFnData, TError, TData>, "queryKey"> & ExtraQueryOptions
) {
  const { endpoint, fetch } = getHooksContext();
  return useModelQuery<TQueryFnData, TData, TError>(
    "listing_boosts",
    `${endpoint}/listing_boosts/findMany`,
    args,
    options,
    fetch
  );
}

export function useInfiniteFindManylisting_boosts<
  TArgs extends Prisma.listing_boostsFindManyArgs,
  TQueryFnData = Array<Prisma.listing_boostsGetPayload<TArgs>>,
  TData = TQueryFnData,
  TError = DefaultError,
>(
  args?: Prisma.SelectSubset<TArgs, Prisma.listing_boostsFindManyArgs>,
  options?: Omit<
    UseInfiniteQueryOptions<TQueryFnData, TError, InfiniteData<TData>>,
    "queryKey" | "initialPageParam"
  >
) {
  options = options ?? { getNextPageParam: () => null };
  const { endpoint, fetch } = getHooksContext();
  return useInfiniteModelQuery<TQueryFnData, TData, TError>(
    "listing_boosts",
    `${endpoint}/listing_boosts/findMany`,
    args,
    options,
    fetch
  );
}

export function useSuspenseFindManylisting_boosts<
  TArgs extends Prisma.listing_boostsFindManyArgs,
  TQueryFnData = Array<Prisma.listing_boostsGetPayload<TArgs> & { $optimistic?: boolean }>,
  TData = TQueryFnData,
  TError = DefaultError,
>(
  args?: Prisma.SelectSubset<TArgs, Prisma.listing_boostsFindManyArgs>,
  options?: Omit<UseSuspenseQueryOptions<TQueryFnData, TError, TData>, "queryKey"> &
    ExtraQueryOptions
) {
  const { endpoint, fetch } = getHooksContext();
  return useSuspenseModelQuery<TQueryFnData, TData, TError>(
    "listing_boosts",
    `${endpoint}/listing_boosts/findMany`,
    args,
    options,
    fetch
  );
}

export function useSuspenseInfiniteFindManylisting_boosts<
  TArgs extends Prisma.listing_boostsFindManyArgs,
  TQueryFnData = Array<Prisma.listing_boostsGetPayload<TArgs>>,
  TData = TQueryFnData,
  TError = DefaultError,
>(
  args?: Prisma.SelectSubset<TArgs, Prisma.listing_boostsFindManyArgs>,
  options?: Omit<
    UseSuspenseInfiniteQueryOptions<TQueryFnData, TError, InfiniteData<TData>>,
    "queryKey" | "initialPageParam"
  >
) {
  options = options ?? { getNextPageParam: () => null };
  const { endpoint, fetch } = getHooksContext();
  return useSuspenseInfiniteModelQuery<TQueryFnData, TData, TError>(
    "listing_boosts",
    `${endpoint}/listing_boosts/findMany`,
    args,
    options,
    fetch
  );
}

export function useFindUniquelisting_boosts<
  TArgs extends Prisma.listing_boostsFindUniqueArgs,
  TQueryFnData = Prisma.listing_boostsGetPayload<TArgs> & { $optimistic?: boolean },
  TData = TQueryFnData,
  TError = DefaultError,
>(
  args: Prisma.SelectSubset<TArgs, Prisma.listing_boostsFindUniqueArgs>,
  options?: Omit<UseQueryOptions<TQueryFnData, TError, TData>, "queryKey"> & ExtraQueryOptions
) {
  const { endpoint, fetch } = getHooksContext();
  return useModelQuery<TQueryFnData, TData, TError>(
    "listing_boosts",
    `${endpoint}/listing_boosts/findUnique`,
    args,
    options,
    fetch
  );
}

export function useSuspenseFindUniquelisting_boosts<
  TArgs extends Prisma.listing_boostsFindUniqueArgs,
  TQueryFnData = Prisma.listing_boostsGetPayload<TArgs> & { $optimistic?: boolean },
  TData = TQueryFnData,
  TError = DefaultError,
>(
  args: Prisma.SelectSubset<TArgs, Prisma.listing_boostsFindUniqueArgs>,
  options?: Omit<UseSuspenseQueryOptions<TQueryFnData, TError, TData>, "queryKey"> &
    ExtraQueryOptions
) {
  const { endpoint, fetch } = getHooksContext();
  return useSuspenseModelQuery<TQueryFnData, TData, TError>(
    "listing_boosts",
    `${endpoint}/listing_boosts/findUnique`,
    args,
    options,
    fetch
  );
}

export function useFindFirstlisting_boosts<
  TArgs extends Prisma.listing_boostsFindFirstArgs,
  TQueryFnData = Prisma.listing_boostsGetPayload<TArgs> & { $optimistic?: boolean },
  TData = TQueryFnData,
  TError = DefaultError,
>(
  args?: Prisma.SelectSubset<TArgs, Prisma.listing_boostsFindFirstArgs>,
  options?: Omit<UseQueryOptions<TQueryFnData, TError, TData>, "queryKey"> & ExtraQueryOptions
) {
  const { endpoint, fetch } = getHooksContext();
  return useModelQuery<TQueryFnData, TData, TError>(
    "listing_boosts",
    `${endpoint}/listing_boosts/findFirst`,
    args,
    options,
    fetch
  );
}

export function useSuspenseFindFirstlisting_boosts<
  TArgs extends Prisma.listing_boostsFindFirstArgs,
  TQueryFnData = Prisma.listing_boostsGetPayload<TArgs> & { $optimistic?: boolean },
  TData = TQueryFnData,
  TError = DefaultError,
>(
  args?: Prisma.SelectSubset<TArgs, Prisma.listing_boostsFindFirstArgs>,
  options?: Omit<UseSuspenseQueryOptions<TQueryFnData, TError, TData>, "queryKey"> &
    ExtraQueryOptions
) {
  const { endpoint, fetch } = getHooksContext();
  return useSuspenseModelQuery<TQueryFnData, TData, TError>(
    "listing_boosts",
    `${endpoint}/listing_boosts/findFirst`,
    args,
    options,
    fetch
  );
}

export function useUpdatelisting_boosts(
  options?: Omit<
    UseMutationOptions<listing_boosts | undefined, DefaultError, Prisma.listing_boostsUpdateArgs> &
      ExtraMutationOptions,
    "mutationFn"
  >
) {
  const { endpoint, fetch } = getHooksContext();
  const _mutation = useModelMutation<
    Prisma.listing_boostsUpdateArgs,
    DefaultError,
    listing_boosts,
    true
  >("listing_boosts", "PUT", `${endpoint}/listing_boosts/update`, metadata, options, fetch, true);
  const mutation = {
    ..._mutation,
    mutateAsync: async <T extends Prisma.listing_boostsUpdateArgs>(
      args: Prisma.SelectSubset<T, Prisma.listing_boostsUpdateArgs>,
      options?: Omit<
        UseMutationOptions<
          CheckSelect<T, listing_boosts, Prisma.listing_boostsGetPayload<T>> | undefined,
          DefaultError,
          Prisma.SelectSubset<T, Prisma.listing_boostsUpdateArgs>
        > &
          ExtraMutationOptions,
        "mutationFn"
      >
    ) => {
      return (await _mutation.mutateAsync(args, options as any)) as
        | CheckSelect<T, listing_boosts, Prisma.listing_boostsGetPayload<T>>
        | undefined;
    },
  };
  return mutation;
}

export function useUpdateManylisting_boosts(
  options?: Omit<
    UseMutationOptions<Prisma.BatchPayload, DefaultError, Prisma.listing_boostsUpdateManyArgs> &
      ExtraMutationOptions,
    "mutationFn"
  >
) {
  const { endpoint, fetch } = getHooksContext();
  const _mutation = useModelMutation<
    Prisma.listing_boostsUpdateManyArgs,
    DefaultError,
    Prisma.BatchPayload,
    false
  >(
    "listing_boosts",
    "PUT",
    `${endpoint}/listing_boosts/updateMany`,
    metadata,
    options,
    fetch,
    false
  );
  const mutation = {
    ..._mutation,
    mutateAsync: async <T extends Prisma.listing_boostsUpdateManyArgs>(
      args: Prisma.SelectSubset<T, Prisma.listing_boostsUpdateManyArgs>,
      options?: Omit<
        UseMutationOptions<
          Prisma.BatchPayload,
          DefaultError,
          Prisma.SelectSubset<T, Prisma.listing_boostsUpdateManyArgs>
        > &
          ExtraMutationOptions,
        "mutationFn"
      >
    ) => {
      return (await _mutation.mutateAsync(args, options as any)) as Prisma.BatchPayload;
    },
  };
  return mutation;
}

export function useUpsertlisting_boosts(
  options?: Omit<
    UseMutationOptions<listing_boosts | undefined, DefaultError, Prisma.listing_boostsUpsertArgs> &
      ExtraMutationOptions,
    "mutationFn"
  >
) {
  const { endpoint, fetch } = getHooksContext();
  const _mutation = useModelMutation<
    Prisma.listing_boostsUpsertArgs,
    DefaultError,
    listing_boosts,
    true
  >("listing_boosts", "POST", `${endpoint}/listing_boosts/upsert`, metadata, options, fetch, true);
  const mutation = {
    ..._mutation,
    mutateAsync: async <T extends Prisma.listing_boostsUpsertArgs>(
      args: Prisma.SelectSubset<T, Prisma.listing_boostsUpsertArgs>,
      options?: Omit<
        UseMutationOptions<
          CheckSelect<T, listing_boosts, Prisma.listing_boostsGetPayload<T>> | undefined,
          DefaultError,
          Prisma.SelectSubset<T, Prisma.listing_boostsUpsertArgs>
        > &
          ExtraMutationOptions,
        "mutationFn"
      >
    ) => {
      return (await _mutation.mutateAsync(args, options as any)) as
        | CheckSelect<T, listing_boosts, Prisma.listing_boostsGetPayload<T>>
        | undefined;
    },
  };
  return mutation;
}

export function useDeletelisting_boosts(
  options?: Omit<
    UseMutationOptions<listing_boosts | undefined, DefaultError, Prisma.listing_boostsDeleteArgs> &
      ExtraMutationOptions,
    "mutationFn"
  >
) {
  const { endpoint, fetch } = getHooksContext();
  const _mutation = useModelMutation<
    Prisma.listing_boostsDeleteArgs,
    DefaultError,
    listing_boosts,
    true
  >(
    "listing_boosts",
    "DELETE",
    `${endpoint}/listing_boosts/delete`,
    metadata,
    options,
    fetch,
    true
  );
  const mutation = {
    ..._mutation,
    mutateAsync: async <T extends Prisma.listing_boostsDeleteArgs>(
      args: Prisma.SelectSubset<T, Prisma.listing_boostsDeleteArgs>,
      options?: Omit<
        UseMutationOptions<
          CheckSelect<T, listing_boosts, Prisma.listing_boostsGetPayload<T>> | undefined,
          DefaultError,
          Prisma.SelectSubset<T, Prisma.listing_boostsDeleteArgs>
        > &
          ExtraMutationOptions,
        "mutationFn"
      >
    ) => {
      return (await _mutation.mutateAsync(args, options as any)) as
        | CheckSelect<T, listing_boosts, Prisma.listing_boostsGetPayload<T>>
        | undefined;
    },
  };
  return mutation;
}

export function useDeleteManylisting_boosts(
  options?: Omit<
    UseMutationOptions<Prisma.BatchPayload, DefaultError, Prisma.listing_boostsDeleteManyArgs> &
      ExtraMutationOptions,
    "mutationFn"
  >
) {
  const { endpoint, fetch } = getHooksContext();
  const _mutation = useModelMutation<
    Prisma.listing_boostsDeleteManyArgs,
    DefaultError,
    Prisma.BatchPayload,
    false
  >(
    "listing_boosts",
    "DELETE",
    `${endpoint}/listing_boosts/deleteMany`,
    metadata,
    options,
    fetch,
    false
  );
  const mutation = {
    ..._mutation,
    mutateAsync: async <T extends Prisma.listing_boostsDeleteManyArgs>(
      args: Prisma.SelectSubset<T, Prisma.listing_boostsDeleteManyArgs>,
      options?: Omit<
        UseMutationOptions<
          Prisma.BatchPayload,
          DefaultError,
          Prisma.SelectSubset<T, Prisma.listing_boostsDeleteManyArgs>
        > &
          ExtraMutationOptions,
        "mutationFn"
      >
    ) => {
      return (await _mutation.mutateAsync(args, options as any)) as Prisma.BatchPayload;
    },
  };
  return mutation;
}

export function useAggregateListing_boosts<
  TArgs extends Prisma.Listing_boostsAggregateArgs,
  TQueryFnData = Prisma.GetListing_boostsAggregateType<TArgs>,
  TData = TQueryFnData,
  TError = DefaultError,
>(
  args: Prisma.SelectSubset<TArgs, Prisma.Listing_boostsAggregateArgs>,
  options?: Omit<UseQueryOptions<TQueryFnData, TError, TData>, "queryKey"> & ExtraQueryOptions
) {
  const { endpoint, fetch } = getHooksContext();
  return useModelQuery<TQueryFnData, TData, TError>(
    "Listing_boosts",
    `${endpoint}/listing_boosts/aggregate`,
    args,
    options,
    fetch
  );
}

export function useSuspenseAggregateListing_boosts<
  TArgs extends Prisma.Listing_boostsAggregateArgs,
  TQueryFnData = Prisma.GetListing_boostsAggregateType<TArgs>,
  TData = TQueryFnData,
  TError = DefaultError,
>(
  args: Prisma.SelectSubset<TArgs, Prisma.Listing_boostsAggregateArgs>,
  options?: Omit<UseSuspenseQueryOptions<TQueryFnData, TError, TData>, "queryKey"> &
    ExtraQueryOptions
) {
  const { endpoint, fetch } = getHooksContext();
  return useSuspenseModelQuery<TQueryFnData, TData, TError>(
    "Listing_boosts",
    `${endpoint}/listing_boosts/aggregate`,
    args,
    options,
    fetch
  );
}

export function useGroupBylisting_boosts<
  TArgs extends Prisma.listing_boostsGroupByArgs,
  HasSelectOrTake extends Prisma.Or<
    Prisma.Extends<"skip", Prisma.Keys<TArgs>>,
    Prisma.Extends<"take", Prisma.Keys<TArgs>>
  >,
  OrderByArg extends Prisma.True extends HasSelectOrTake
    ? { orderBy: Prisma.listing_boostsGroupByArgs["orderBy"] }
    : { orderBy?: Prisma.listing_boostsGroupByArgs["orderBy"] },
  OrderFields extends Prisma.ExcludeUnderscoreKeys<
    Prisma.Keys<Prisma.MaybeTupleToUnion<TArgs["orderBy"]>>
  >,
  ByFields extends Prisma.MaybeTupleToUnion<TArgs["by"]>,
  ByValid extends Prisma.Has<ByFields, OrderFields>,
  HavingFields extends Prisma.GetHavingFields<TArgs["having"]>,
  HavingValid extends Prisma.Has<ByFields, HavingFields>,
  ByEmpty extends TArgs["by"] extends never[] ? Prisma.True : Prisma.False,
  InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
      ? {
          [P in HavingFields]: P extends ByFields
            ? never
            : P extends string
              ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
              : [Error, "Field ", P, ` in "having" needs to be provided in "by"`];
        }[HavingFields]
      : "take" extends Prisma.Keys<TArgs>
        ? "orderBy" extends Prisma.Keys<TArgs>
          ? ByValid extends Prisma.True
            ? {}
            : {
                [P in OrderFields]: P extends ByFields
                  ? never
                  : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`;
              }[OrderFields]
          : 'Error: If you provide "take", you also need to provide "orderBy"'
        : "skip" extends Prisma.Keys<TArgs>
          ? "orderBy" extends Prisma.Keys<TArgs>
            ? ByValid extends Prisma.True
              ? {}
              : {
                  [P in OrderFields]: P extends ByFields
                    ? never
                    : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`;
                }[OrderFields]
            : 'Error: If you provide "skip", you also need to provide "orderBy"'
          : ByValid extends Prisma.True
            ? {}
            : {
                [P in OrderFields]: P extends ByFields
                  ? never
                  : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`;
              }[OrderFields],
  TQueryFnData = {} extends InputErrors
    ? Array<
        PickEnumerable<Prisma.Listing_boostsGroupByOutputType, TArgs["by"]> & {
          [P in keyof TArgs & keyof Prisma.Listing_boostsGroupByOutputType]: P extends "_count"
            ? TArgs[P] extends boolean
              ? number
              : Prisma.GetScalarType<TArgs[P], Prisma.Listing_boostsGroupByOutputType[P]>
            : Prisma.GetScalarType<TArgs[P], Prisma.Listing_boostsGroupByOutputType[P]>;
        }
      >
    : InputErrors,
  TData = TQueryFnData,
  TError = DefaultError,
>(
  args: Prisma.SelectSubset<
    TArgs,
    Prisma.SubsetIntersection<TArgs, Prisma.listing_boostsGroupByArgs, OrderByArg> & InputErrors
  >,
  options?: Omit<UseQueryOptions<TQueryFnData, TError, TData>, "queryKey"> & ExtraQueryOptions
) {
  const { endpoint, fetch } = getHooksContext();
  return useModelQuery<TQueryFnData, TData, TError>(
    "listing_boosts",
    `${endpoint}/listing_boosts/groupBy`,
    args,
    options,
    fetch
  );
}

export function useSuspenseGroupBylisting_boosts<
  TArgs extends Prisma.listing_boostsGroupByArgs,
  HasSelectOrTake extends Prisma.Or<
    Prisma.Extends<"skip", Prisma.Keys<TArgs>>,
    Prisma.Extends<"take", Prisma.Keys<TArgs>>
  >,
  OrderByArg extends Prisma.True extends HasSelectOrTake
    ? { orderBy: Prisma.listing_boostsGroupByArgs["orderBy"] }
    : { orderBy?: Prisma.listing_boostsGroupByArgs["orderBy"] },
  OrderFields extends Prisma.ExcludeUnderscoreKeys<
    Prisma.Keys<Prisma.MaybeTupleToUnion<TArgs["orderBy"]>>
  >,
  ByFields extends Prisma.MaybeTupleToUnion<TArgs["by"]>,
  ByValid extends Prisma.Has<ByFields, OrderFields>,
  HavingFields extends Prisma.GetHavingFields<TArgs["having"]>,
  HavingValid extends Prisma.Has<ByFields, HavingFields>,
  ByEmpty extends TArgs["by"] extends never[] ? Prisma.True : Prisma.False,
  InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
      ? {
          [P in HavingFields]: P extends ByFields
            ? never
            : P extends string
              ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
              : [Error, "Field ", P, ` in "having" needs to be provided in "by"`];
        }[HavingFields]
      : "take" extends Prisma.Keys<TArgs>
        ? "orderBy" extends Prisma.Keys<TArgs>
          ? ByValid extends Prisma.True
            ? {}
            : {
                [P in OrderFields]: P extends ByFields
                  ? never
                  : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`;
              }[OrderFields]
          : 'Error: If you provide "take", you also need to provide "orderBy"'
        : "skip" extends Prisma.Keys<TArgs>
          ? "orderBy" extends Prisma.Keys<TArgs>
            ? ByValid extends Prisma.True
              ? {}
              : {
                  [P in OrderFields]: P extends ByFields
                    ? never
                    : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`;
                }[OrderFields]
            : 'Error: If you provide "skip", you also need to provide "orderBy"'
          : ByValid extends Prisma.True
            ? {}
            : {
                [P in OrderFields]: P extends ByFields
                  ? never
                  : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`;
              }[OrderFields],
  TQueryFnData = {} extends InputErrors
    ? Array<
        PickEnumerable<Prisma.Listing_boostsGroupByOutputType, TArgs["by"]> & {
          [P in keyof TArgs & keyof Prisma.Listing_boostsGroupByOutputType]: P extends "_count"
            ? TArgs[P] extends boolean
              ? number
              : Prisma.GetScalarType<TArgs[P], Prisma.Listing_boostsGroupByOutputType[P]>
            : Prisma.GetScalarType<TArgs[P], Prisma.Listing_boostsGroupByOutputType[P]>;
        }
      >
    : InputErrors,
  TData = TQueryFnData,
  TError = DefaultError,
>(
  args: Prisma.SelectSubset<
    TArgs,
    Prisma.SubsetIntersection<TArgs, Prisma.listing_boostsGroupByArgs, OrderByArg> & InputErrors
  >,
  options?: Omit<UseSuspenseQueryOptions<TQueryFnData, TError, TData>, "queryKey"> &
    ExtraQueryOptions
) {
  const { endpoint, fetch } = getHooksContext();
  return useSuspenseModelQuery<TQueryFnData, TData, TError>(
    "listing_boosts",
    `${endpoint}/listing_boosts/groupBy`,
    args,
    options,
    fetch
  );
}

export function useCountlisting_boosts<
  TArgs extends Prisma.listing_boostsCountArgs,
  TQueryFnData = TArgs extends { select: any }
    ? TArgs["select"] extends true
      ? number
      : Prisma.GetScalarType<TArgs["select"], Prisma.Listing_boostsCountAggregateOutputType>
    : number,
  TData = TQueryFnData,
  TError = DefaultError,
>(
  args?: Prisma.SelectSubset<TArgs, Prisma.listing_boostsCountArgs>,
  options?: Omit<UseQueryOptions<TQueryFnData, TError, TData>, "queryKey"> & ExtraQueryOptions
) {
  const { endpoint, fetch } = getHooksContext();
  return useModelQuery<TQueryFnData, TData, TError>(
    "listing_boosts",
    `${endpoint}/listing_boosts/count`,
    args,
    options,
    fetch
  );
}

export function useSuspenseCountlisting_boosts<
  TArgs extends Prisma.listing_boostsCountArgs,
  TQueryFnData = TArgs extends { select: any }
    ? TArgs["select"] extends true
      ? number
      : Prisma.GetScalarType<TArgs["select"], Prisma.Listing_boostsCountAggregateOutputType>
    : number,
  TData = TQueryFnData,
  TError = DefaultError,
>(
  args?: Prisma.SelectSubset<TArgs, Prisma.listing_boostsCountArgs>,
  options?: Omit<UseSuspenseQueryOptions<TQueryFnData, TError, TData>, "queryKey"> &
    ExtraQueryOptions
) {
  const { endpoint, fetch } = getHooksContext();
  return useSuspenseModelQuery<TQueryFnData, TData, TError>(
    "listing_boosts",
    `${endpoint}/listing_boosts/count`,
    args,
    options,
    fetch
  );
}
import type { BoostStatus } from "@prisma/client";

export function useChecklisting_boosts<TError = DefaultError>(
  args: {
    operation: PolicyCrudKind;
    where?: {
      id?: string;
      listing_id?: string;
      user_id?: string;
      plan?: string;
      status?: BoostStatus;
    };
  },
  options?: Omit<UseQueryOptions<boolean, TError, boolean>, "queryKey"> & ExtraQueryOptions
) {
  const { endpoint, fetch } = getHooksContext();
  return useModelQuery<boolean, boolean, TError>(
    "listing_boosts",
    `${endpoint}/listing_boosts/check`,
    args,
    options,
    fetch
  );
}
