/******************************************************************************
 * This file was generated by ZenStack CLI.
 ******************************************************************************/

/* eslint-disable */

import type { Prisma, listings_images } from "@prisma/client";
import type { UseMutationOptions, UseQueryOptions, UseInfiniteQueryOptions, InfiniteData } from '@tanstack/react-query';
import { getHooksContext } from '@zenstackhq/tanstack-query/runtime-v5/react';
import { useModelQuery, useInfiniteModelQuery, useModelMutation } from '@zenstackhq/tanstack-query/runtime-v5/react';
import type { PickEnumerable, CheckSelect, QueryError, ExtraQueryOptions, ExtraMutationOptions } from '@zenstackhq/tanstack-query/runtime-v5';
import type { PolicyCrudKind } from '@zenstackhq/runtime'
import metadata from './__model_meta';
type DefaultError = QueryError;
import { useSuspenseModelQuery, useSuspenseInfiniteModelQuery } from '@zenstackhq/tanstack-query/runtime-v5/react';
import type { UseSuspenseQueryOptions, UseSuspenseInfiniteQueryOptions } from '@tanstack/react-query';

export function useCreatelistings_images(options?: Omit<(UseMutationOptions<(listings_images | undefined), DefaultError, Prisma.listings_imagesCreateArgs> & ExtraMutationOptions), 'mutationFn'>) {
    const { endpoint, fetch } = getHooksContext();
    const _mutation =
        useModelMutation<Prisma.listings_imagesCreateArgs, DefaultError, listings_images, true>('listings_images', 'POST', `${endpoint}/listings_images/create`, metadata, options, fetch, true)
        ;
    const mutation = {
        ..._mutation,
        mutateAsync: async <T extends Prisma.listings_imagesCreateArgs>(
            args: Prisma.SelectSubset<T, Prisma.listings_imagesCreateArgs>,
            options?: Omit<(UseMutationOptions<(CheckSelect<T, listings_images, Prisma.listings_imagesGetPayload<T>> | undefined), DefaultError, Prisma.SelectSubset<T, Prisma.listings_imagesCreateArgs>> & ExtraMutationOptions), 'mutationFn'>
        ) => {
            return (await _mutation.mutateAsync(
                args,
                options as any
            )) as (CheckSelect<T, listings_images, Prisma.listings_imagesGetPayload<T>> | undefined);
        },
    };
    return mutation;
}

export function useCreateManylistings_images(options?: Omit<(UseMutationOptions<Prisma.BatchPayload, DefaultError, Prisma.listings_imagesCreateManyArgs> & ExtraMutationOptions), 'mutationFn'>) {
    const { endpoint, fetch } = getHooksContext();
    const _mutation =
        useModelMutation<Prisma.listings_imagesCreateManyArgs, DefaultError, Prisma.BatchPayload, false>('listings_images', 'POST', `${endpoint}/listings_images/createMany`, metadata, options, fetch, false)
        ;
    const mutation = {
        ..._mutation,
        mutateAsync: async <T extends Prisma.listings_imagesCreateManyArgs>(
            args: Prisma.SelectSubset<T, Prisma.listings_imagesCreateManyArgs>,
            options?: Omit<(UseMutationOptions<Prisma.BatchPayload, DefaultError, Prisma.SelectSubset<T, Prisma.listings_imagesCreateManyArgs>> & ExtraMutationOptions), 'mutationFn'>
        ) => {
            return (await _mutation.mutateAsync(
                args,
                options as any
            )) as Prisma.BatchPayload;
        },
    };
    return mutation;
}

export function useFindManylistings_images<TArgs extends Prisma.listings_imagesFindManyArgs, TQueryFnData = Array<Prisma.listings_imagesGetPayload<TArgs> & { $optimistic?: boolean }>, TData = TQueryFnData, TError = DefaultError>(args?: Prisma.SelectSubset<TArgs, Prisma.listings_imagesFindManyArgs>, options?: (Omit<UseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useModelQuery<TQueryFnData, TData, TError>('listings_images', `${endpoint}/listings_images/findMany`, args, options, fetch);
}

export function useInfiniteFindManylistings_images<TArgs extends Prisma.listings_imagesFindManyArgs, TQueryFnData = Array<Prisma.listings_imagesGetPayload<TArgs>>, TData = TQueryFnData, TError = DefaultError>(args?: Prisma.SelectSubset<TArgs, Prisma.listings_imagesFindManyArgs>, options?: Omit<UseInfiniteQueryOptions<TQueryFnData, TError, InfiniteData<TData>>, 'queryKey' | 'initialPageParam'>) {
    options = options ?? { getNextPageParam: () => null };
    const { endpoint, fetch } = getHooksContext();
    return useInfiniteModelQuery<TQueryFnData, TData, TError>('listings_images', `${endpoint}/listings_images/findMany`, args, options, fetch);
}

export function useSuspenseFindManylistings_images<TArgs extends Prisma.listings_imagesFindManyArgs, TQueryFnData = Array<Prisma.listings_imagesGetPayload<TArgs> & { $optimistic?: boolean }>, TData = TQueryFnData, TError = DefaultError>(args?: Prisma.SelectSubset<TArgs, Prisma.listings_imagesFindManyArgs>, options?: (Omit<UseSuspenseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useSuspenseModelQuery<TQueryFnData, TData, TError>('listings_images', `${endpoint}/listings_images/findMany`, args, options, fetch);
}

export function useSuspenseInfiniteFindManylistings_images<TArgs extends Prisma.listings_imagesFindManyArgs, TQueryFnData = Array<Prisma.listings_imagesGetPayload<TArgs>>, TData = TQueryFnData, TError = DefaultError>(args?: Prisma.SelectSubset<TArgs, Prisma.listings_imagesFindManyArgs>, options?: Omit<UseSuspenseInfiniteQueryOptions<TQueryFnData, TError, InfiniteData<TData>>, 'queryKey' | 'initialPageParam'>) {
    options = options ?? { getNextPageParam: () => null };
    const { endpoint, fetch } = getHooksContext();
    return useSuspenseInfiniteModelQuery<TQueryFnData, TData, TError>('listings_images', `${endpoint}/listings_images/findMany`, args, options, fetch);
}

export function useFindUniquelistings_images<TArgs extends Prisma.listings_imagesFindUniqueArgs, TQueryFnData = Prisma.listings_imagesGetPayload<TArgs> & { $optimistic?: boolean }, TData = TQueryFnData, TError = DefaultError>(args: Prisma.SelectSubset<TArgs, Prisma.listings_imagesFindUniqueArgs>, options?: (Omit<UseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useModelQuery<TQueryFnData, TData, TError>('listings_images', `${endpoint}/listings_images/findUnique`, args, options, fetch);
}

export function useSuspenseFindUniquelistings_images<TArgs extends Prisma.listings_imagesFindUniqueArgs, TQueryFnData = Prisma.listings_imagesGetPayload<TArgs> & { $optimistic?: boolean }, TData = TQueryFnData, TError = DefaultError>(args: Prisma.SelectSubset<TArgs, Prisma.listings_imagesFindUniqueArgs>, options?: (Omit<UseSuspenseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useSuspenseModelQuery<TQueryFnData, TData, TError>('listings_images', `${endpoint}/listings_images/findUnique`, args, options, fetch);
}

export function useFindFirstlistings_images<TArgs extends Prisma.listings_imagesFindFirstArgs, TQueryFnData = Prisma.listings_imagesGetPayload<TArgs> & { $optimistic?: boolean }, TData = TQueryFnData, TError = DefaultError>(args?: Prisma.SelectSubset<TArgs, Prisma.listings_imagesFindFirstArgs>, options?: (Omit<UseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useModelQuery<TQueryFnData, TData, TError>('listings_images', `${endpoint}/listings_images/findFirst`, args, options, fetch);
}

export function useSuspenseFindFirstlistings_images<TArgs extends Prisma.listings_imagesFindFirstArgs, TQueryFnData = Prisma.listings_imagesGetPayload<TArgs> & { $optimistic?: boolean }, TData = TQueryFnData, TError = DefaultError>(args?: Prisma.SelectSubset<TArgs, Prisma.listings_imagesFindFirstArgs>, options?: (Omit<UseSuspenseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useSuspenseModelQuery<TQueryFnData, TData, TError>('listings_images', `${endpoint}/listings_images/findFirst`, args, options, fetch);
}

export function useUpdatelistings_images(options?: Omit<(UseMutationOptions<(listings_images | undefined), DefaultError, Prisma.listings_imagesUpdateArgs> & ExtraMutationOptions), 'mutationFn'>) {
    const { endpoint, fetch } = getHooksContext();
    const _mutation =
        useModelMutation<Prisma.listings_imagesUpdateArgs, DefaultError, listings_images, true>('listings_images', 'PUT', `${endpoint}/listings_images/update`, metadata, options, fetch, true)
        ;
    const mutation = {
        ..._mutation,
        mutateAsync: async <T extends Prisma.listings_imagesUpdateArgs>(
            args: Prisma.SelectSubset<T, Prisma.listings_imagesUpdateArgs>,
            options?: Omit<(UseMutationOptions<(CheckSelect<T, listings_images, Prisma.listings_imagesGetPayload<T>> | undefined), DefaultError, Prisma.SelectSubset<T, Prisma.listings_imagesUpdateArgs>> & ExtraMutationOptions), 'mutationFn'>
        ) => {
            return (await _mutation.mutateAsync(
                args,
                options as any
            )) as (CheckSelect<T, listings_images, Prisma.listings_imagesGetPayload<T>> | undefined);
        },
    };
    return mutation;
}

export function useUpdateManylistings_images(options?: Omit<(UseMutationOptions<Prisma.BatchPayload, DefaultError, Prisma.listings_imagesUpdateManyArgs> & ExtraMutationOptions), 'mutationFn'>) {
    const { endpoint, fetch } = getHooksContext();
    const _mutation =
        useModelMutation<Prisma.listings_imagesUpdateManyArgs, DefaultError, Prisma.BatchPayload, false>('listings_images', 'PUT', `${endpoint}/listings_images/updateMany`, metadata, options, fetch, false)
        ;
    const mutation = {
        ..._mutation,
        mutateAsync: async <T extends Prisma.listings_imagesUpdateManyArgs>(
            args: Prisma.SelectSubset<T, Prisma.listings_imagesUpdateManyArgs>,
            options?: Omit<(UseMutationOptions<Prisma.BatchPayload, DefaultError, Prisma.SelectSubset<T, Prisma.listings_imagesUpdateManyArgs>> & ExtraMutationOptions), 'mutationFn'>
        ) => {
            return (await _mutation.mutateAsync(
                args,
                options as any
            )) as Prisma.BatchPayload;
        },
    };
    return mutation;
}

export function useUpsertlistings_images(options?: Omit<(UseMutationOptions<(listings_images | undefined), DefaultError, Prisma.listings_imagesUpsertArgs> & ExtraMutationOptions), 'mutationFn'>) {
    const { endpoint, fetch } = getHooksContext();
    const _mutation =
        useModelMutation<Prisma.listings_imagesUpsertArgs, DefaultError, listings_images, true>('listings_images', 'POST', `${endpoint}/listings_images/upsert`, metadata, options, fetch, true)
        ;
    const mutation = {
        ..._mutation,
        mutateAsync: async <T extends Prisma.listings_imagesUpsertArgs>(
            args: Prisma.SelectSubset<T, Prisma.listings_imagesUpsertArgs>,
            options?: Omit<(UseMutationOptions<(CheckSelect<T, listings_images, Prisma.listings_imagesGetPayload<T>> | undefined), DefaultError, Prisma.SelectSubset<T, Prisma.listings_imagesUpsertArgs>> & ExtraMutationOptions), 'mutationFn'>
        ) => {
            return (await _mutation.mutateAsync(
                args,
                options as any
            )) as (CheckSelect<T, listings_images, Prisma.listings_imagesGetPayload<T>> | undefined);
        },
    };
    return mutation;
}

export function useDeletelistings_images(options?: Omit<(UseMutationOptions<(listings_images | undefined), DefaultError, Prisma.listings_imagesDeleteArgs> & ExtraMutationOptions), 'mutationFn'>) {
    const { endpoint, fetch } = getHooksContext();
    const _mutation =
        useModelMutation<Prisma.listings_imagesDeleteArgs, DefaultError, listings_images, true>('listings_images', 'DELETE', `${endpoint}/listings_images/delete`, metadata, options, fetch, true)
        ;
    const mutation = {
        ..._mutation,
        mutateAsync: async <T extends Prisma.listings_imagesDeleteArgs>(
            args: Prisma.SelectSubset<T, Prisma.listings_imagesDeleteArgs>,
            options?: Omit<(UseMutationOptions<(CheckSelect<T, listings_images, Prisma.listings_imagesGetPayload<T>> | undefined), DefaultError, Prisma.SelectSubset<T, Prisma.listings_imagesDeleteArgs>> & ExtraMutationOptions), 'mutationFn'>
        ) => {
            return (await _mutation.mutateAsync(
                args,
                options as any
            )) as (CheckSelect<T, listings_images, Prisma.listings_imagesGetPayload<T>> | undefined);
        },
    };
    return mutation;
}

export function useDeleteManylistings_images(options?: Omit<(UseMutationOptions<Prisma.BatchPayload, DefaultError, Prisma.listings_imagesDeleteManyArgs> & ExtraMutationOptions), 'mutationFn'>) {
    const { endpoint, fetch } = getHooksContext();
    const _mutation =
        useModelMutation<Prisma.listings_imagesDeleteManyArgs, DefaultError, Prisma.BatchPayload, false>('listings_images', 'DELETE', `${endpoint}/listings_images/deleteMany`, metadata, options, fetch, false)
        ;
    const mutation = {
        ..._mutation,
        mutateAsync: async <T extends Prisma.listings_imagesDeleteManyArgs>(
            args: Prisma.SelectSubset<T, Prisma.listings_imagesDeleteManyArgs>,
            options?: Omit<(UseMutationOptions<Prisma.BatchPayload, DefaultError, Prisma.SelectSubset<T, Prisma.listings_imagesDeleteManyArgs>> & ExtraMutationOptions), 'mutationFn'>
        ) => {
            return (await _mutation.mutateAsync(
                args,
                options as any
            )) as Prisma.BatchPayload;
        },
    };
    return mutation;
}

export function useAggregateListings_images<TArgs extends Prisma.Listings_imagesAggregateArgs, TQueryFnData = Prisma.GetListings_imagesAggregateType<TArgs>, TData = TQueryFnData, TError = DefaultError>(args: Prisma.SelectSubset<TArgs, Prisma.Listings_imagesAggregateArgs>, options?: (Omit<UseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useModelQuery<TQueryFnData, TData, TError>('Listings_images', `${endpoint}/listings_images/aggregate`, args, options, fetch);
}

export function useSuspenseAggregateListings_images<TArgs extends Prisma.Listings_imagesAggregateArgs, TQueryFnData = Prisma.GetListings_imagesAggregateType<TArgs>, TData = TQueryFnData, TError = DefaultError>(args: Prisma.SelectSubset<TArgs, Prisma.Listings_imagesAggregateArgs>, options?: (Omit<UseSuspenseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useSuspenseModelQuery<TQueryFnData, TData, TError>('Listings_images', `${endpoint}/listings_images/aggregate`, args, options, fetch);
}

export function useGroupBylistings_images<TArgs extends Prisma.listings_imagesGroupByArgs, HasSelectOrTake extends Prisma.Or<Prisma.Extends<'skip', Prisma.Keys<TArgs>>, Prisma.Extends<'take', Prisma.Keys<TArgs>>>, OrderByArg extends Prisma.True extends HasSelectOrTake ? { orderBy: Prisma.listings_imagesGroupByArgs['orderBy'] } : { orderBy?: Prisma.listings_imagesGroupByArgs['orderBy'] }, OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<TArgs['orderBy']>>>, ByFields extends Prisma.MaybeTupleToUnion<TArgs['by']>, ByValid extends Prisma.Has<ByFields, OrderFields>, HavingFields extends Prisma.GetHavingFields<TArgs['having']>, HavingValid extends Prisma.Has<ByFields, HavingFields>, ByEmpty extends TArgs['by'] extends never[] ? Prisma.True : Prisma.False, InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
        ? never
        : P extends string
        ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
        : [
            Error,
            'Field ',
            P,
            ` in "having" needs to be provided in "by"`,
        ]
    }[HavingFields]
    : 'take' extends Prisma.Keys<TArgs>
    ? 'orderBy' extends Prisma.Keys<TArgs>
    ? ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
        ? never
        : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
    }[OrderFields]
    : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<TArgs>
    ? 'orderBy' extends Prisma.Keys<TArgs>
    ? ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
        ? never
        : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
    }[OrderFields]
    : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
        ? never
        : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
    }[OrderFields], TQueryFnData = {} extends InputErrors ?
    Array<PickEnumerable<Prisma.Listings_imagesGroupByOutputType, TArgs['by']> &
    {
        [P in ((keyof TArgs) & (keyof Prisma.Listings_imagesGroupByOutputType))]: P extends '_count'
        ? TArgs[P] extends boolean
        ? number
        : Prisma.GetScalarType<TArgs[P], Prisma.Listings_imagesGroupByOutputType[P]>
        : Prisma.GetScalarType<TArgs[P], Prisma.Listings_imagesGroupByOutputType[P]>
    }
    > : InputErrors, TData = TQueryFnData, TError = DefaultError>(args: Prisma.SelectSubset<TArgs, Prisma.SubsetIntersection<TArgs, Prisma.listings_imagesGroupByArgs, OrderByArg> & InputErrors>, options?: (Omit<UseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useModelQuery<TQueryFnData, TData, TError>('listings_images', `${endpoint}/listings_images/groupBy`, args, options, fetch);
}

export function useSuspenseGroupBylistings_images<TArgs extends Prisma.listings_imagesGroupByArgs, HasSelectOrTake extends Prisma.Or<Prisma.Extends<'skip', Prisma.Keys<TArgs>>, Prisma.Extends<'take', Prisma.Keys<TArgs>>>, OrderByArg extends Prisma.True extends HasSelectOrTake ? { orderBy: Prisma.listings_imagesGroupByArgs['orderBy'] } : { orderBy?: Prisma.listings_imagesGroupByArgs['orderBy'] }, OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<TArgs['orderBy']>>>, ByFields extends Prisma.MaybeTupleToUnion<TArgs['by']>, ByValid extends Prisma.Has<ByFields, OrderFields>, HavingFields extends Prisma.GetHavingFields<TArgs['having']>, HavingValid extends Prisma.Has<ByFields, HavingFields>, ByEmpty extends TArgs['by'] extends never[] ? Prisma.True : Prisma.False, InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
        ? never
        : P extends string
        ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
        : [
            Error,
            'Field ',
            P,
            ` in "having" needs to be provided in "by"`,
        ]
    }[HavingFields]
    : 'take' extends Prisma.Keys<TArgs>
    ? 'orderBy' extends Prisma.Keys<TArgs>
    ? ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
        ? never
        : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
    }[OrderFields]
    : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<TArgs>
    ? 'orderBy' extends Prisma.Keys<TArgs>
    ? ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
        ? never
        : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
    }[OrderFields]
    : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
        ? never
        : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
    }[OrderFields], TQueryFnData = {} extends InputErrors ?
    Array<PickEnumerable<Prisma.Listings_imagesGroupByOutputType, TArgs['by']> &
    {
        [P in ((keyof TArgs) & (keyof Prisma.Listings_imagesGroupByOutputType))]: P extends '_count'
        ? TArgs[P] extends boolean
        ? number
        : Prisma.GetScalarType<TArgs[P], Prisma.Listings_imagesGroupByOutputType[P]>
        : Prisma.GetScalarType<TArgs[P], Prisma.Listings_imagesGroupByOutputType[P]>
    }
    > : InputErrors, TData = TQueryFnData, TError = DefaultError>(args: Prisma.SelectSubset<TArgs, Prisma.SubsetIntersection<TArgs, Prisma.listings_imagesGroupByArgs, OrderByArg> & InputErrors>, options?: (Omit<UseSuspenseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useSuspenseModelQuery<TQueryFnData, TData, TError>('listings_images', `${endpoint}/listings_images/groupBy`, args, options, fetch);
}

export function useCountlistings_images<TArgs extends Prisma.listings_imagesCountArgs, TQueryFnData = TArgs extends { select: any; } ? TArgs['select'] extends true ? number : Prisma.GetScalarType<TArgs['select'], Prisma.Listings_imagesCountAggregateOutputType> : number, TData = TQueryFnData, TError = DefaultError>(args?: Prisma.SelectSubset<TArgs, Prisma.listings_imagesCountArgs>, options?: (Omit<UseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useModelQuery<TQueryFnData, TData, TError>('listings_images', `${endpoint}/listings_images/count`, args, options, fetch);
}

export function useSuspenseCountlistings_images<TArgs extends Prisma.listings_imagesCountArgs, TQueryFnData = TArgs extends { select: any; } ? TArgs['select'] extends true ? number : Prisma.GetScalarType<TArgs['select'], Prisma.Listings_imagesCountAggregateOutputType> : number, TData = TQueryFnData, TError = DefaultError>(args?: Prisma.SelectSubset<TArgs, Prisma.listings_imagesCountArgs>, options?: (Omit<UseSuspenseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useSuspenseModelQuery<TQueryFnData, TData, TError>('listings_images', `${endpoint}/listings_images/count`, args, options, fetch);
}

export function useChecklistings_images<TError = DefaultError>(args: { operation: PolicyCrudKind; where?: { id?: string; listing_id?: string; url?: string; alt?: string; sort_order?: number; is_cover?: boolean }; }, options?: (Omit<UseQueryOptions<boolean, TError, boolean>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useModelQuery<boolean, boolean, TError>('listings_images', `${endpoint}/listings_images/check`, args, options, fetch);
}
