/******************************************************************************
 * This file was generated by ZenStack CLI.
 ******************************************************************************/

/* eslint-disable */

import type { Prisma, profiles_work_experiences } from "@prisma/client";
import type { UseMutationOptions, UseQueryOptions, UseInfiniteQueryOptions, InfiniteData } from '@tanstack/react-query';
import { getHooksContext } from '@zenstackhq/tanstack-query/runtime-v5/react';
import { useModelQuery, useInfiniteModelQuery, useModelMutation } from '@zenstackhq/tanstack-query/runtime-v5/react';
import type { PickEnumerable, CheckSelect, QueryError, ExtraQueryOptions, ExtraMutationOptions } from '@zenstackhq/tanstack-query/runtime-v5';
import type { PolicyCrudKind } from '@zenstackhq/runtime'
import metadata from './__model_meta';
type DefaultError = QueryError;
import { useSuspenseModelQuery, useSuspenseInfiniteModelQuery } from '@zenstackhq/tanstack-query/runtime-v5/react';
import type { UseSuspenseQueryOptions, UseSuspenseInfiniteQueryOptions } from '@tanstack/react-query';

export function useCreateprofiles_work_experiences(options?: Omit<(UseMutationOptions<(profiles_work_experiences | undefined), DefaultError, Prisma.profiles_work_experiencesCreateArgs> & ExtraMutationOptions), 'mutationFn'>) {
    const { endpoint, fetch } = getHooksContext();
    const _mutation =
        useModelMutation<Prisma.profiles_work_experiencesCreateArgs, DefaultError, profiles_work_experiences, true>('profiles_work_experiences', 'POST', `${endpoint}/profiles_work_experiences/create`, metadata, options, fetch, true)
        ;
    const mutation = {
        ..._mutation,
        mutateAsync: async <T extends Prisma.profiles_work_experiencesCreateArgs>(
            args: Prisma.SelectSubset<T, Prisma.profiles_work_experiencesCreateArgs>,
            options?: Omit<(UseMutationOptions<(CheckSelect<T, profiles_work_experiences, Prisma.profiles_work_experiencesGetPayload<T>> | undefined), DefaultError, Prisma.SelectSubset<T, Prisma.profiles_work_experiencesCreateArgs>> & ExtraMutationOptions), 'mutationFn'>
        ) => {
            return (await _mutation.mutateAsync(
                args,
                options as any
            )) as (CheckSelect<T, profiles_work_experiences, Prisma.profiles_work_experiencesGetPayload<T>> | undefined);
        },
    };
    return mutation;
}

export function useCreateManyprofiles_work_experiences(options?: Omit<(UseMutationOptions<Prisma.BatchPayload, DefaultError, Prisma.profiles_work_experiencesCreateManyArgs> & ExtraMutationOptions), 'mutationFn'>) {
    const { endpoint, fetch } = getHooksContext();
    const _mutation =
        useModelMutation<Prisma.profiles_work_experiencesCreateManyArgs, DefaultError, Prisma.BatchPayload, false>('profiles_work_experiences', 'POST', `${endpoint}/profiles_work_experiences/createMany`, metadata, options, fetch, false)
        ;
    const mutation = {
        ..._mutation,
        mutateAsync: async <T extends Prisma.profiles_work_experiencesCreateManyArgs>(
            args: Prisma.SelectSubset<T, Prisma.profiles_work_experiencesCreateManyArgs>,
            options?: Omit<(UseMutationOptions<Prisma.BatchPayload, DefaultError, Prisma.SelectSubset<T, Prisma.profiles_work_experiencesCreateManyArgs>> & ExtraMutationOptions), 'mutationFn'>
        ) => {
            return (await _mutation.mutateAsync(
                args,
                options as any
            )) as Prisma.BatchPayload;
        },
    };
    return mutation;
}

export function useFindManyprofiles_work_experiences<TArgs extends Prisma.profiles_work_experiencesFindManyArgs, TQueryFnData = Array<Prisma.profiles_work_experiencesGetPayload<TArgs> & { $optimistic?: boolean }>, TData = TQueryFnData, TError = DefaultError>(args?: Prisma.SelectSubset<TArgs, Prisma.profiles_work_experiencesFindManyArgs>, options?: (Omit<UseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useModelQuery<TQueryFnData, TData, TError>('profiles_work_experiences', `${endpoint}/profiles_work_experiences/findMany`, args, options, fetch);
}

export function useInfiniteFindManyprofiles_work_experiences<TArgs extends Prisma.profiles_work_experiencesFindManyArgs, TQueryFnData = Array<Prisma.profiles_work_experiencesGetPayload<TArgs>>, TData = TQueryFnData, TError = DefaultError>(args?: Prisma.SelectSubset<TArgs, Prisma.profiles_work_experiencesFindManyArgs>, options?: Omit<UseInfiniteQueryOptions<TQueryFnData, TError, InfiniteData<TData>>, 'queryKey' | 'initialPageParam'>) {
    options = options ?? { getNextPageParam: () => null };
    const { endpoint, fetch } = getHooksContext();
    return useInfiniteModelQuery<TQueryFnData, TData, TError>('profiles_work_experiences', `${endpoint}/profiles_work_experiences/findMany`, args, options, fetch);
}

export function useSuspenseFindManyprofiles_work_experiences<TArgs extends Prisma.profiles_work_experiencesFindManyArgs, TQueryFnData = Array<Prisma.profiles_work_experiencesGetPayload<TArgs> & { $optimistic?: boolean }>, TData = TQueryFnData, TError = DefaultError>(args?: Prisma.SelectSubset<TArgs, Prisma.profiles_work_experiencesFindManyArgs>, options?: (Omit<UseSuspenseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useSuspenseModelQuery<TQueryFnData, TData, TError>('profiles_work_experiences', `${endpoint}/profiles_work_experiences/findMany`, args, options, fetch);
}

export function useSuspenseInfiniteFindManyprofiles_work_experiences<TArgs extends Prisma.profiles_work_experiencesFindManyArgs, TQueryFnData = Array<Prisma.profiles_work_experiencesGetPayload<TArgs>>, TData = TQueryFnData, TError = DefaultError>(args?: Prisma.SelectSubset<TArgs, Prisma.profiles_work_experiencesFindManyArgs>, options?: Omit<UseSuspenseInfiniteQueryOptions<TQueryFnData, TError, InfiniteData<TData>>, 'queryKey' | 'initialPageParam'>) {
    options = options ?? { getNextPageParam: () => null };
    const { endpoint, fetch } = getHooksContext();
    return useSuspenseInfiniteModelQuery<TQueryFnData, TData, TError>('profiles_work_experiences', `${endpoint}/profiles_work_experiences/findMany`, args, options, fetch);
}

export function useFindUniqueprofiles_work_experiences<TArgs extends Prisma.profiles_work_experiencesFindUniqueArgs, TQueryFnData = Prisma.profiles_work_experiencesGetPayload<TArgs> & { $optimistic?: boolean }, TData = TQueryFnData, TError = DefaultError>(args: Prisma.SelectSubset<TArgs, Prisma.profiles_work_experiencesFindUniqueArgs>, options?: (Omit<UseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useModelQuery<TQueryFnData, TData, TError>('profiles_work_experiences', `${endpoint}/profiles_work_experiences/findUnique`, args, options, fetch);
}

export function useSuspenseFindUniqueprofiles_work_experiences<TArgs extends Prisma.profiles_work_experiencesFindUniqueArgs, TQueryFnData = Prisma.profiles_work_experiencesGetPayload<TArgs> & { $optimistic?: boolean }, TData = TQueryFnData, TError = DefaultError>(args: Prisma.SelectSubset<TArgs, Prisma.profiles_work_experiencesFindUniqueArgs>, options?: (Omit<UseSuspenseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useSuspenseModelQuery<TQueryFnData, TData, TError>('profiles_work_experiences', `${endpoint}/profiles_work_experiences/findUnique`, args, options, fetch);
}

export function useFindFirstprofiles_work_experiences<TArgs extends Prisma.profiles_work_experiencesFindFirstArgs, TQueryFnData = Prisma.profiles_work_experiencesGetPayload<TArgs> & { $optimistic?: boolean }, TData = TQueryFnData, TError = DefaultError>(args?: Prisma.SelectSubset<TArgs, Prisma.profiles_work_experiencesFindFirstArgs>, options?: (Omit<UseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useModelQuery<TQueryFnData, TData, TError>('profiles_work_experiences', `${endpoint}/profiles_work_experiences/findFirst`, args, options, fetch);
}

export function useSuspenseFindFirstprofiles_work_experiences<TArgs extends Prisma.profiles_work_experiencesFindFirstArgs, TQueryFnData = Prisma.profiles_work_experiencesGetPayload<TArgs> & { $optimistic?: boolean }, TData = TQueryFnData, TError = DefaultError>(args?: Prisma.SelectSubset<TArgs, Prisma.profiles_work_experiencesFindFirstArgs>, options?: (Omit<UseSuspenseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useSuspenseModelQuery<TQueryFnData, TData, TError>('profiles_work_experiences', `${endpoint}/profiles_work_experiences/findFirst`, args, options, fetch);
}

export function useUpdateprofiles_work_experiences(options?: Omit<(UseMutationOptions<(profiles_work_experiences | undefined), DefaultError, Prisma.profiles_work_experiencesUpdateArgs> & ExtraMutationOptions), 'mutationFn'>) {
    const { endpoint, fetch } = getHooksContext();
    const _mutation =
        useModelMutation<Prisma.profiles_work_experiencesUpdateArgs, DefaultError, profiles_work_experiences, true>('profiles_work_experiences', 'PUT', `${endpoint}/profiles_work_experiences/update`, metadata, options, fetch, true)
        ;
    const mutation = {
        ..._mutation,
        mutateAsync: async <T extends Prisma.profiles_work_experiencesUpdateArgs>(
            args: Prisma.SelectSubset<T, Prisma.profiles_work_experiencesUpdateArgs>,
            options?: Omit<(UseMutationOptions<(CheckSelect<T, profiles_work_experiences, Prisma.profiles_work_experiencesGetPayload<T>> | undefined), DefaultError, Prisma.SelectSubset<T, Prisma.profiles_work_experiencesUpdateArgs>> & ExtraMutationOptions), 'mutationFn'>
        ) => {
            return (await _mutation.mutateAsync(
                args,
                options as any
            )) as (CheckSelect<T, profiles_work_experiences, Prisma.profiles_work_experiencesGetPayload<T>> | undefined);
        },
    };
    return mutation;
}

export function useUpdateManyprofiles_work_experiences(options?: Omit<(UseMutationOptions<Prisma.BatchPayload, DefaultError, Prisma.profiles_work_experiencesUpdateManyArgs> & ExtraMutationOptions), 'mutationFn'>) {
    const { endpoint, fetch } = getHooksContext();
    const _mutation =
        useModelMutation<Prisma.profiles_work_experiencesUpdateManyArgs, DefaultError, Prisma.BatchPayload, false>('profiles_work_experiences', 'PUT', `${endpoint}/profiles_work_experiences/updateMany`, metadata, options, fetch, false)
        ;
    const mutation = {
        ..._mutation,
        mutateAsync: async <T extends Prisma.profiles_work_experiencesUpdateManyArgs>(
            args: Prisma.SelectSubset<T, Prisma.profiles_work_experiencesUpdateManyArgs>,
            options?: Omit<(UseMutationOptions<Prisma.BatchPayload, DefaultError, Prisma.SelectSubset<T, Prisma.profiles_work_experiencesUpdateManyArgs>> & ExtraMutationOptions), 'mutationFn'>
        ) => {
            return (await _mutation.mutateAsync(
                args,
                options as any
            )) as Prisma.BatchPayload;
        },
    };
    return mutation;
}

export function useUpsertprofiles_work_experiences(options?: Omit<(UseMutationOptions<(profiles_work_experiences | undefined), DefaultError, Prisma.profiles_work_experiencesUpsertArgs> & ExtraMutationOptions), 'mutationFn'>) {
    const { endpoint, fetch } = getHooksContext();
    const _mutation =
        useModelMutation<Prisma.profiles_work_experiencesUpsertArgs, DefaultError, profiles_work_experiences, true>('profiles_work_experiences', 'POST', `${endpoint}/profiles_work_experiences/upsert`, metadata, options, fetch, true)
        ;
    const mutation = {
        ..._mutation,
        mutateAsync: async <T extends Prisma.profiles_work_experiencesUpsertArgs>(
            args: Prisma.SelectSubset<T, Prisma.profiles_work_experiencesUpsertArgs>,
            options?: Omit<(UseMutationOptions<(CheckSelect<T, profiles_work_experiences, Prisma.profiles_work_experiencesGetPayload<T>> | undefined), DefaultError, Prisma.SelectSubset<T, Prisma.profiles_work_experiencesUpsertArgs>> & ExtraMutationOptions), 'mutationFn'>
        ) => {
            return (await _mutation.mutateAsync(
                args,
                options as any
            )) as (CheckSelect<T, profiles_work_experiences, Prisma.profiles_work_experiencesGetPayload<T>> | undefined);
        },
    };
    return mutation;
}

export function useDeleteprofiles_work_experiences(options?: Omit<(UseMutationOptions<(profiles_work_experiences | undefined), DefaultError, Prisma.profiles_work_experiencesDeleteArgs> & ExtraMutationOptions), 'mutationFn'>) {
    const { endpoint, fetch } = getHooksContext();
    const _mutation =
        useModelMutation<Prisma.profiles_work_experiencesDeleteArgs, DefaultError, profiles_work_experiences, true>('profiles_work_experiences', 'DELETE', `${endpoint}/profiles_work_experiences/delete`, metadata, options, fetch, true)
        ;
    const mutation = {
        ..._mutation,
        mutateAsync: async <T extends Prisma.profiles_work_experiencesDeleteArgs>(
            args: Prisma.SelectSubset<T, Prisma.profiles_work_experiencesDeleteArgs>,
            options?: Omit<(UseMutationOptions<(CheckSelect<T, profiles_work_experiences, Prisma.profiles_work_experiencesGetPayload<T>> | undefined), DefaultError, Prisma.SelectSubset<T, Prisma.profiles_work_experiencesDeleteArgs>> & ExtraMutationOptions), 'mutationFn'>
        ) => {
            return (await _mutation.mutateAsync(
                args,
                options as any
            )) as (CheckSelect<T, profiles_work_experiences, Prisma.profiles_work_experiencesGetPayload<T>> | undefined);
        },
    };
    return mutation;
}

export function useDeleteManyprofiles_work_experiences(options?: Omit<(UseMutationOptions<Prisma.BatchPayload, DefaultError, Prisma.profiles_work_experiencesDeleteManyArgs> & ExtraMutationOptions), 'mutationFn'>) {
    const { endpoint, fetch } = getHooksContext();
    const _mutation =
        useModelMutation<Prisma.profiles_work_experiencesDeleteManyArgs, DefaultError, Prisma.BatchPayload, false>('profiles_work_experiences', 'DELETE', `${endpoint}/profiles_work_experiences/deleteMany`, metadata, options, fetch, false)
        ;
    const mutation = {
        ..._mutation,
        mutateAsync: async <T extends Prisma.profiles_work_experiencesDeleteManyArgs>(
            args: Prisma.SelectSubset<T, Prisma.profiles_work_experiencesDeleteManyArgs>,
            options?: Omit<(UseMutationOptions<Prisma.BatchPayload, DefaultError, Prisma.SelectSubset<T, Prisma.profiles_work_experiencesDeleteManyArgs>> & ExtraMutationOptions), 'mutationFn'>
        ) => {
            return (await _mutation.mutateAsync(
                args,
                options as any
            )) as Prisma.BatchPayload;
        },
    };
    return mutation;
}

export function useAggregateProfiles_work_experiences<TArgs extends Prisma.Profiles_work_experiencesAggregateArgs, TQueryFnData = Prisma.GetProfiles_work_experiencesAggregateType<TArgs>, TData = TQueryFnData, TError = DefaultError>(args: Prisma.SelectSubset<TArgs, Prisma.Profiles_work_experiencesAggregateArgs>, options?: (Omit<UseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useModelQuery<TQueryFnData, TData, TError>('Profiles_work_experiences', `${endpoint}/profiles_work_experiences/aggregate`, args, options, fetch);
}

export function useSuspenseAggregateProfiles_work_experiences<TArgs extends Prisma.Profiles_work_experiencesAggregateArgs, TQueryFnData = Prisma.GetProfiles_work_experiencesAggregateType<TArgs>, TData = TQueryFnData, TError = DefaultError>(args: Prisma.SelectSubset<TArgs, Prisma.Profiles_work_experiencesAggregateArgs>, options?: (Omit<UseSuspenseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useSuspenseModelQuery<TQueryFnData, TData, TError>('Profiles_work_experiences', `${endpoint}/profiles_work_experiences/aggregate`, args, options, fetch);
}

export function useGroupByprofiles_work_experiences<TArgs extends Prisma.profiles_work_experiencesGroupByArgs, HasSelectOrTake extends Prisma.Or<Prisma.Extends<'skip', Prisma.Keys<TArgs>>, Prisma.Extends<'take', Prisma.Keys<TArgs>>>, OrderByArg extends Prisma.True extends HasSelectOrTake ? { orderBy: Prisma.profiles_work_experiencesGroupByArgs['orderBy'] } : { orderBy?: Prisma.profiles_work_experiencesGroupByArgs['orderBy'] }, OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<TArgs['orderBy']>>>, ByFields extends Prisma.MaybeTupleToUnion<TArgs['by']>, ByValid extends Prisma.Has<ByFields, OrderFields>, HavingFields extends Prisma.GetHavingFields<TArgs['having']>, HavingValid extends Prisma.Has<ByFields, HavingFields>, ByEmpty extends TArgs['by'] extends never[] ? Prisma.True : Prisma.False, InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
        ? never
        : P extends string
        ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
        : [
            Error,
            'Field ',
            P,
            ` in "having" needs to be provided in "by"`,
        ]
    }[HavingFields]
    : 'take' extends Prisma.Keys<TArgs>
    ? 'orderBy' extends Prisma.Keys<TArgs>
    ? ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
        ? never
        : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
    }[OrderFields]
    : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<TArgs>
    ? 'orderBy' extends Prisma.Keys<TArgs>
    ? ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
        ? never
        : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
    }[OrderFields]
    : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
        ? never
        : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
    }[OrderFields], TQueryFnData = {} extends InputErrors ?
    Array<PickEnumerable<Prisma.Profiles_work_experiencesGroupByOutputType, TArgs['by']> &
    {
        [P in ((keyof TArgs) & (keyof Prisma.Profiles_work_experiencesGroupByOutputType))]: P extends '_count'
        ? TArgs[P] extends boolean
        ? number
        : Prisma.GetScalarType<TArgs[P], Prisma.Profiles_work_experiencesGroupByOutputType[P]>
        : Prisma.GetScalarType<TArgs[P], Prisma.Profiles_work_experiencesGroupByOutputType[P]>
    }
    > : InputErrors, TData = TQueryFnData, TError = DefaultError>(args: Prisma.SelectSubset<TArgs, Prisma.SubsetIntersection<TArgs, Prisma.profiles_work_experiencesGroupByArgs, OrderByArg> & InputErrors>, options?: (Omit<UseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useModelQuery<TQueryFnData, TData, TError>('profiles_work_experiences', `${endpoint}/profiles_work_experiences/groupBy`, args, options, fetch);
}

export function useSuspenseGroupByprofiles_work_experiences<TArgs extends Prisma.profiles_work_experiencesGroupByArgs, HasSelectOrTake extends Prisma.Or<Prisma.Extends<'skip', Prisma.Keys<TArgs>>, Prisma.Extends<'take', Prisma.Keys<TArgs>>>, OrderByArg extends Prisma.True extends HasSelectOrTake ? { orderBy: Prisma.profiles_work_experiencesGroupByArgs['orderBy'] } : { orderBy?: Prisma.profiles_work_experiencesGroupByArgs['orderBy'] }, OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<TArgs['orderBy']>>>, ByFields extends Prisma.MaybeTupleToUnion<TArgs['by']>, ByValid extends Prisma.Has<ByFields, OrderFields>, HavingFields extends Prisma.GetHavingFields<TArgs['having']>, HavingValid extends Prisma.Has<ByFields, HavingFields>, ByEmpty extends TArgs['by'] extends never[] ? Prisma.True : Prisma.False, InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
        ? never
        : P extends string
        ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
        : [
            Error,
            'Field ',
            P,
            ` in "having" needs to be provided in "by"`,
        ]
    }[HavingFields]
    : 'take' extends Prisma.Keys<TArgs>
    ? 'orderBy' extends Prisma.Keys<TArgs>
    ? ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
        ? never
        : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
    }[OrderFields]
    : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<TArgs>
    ? 'orderBy' extends Prisma.Keys<TArgs>
    ? ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
        ? never
        : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
    }[OrderFields]
    : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
        ? never
        : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
    }[OrderFields], TQueryFnData = {} extends InputErrors ?
    Array<PickEnumerable<Prisma.Profiles_work_experiencesGroupByOutputType, TArgs['by']> &
    {
        [P in ((keyof TArgs) & (keyof Prisma.Profiles_work_experiencesGroupByOutputType))]: P extends '_count'
        ? TArgs[P] extends boolean
        ? number
        : Prisma.GetScalarType<TArgs[P], Prisma.Profiles_work_experiencesGroupByOutputType[P]>
        : Prisma.GetScalarType<TArgs[P], Prisma.Profiles_work_experiencesGroupByOutputType[P]>
    }
    > : InputErrors, TData = TQueryFnData, TError = DefaultError>(args: Prisma.SelectSubset<TArgs, Prisma.SubsetIntersection<TArgs, Prisma.profiles_work_experiencesGroupByArgs, OrderByArg> & InputErrors>, options?: (Omit<UseSuspenseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useSuspenseModelQuery<TQueryFnData, TData, TError>('profiles_work_experiences', `${endpoint}/profiles_work_experiences/groupBy`, args, options, fetch);
}

export function useCountprofiles_work_experiences<TArgs extends Prisma.profiles_work_experiencesCountArgs, TQueryFnData = TArgs extends { select: any; } ? TArgs['select'] extends true ? number : Prisma.GetScalarType<TArgs['select'], Prisma.Profiles_work_experiencesCountAggregateOutputType> : number, TData = TQueryFnData, TError = DefaultError>(args?: Prisma.SelectSubset<TArgs, Prisma.profiles_work_experiencesCountArgs>, options?: (Omit<UseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useModelQuery<TQueryFnData, TData, TError>('profiles_work_experiences', `${endpoint}/profiles_work_experiences/count`, args, options, fetch);
}

export function useSuspenseCountprofiles_work_experiences<TArgs extends Prisma.profiles_work_experiencesCountArgs, TQueryFnData = TArgs extends { select: any; } ? TArgs['select'] extends true ? number : Prisma.GetScalarType<TArgs['select'], Prisma.Profiles_work_experiencesCountAggregateOutputType> : number, TData = TQueryFnData, TError = DefaultError>(args?: Prisma.SelectSubset<TArgs, Prisma.profiles_work_experiencesCountArgs>, options?: (Omit<UseSuspenseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useSuspenseModelQuery<TQueryFnData, TData, TError>('profiles_work_experiences', `${endpoint}/profiles_work_experiences/count`, args, options, fetch);
}

export function useCheckprofiles_work_experiences<TError = DefaultError>(args: { operation: PolicyCrudKind; where?: { id?: string; user_id?: string; company?: string; position?: string; description?: string; is_current?: boolean }; }, options?: (Omit<UseQueryOptions<boolean, TError, boolean>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useModelQuery<boolean, boolean, TError>('profiles_work_experiences', `${endpoint}/profiles_work_experiences/check`, args, options, fetch);
}
