/******************************************************************************
 * This file was generated by ZenStack CLI.
 ******************************************************************************/

/* eslint-disable */

import type { Prisma, profiles_educations } from "@prisma/client";
import type { UseMutationOptions, UseQueryOptions, UseInfiniteQueryOptions, InfiniteData } from '@tanstack/react-query';
import { getHooksContext } from '@zenstackhq/tanstack-query/runtime-v5/react';
import { useModelQuery, useInfiniteModelQuery, useModelMutation } from '@zenstackhq/tanstack-query/runtime-v5/react';
import type { PickEnumerable, CheckSelect, QueryError, ExtraQueryOptions, ExtraMutationOptions } from '@zenstackhq/tanstack-query/runtime-v5';
import type { PolicyCrudKind } from '@zenstackhq/runtime'
import metadata from './__model_meta';
type DefaultError = QueryError;
import { useSuspenseModelQuery, useSuspenseInfiniteModelQuery } from '@zenstackhq/tanstack-query/runtime-v5/react';
import type { UseSuspenseQueryOptions, UseSuspenseInfiniteQueryOptions } from '@tanstack/react-query';

export function useCreateprofiles_educations(options?: Omit<(UseMutationOptions<(profiles_educations | undefined), DefaultError, Prisma.profiles_educationsCreateArgs> & ExtraMutationOptions), 'mutationFn'>) {
    const { endpoint, fetch } = getHooksContext();
    const _mutation =
        useModelMutation<Prisma.profiles_educationsCreateArgs, DefaultError, profiles_educations, true>('profiles_educations', 'POST', `${endpoint}/profiles_educations/create`, metadata, options, fetch, true)
        ;
    const mutation = {
        ..._mutation,
        mutateAsync: async <T extends Prisma.profiles_educationsCreateArgs>(
            args: Prisma.SelectSubset<T, Prisma.profiles_educationsCreateArgs>,
            options?: Omit<(UseMutationOptions<(CheckSelect<T, profiles_educations, Prisma.profiles_educationsGetPayload<T>> | undefined), DefaultError, Prisma.SelectSubset<T, Prisma.profiles_educationsCreateArgs>> & ExtraMutationOptions), 'mutationFn'>
        ) => {
            return (await _mutation.mutateAsync(
                args,
                options as any
            )) as (CheckSelect<T, profiles_educations, Prisma.profiles_educationsGetPayload<T>> | undefined);
        },
    };
    return mutation;
}

export function useCreateManyprofiles_educations(options?: Omit<(UseMutationOptions<Prisma.BatchPayload, DefaultError, Prisma.profiles_educationsCreateManyArgs> & ExtraMutationOptions), 'mutationFn'>) {
    const { endpoint, fetch } = getHooksContext();
    const _mutation =
        useModelMutation<Prisma.profiles_educationsCreateManyArgs, DefaultError, Prisma.BatchPayload, false>('profiles_educations', 'POST', `${endpoint}/profiles_educations/createMany`, metadata, options, fetch, false)
        ;
    const mutation = {
        ..._mutation,
        mutateAsync: async <T extends Prisma.profiles_educationsCreateManyArgs>(
            args: Prisma.SelectSubset<T, Prisma.profiles_educationsCreateManyArgs>,
            options?: Omit<(UseMutationOptions<Prisma.BatchPayload, DefaultError, Prisma.SelectSubset<T, Prisma.profiles_educationsCreateManyArgs>> & ExtraMutationOptions), 'mutationFn'>
        ) => {
            return (await _mutation.mutateAsync(
                args,
                options as any
            )) as Prisma.BatchPayload;
        },
    };
    return mutation;
}

export function useFindManyprofiles_educations<TArgs extends Prisma.profiles_educationsFindManyArgs, TQueryFnData = Array<Prisma.profiles_educationsGetPayload<TArgs> & { $optimistic?: boolean }>, TData = TQueryFnData, TError = DefaultError>(args?: Prisma.SelectSubset<TArgs, Prisma.profiles_educationsFindManyArgs>, options?: (Omit<UseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useModelQuery<TQueryFnData, TData, TError>('profiles_educations', `${endpoint}/profiles_educations/findMany`, args, options, fetch);
}

export function useInfiniteFindManyprofiles_educations<TArgs extends Prisma.profiles_educationsFindManyArgs, TQueryFnData = Array<Prisma.profiles_educationsGetPayload<TArgs>>, TData = TQueryFnData, TError = DefaultError>(args?: Prisma.SelectSubset<TArgs, Prisma.profiles_educationsFindManyArgs>, options?: Omit<UseInfiniteQueryOptions<TQueryFnData, TError, InfiniteData<TData>>, 'queryKey' | 'initialPageParam'>) {
    options = options ?? { getNextPageParam: () => null };
    const { endpoint, fetch } = getHooksContext();
    return useInfiniteModelQuery<TQueryFnData, TData, TError>('profiles_educations', `${endpoint}/profiles_educations/findMany`, args, options, fetch);
}

export function useSuspenseFindManyprofiles_educations<TArgs extends Prisma.profiles_educationsFindManyArgs, TQueryFnData = Array<Prisma.profiles_educationsGetPayload<TArgs> & { $optimistic?: boolean }>, TData = TQueryFnData, TError = DefaultError>(args?: Prisma.SelectSubset<TArgs, Prisma.profiles_educationsFindManyArgs>, options?: (Omit<UseSuspenseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useSuspenseModelQuery<TQueryFnData, TData, TError>('profiles_educations', `${endpoint}/profiles_educations/findMany`, args, options, fetch);
}

export function useSuspenseInfiniteFindManyprofiles_educations<TArgs extends Prisma.profiles_educationsFindManyArgs, TQueryFnData = Array<Prisma.profiles_educationsGetPayload<TArgs>>, TData = TQueryFnData, TError = DefaultError>(args?: Prisma.SelectSubset<TArgs, Prisma.profiles_educationsFindManyArgs>, options?: Omit<UseSuspenseInfiniteQueryOptions<TQueryFnData, TError, InfiniteData<TData>>, 'queryKey' | 'initialPageParam'>) {
    options = options ?? { getNextPageParam: () => null };
    const { endpoint, fetch } = getHooksContext();
    return useSuspenseInfiniteModelQuery<TQueryFnData, TData, TError>('profiles_educations', `${endpoint}/profiles_educations/findMany`, args, options, fetch);
}

export function useFindUniqueprofiles_educations<TArgs extends Prisma.profiles_educationsFindUniqueArgs, TQueryFnData = Prisma.profiles_educationsGetPayload<TArgs> & { $optimistic?: boolean }, TData = TQueryFnData, TError = DefaultError>(args: Prisma.SelectSubset<TArgs, Prisma.profiles_educationsFindUniqueArgs>, options?: (Omit<UseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useModelQuery<TQueryFnData, TData, TError>('profiles_educations', `${endpoint}/profiles_educations/findUnique`, args, options, fetch);
}

export function useSuspenseFindUniqueprofiles_educations<TArgs extends Prisma.profiles_educationsFindUniqueArgs, TQueryFnData = Prisma.profiles_educationsGetPayload<TArgs> & { $optimistic?: boolean }, TData = TQueryFnData, TError = DefaultError>(args: Prisma.SelectSubset<TArgs, Prisma.profiles_educationsFindUniqueArgs>, options?: (Omit<UseSuspenseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useSuspenseModelQuery<TQueryFnData, TData, TError>('profiles_educations', `${endpoint}/profiles_educations/findUnique`, args, options, fetch);
}

export function useFindFirstprofiles_educations<TArgs extends Prisma.profiles_educationsFindFirstArgs, TQueryFnData = Prisma.profiles_educationsGetPayload<TArgs> & { $optimistic?: boolean }, TData = TQueryFnData, TError = DefaultError>(args?: Prisma.SelectSubset<TArgs, Prisma.profiles_educationsFindFirstArgs>, options?: (Omit<UseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useModelQuery<TQueryFnData, TData, TError>('profiles_educations', `${endpoint}/profiles_educations/findFirst`, args, options, fetch);
}

export function useSuspenseFindFirstprofiles_educations<TArgs extends Prisma.profiles_educationsFindFirstArgs, TQueryFnData = Prisma.profiles_educationsGetPayload<TArgs> & { $optimistic?: boolean }, TData = TQueryFnData, TError = DefaultError>(args?: Prisma.SelectSubset<TArgs, Prisma.profiles_educationsFindFirstArgs>, options?: (Omit<UseSuspenseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useSuspenseModelQuery<TQueryFnData, TData, TError>('profiles_educations', `${endpoint}/profiles_educations/findFirst`, args, options, fetch);
}

export function useUpdateprofiles_educations(options?: Omit<(UseMutationOptions<(profiles_educations | undefined), DefaultError, Prisma.profiles_educationsUpdateArgs> & ExtraMutationOptions), 'mutationFn'>) {
    const { endpoint, fetch } = getHooksContext();
    const _mutation =
        useModelMutation<Prisma.profiles_educationsUpdateArgs, DefaultError, profiles_educations, true>('profiles_educations', 'PUT', `${endpoint}/profiles_educations/update`, metadata, options, fetch, true)
        ;
    const mutation = {
        ..._mutation,
        mutateAsync: async <T extends Prisma.profiles_educationsUpdateArgs>(
            args: Prisma.SelectSubset<T, Prisma.profiles_educationsUpdateArgs>,
            options?: Omit<(UseMutationOptions<(CheckSelect<T, profiles_educations, Prisma.profiles_educationsGetPayload<T>> | undefined), DefaultError, Prisma.SelectSubset<T, Prisma.profiles_educationsUpdateArgs>> & ExtraMutationOptions), 'mutationFn'>
        ) => {
            return (await _mutation.mutateAsync(
                args,
                options as any
            )) as (CheckSelect<T, profiles_educations, Prisma.profiles_educationsGetPayload<T>> | undefined);
        },
    };
    return mutation;
}

export function useUpdateManyprofiles_educations(options?: Omit<(UseMutationOptions<Prisma.BatchPayload, DefaultError, Prisma.profiles_educationsUpdateManyArgs> & ExtraMutationOptions), 'mutationFn'>) {
    const { endpoint, fetch } = getHooksContext();
    const _mutation =
        useModelMutation<Prisma.profiles_educationsUpdateManyArgs, DefaultError, Prisma.BatchPayload, false>('profiles_educations', 'PUT', `${endpoint}/profiles_educations/updateMany`, metadata, options, fetch, false)
        ;
    const mutation = {
        ..._mutation,
        mutateAsync: async <T extends Prisma.profiles_educationsUpdateManyArgs>(
            args: Prisma.SelectSubset<T, Prisma.profiles_educationsUpdateManyArgs>,
            options?: Omit<(UseMutationOptions<Prisma.BatchPayload, DefaultError, Prisma.SelectSubset<T, Prisma.profiles_educationsUpdateManyArgs>> & ExtraMutationOptions), 'mutationFn'>
        ) => {
            return (await _mutation.mutateAsync(
                args,
                options as any
            )) as Prisma.BatchPayload;
        },
    };
    return mutation;
}

export function useUpsertprofiles_educations(options?: Omit<(UseMutationOptions<(profiles_educations | undefined), DefaultError, Prisma.profiles_educationsUpsertArgs> & ExtraMutationOptions), 'mutationFn'>) {
    const { endpoint, fetch } = getHooksContext();
    const _mutation =
        useModelMutation<Prisma.profiles_educationsUpsertArgs, DefaultError, profiles_educations, true>('profiles_educations', 'POST', `${endpoint}/profiles_educations/upsert`, metadata, options, fetch, true)
        ;
    const mutation = {
        ..._mutation,
        mutateAsync: async <T extends Prisma.profiles_educationsUpsertArgs>(
            args: Prisma.SelectSubset<T, Prisma.profiles_educationsUpsertArgs>,
            options?: Omit<(UseMutationOptions<(CheckSelect<T, profiles_educations, Prisma.profiles_educationsGetPayload<T>> | undefined), DefaultError, Prisma.SelectSubset<T, Prisma.profiles_educationsUpsertArgs>> & ExtraMutationOptions), 'mutationFn'>
        ) => {
            return (await _mutation.mutateAsync(
                args,
                options as any
            )) as (CheckSelect<T, profiles_educations, Prisma.profiles_educationsGetPayload<T>> | undefined);
        },
    };
    return mutation;
}

export function useDeleteprofiles_educations(options?: Omit<(UseMutationOptions<(profiles_educations | undefined), DefaultError, Prisma.profiles_educationsDeleteArgs> & ExtraMutationOptions), 'mutationFn'>) {
    const { endpoint, fetch } = getHooksContext();
    const _mutation =
        useModelMutation<Prisma.profiles_educationsDeleteArgs, DefaultError, profiles_educations, true>('profiles_educations', 'DELETE', `${endpoint}/profiles_educations/delete`, metadata, options, fetch, true)
        ;
    const mutation = {
        ..._mutation,
        mutateAsync: async <T extends Prisma.profiles_educationsDeleteArgs>(
            args: Prisma.SelectSubset<T, Prisma.profiles_educationsDeleteArgs>,
            options?: Omit<(UseMutationOptions<(CheckSelect<T, profiles_educations, Prisma.profiles_educationsGetPayload<T>> | undefined), DefaultError, Prisma.SelectSubset<T, Prisma.profiles_educationsDeleteArgs>> & ExtraMutationOptions), 'mutationFn'>
        ) => {
            return (await _mutation.mutateAsync(
                args,
                options as any
            )) as (CheckSelect<T, profiles_educations, Prisma.profiles_educationsGetPayload<T>> | undefined);
        },
    };
    return mutation;
}

export function useDeleteManyprofiles_educations(options?: Omit<(UseMutationOptions<Prisma.BatchPayload, DefaultError, Prisma.profiles_educationsDeleteManyArgs> & ExtraMutationOptions), 'mutationFn'>) {
    const { endpoint, fetch } = getHooksContext();
    const _mutation =
        useModelMutation<Prisma.profiles_educationsDeleteManyArgs, DefaultError, Prisma.BatchPayload, false>('profiles_educations', 'DELETE', `${endpoint}/profiles_educations/deleteMany`, metadata, options, fetch, false)
        ;
    const mutation = {
        ..._mutation,
        mutateAsync: async <T extends Prisma.profiles_educationsDeleteManyArgs>(
            args: Prisma.SelectSubset<T, Prisma.profiles_educationsDeleteManyArgs>,
            options?: Omit<(UseMutationOptions<Prisma.BatchPayload, DefaultError, Prisma.SelectSubset<T, Prisma.profiles_educationsDeleteManyArgs>> & ExtraMutationOptions), 'mutationFn'>
        ) => {
            return (await _mutation.mutateAsync(
                args,
                options as any
            )) as Prisma.BatchPayload;
        },
    };
    return mutation;
}

export function useAggregateProfiles_educations<TArgs extends Prisma.Profiles_educationsAggregateArgs, TQueryFnData = Prisma.GetProfiles_educationsAggregateType<TArgs>, TData = TQueryFnData, TError = DefaultError>(args: Prisma.SelectSubset<TArgs, Prisma.Profiles_educationsAggregateArgs>, options?: (Omit<UseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useModelQuery<TQueryFnData, TData, TError>('Profiles_educations', `${endpoint}/profiles_educations/aggregate`, args, options, fetch);
}

export function useSuspenseAggregateProfiles_educations<TArgs extends Prisma.Profiles_educationsAggregateArgs, TQueryFnData = Prisma.GetProfiles_educationsAggregateType<TArgs>, TData = TQueryFnData, TError = DefaultError>(args: Prisma.SelectSubset<TArgs, Prisma.Profiles_educationsAggregateArgs>, options?: (Omit<UseSuspenseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useSuspenseModelQuery<TQueryFnData, TData, TError>('Profiles_educations', `${endpoint}/profiles_educations/aggregate`, args, options, fetch);
}

export function useGroupByprofiles_educations<TArgs extends Prisma.profiles_educationsGroupByArgs, HasSelectOrTake extends Prisma.Or<Prisma.Extends<'skip', Prisma.Keys<TArgs>>, Prisma.Extends<'take', Prisma.Keys<TArgs>>>, OrderByArg extends Prisma.True extends HasSelectOrTake ? { orderBy: Prisma.profiles_educationsGroupByArgs['orderBy'] } : { orderBy?: Prisma.profiles_educationsGroupByArgs['orderBy'] }, OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<TArgs['orderBy']>>>, ByFields extends Prisma.MaybeTupleToUnion<TArgs['by']>, ByValid extends Prisma.Has<ByFields, OrderFields>, HavingFields extends Prisma.GetHavingFields<TArgs['having']>, HavingValid extends Prisma.Has<ByFields, HavingFields>, ByEmpty extends TArgs['by'] extends never[] ? Prisma.True : Prisma.False, InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
        ? never
        : P extends string
        ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
        : [
            Error,
            'Field ',
            P,
            ` in "having" needs to be provided in "by"`,
        ]
    }[HavingFields]
    : 'take' extends Prisma.Keys<TArgs>
    ? 'orderBy' extends Prisma.Keys<TArgs>
    ? ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
        ? never
        : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
    }[OrderFields]
    : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<TArgs>
    ? 'orderBy' extends Prisma.Keys<TArgs>
    ? ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
        ? never
        : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
    }[OrderFields]
    : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
        ? never
        : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
    }[OrderFields], TQueryFnData = {} extends InputErrors ?
    Array<PickEnumerable<Prisma.Profiles_educationsGroupByOutputType, TArgs['by']> &
    {
        [P in ((keyof TArgs) & (keyof Prisma.Profiles_educationsGroupByOutputType))]: P extends '_count'
        ? TArgs[P] extends boolean
        ? number
        : Prisma.GetScalarType<TArgs[P], Prisma.Profiles_educationsGroupByOutputType[P]>
        : Prisma.GetScalarType<TArgs[P], Prisma.Profiles_educationsGroupByOutputType[P]>
    }
    > : InputErrors, TData = TQueryFnData, TError = DefaultError>(args: Prisma.SelectSubset<TArgs, Prisma.SubsetIntersection<TArgs, Prisma.profiles_educationsGroupByArgs, OrderByArg> & InputErrors>, options?: (Omit<UseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useModelQuery<TQueryFnData, TData, TError>('profiles_educations', `${endpoint}/profiles_educations/groupBy`, args, options, fetch);
}

export function useSuspenseGroupByprofiles_educations<TArgs extends Prisma.profiles_educationsGroupByArgs, HasSelectOrTake extends Prisma.Or<Prisma.Extends<'skip', Prisma.Keys<TArgs>>, Prisma.Extends<'take', Prisma.Keys<TArgs>>>, OrderByArg extends Prisma.True extends HasSelectOrTake ? { orderBy: Prisma.profiles_educationsGroupByArgs['orderBy'] } : { orderBy?: Prisma.profiles_educationsGroupByArgs['orderBy'] }, OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<TArgs['orderBy']>>>, ByFields extends Prisma.MaybeTupleToUnion<TArgs['by']>, ByValid extends Prisma.Has<ByFields, OrderFields>, HavingFields extends Prisma.GetHavingFields<TArgs['having']>, HavingValid extends Prisma.Has<ByFields, HavingFields>, ByEmpty extends TArgs['by'] extends never[] ? Prisma.True : Prisma.False, InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
        ? never
        : P extends string
        ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
        : [
            Error,
            'Field ',
            P,
            ` in "having" needs to be provided in "by"`,
        ]
    }[HavingFields]
    : 'take' extends Prisma.Keys<TArgs>
    ? 'orderBy' extends Prisma.Keys<TArgs>
    ? ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
        ? never
        : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
    }[OrderFields]
    : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<TArgs>
    ? 'orderBy' extends Prisma.Keys<TArgs>
    ? ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
        ? never
        : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
    }[OrderFields]
    : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
        ? never
        : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
    }[OrderFields], TQueryFnData = {} extends InputErrors ?
    Array<PickEnumerable<Prisma.Profiles_educationsGroupByOutputType, TArgs['by']> &
    {
        [P in ((keyof TArgs) & (keyof Prisma.Profiles_educationsGroupByOutputType))]: P extends '_count'
        ? TArgs[P] extends boolean
        ? number
        : Prisma.GetScalarType<TArgs[P], Prisma.Profiles_educationsGroupByOutputType[P]>
        : Prisma.GetScalarType<TArgs[P], Prisma.Profiles_educationsGroupByOutputType[P]>
    }
    > : InputErrors, TData = TQueryFnData, TError = DefaultError>(args: Prisma.SelectSubset<TArgs, Prisma.SubsetIntersection<TArgs, Prisma.profiles_educationsGroupByArgs, OrderByArg> & InputErrors>, options?: (Omit<UseSuspenseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useSuspenseModelQuery<TQueryFnData, TData, TError>('profiles_educations', `${endpoint}/profiles_educations/groupBy`, args, options, fetch);
}

export function useCountprofiles_educations<TArgs extends Prisma.profiles_educationsCountArgs, TQueryFnData = TArgs extends { select: any; } ? TArgs['select'] extends true ? number : Prisma.GetScalarType<TArgs['select'], Prisma.Profiles_educationsCountAggregateOutputType> : number, TData = TQueryFnData, TError = DefaultError>(args?: Prisma.SelectSubset<TArgs, Prisma.profiles_educationsCountArgs>, options?: (Omit<UseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useModelQuery<TQueryFnData, TData, TError>('profiles_educations', `${endpoint}/profiles_educations/count`, args, options, fetch);
}

export function useSuspenseCountprofiles_educations<TArgs extends Prisma.profiles_educationsCountArgs, TQueryFnData = TArgs extends { select: any; } ? TArgs['select'] extends true ? number : Prisma.GetScalarType<TArgs['select'], Prisma.Profiles_educationsCountAggregateOutputType> : number, TData = TQueryFnData, TError = DefaultError>(args?: Prisma.SelectSubset<TArgs, Prisma.profiles_educationsCountArgs>, options?: (Omit<UseSuspenseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useSuspenseModelQuery<TQueryFnData, TData, TError>('profiles_educations', `${endpoint}/profiles_educations/count`, args, options, fetch);
}

export function useCheckprofiles_educations<TError = DefaultError>(args: { operation: PolicyCrudKind; where?: { id?: string; user_id?: string; degree?: string; institution?: string; field_of_study?: string; is_current?: boolean }; }, options?: (Omit<UseQueryOptions<boolean, TError, boolean>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useModelQuery<boolean, boolean, TError>('profiles_educations', `${endpoint}/profiles_educations/check`, args, options, fetch);
}
