/******************************************************************************
 * This file was generated by ZenStack CLI.
 ******************************************************************************/

/* eslint-disable */

import type { Prisma, profiles_notification_settings } from "@prisma/client";
import type { UseMutationOptions, UseQueryOptions, UseInfiniteQueryOptions, InfiniteData } from '@tanstack/react-query';
import { getHooksContext } from '@zenstackhq/tanstack-query/runtime-v5/react';
import { useModelQuery, useInfiniteModelQuery, useModelMutation } from '@zenstackhq/tanstack-query/runtime-v5/react';
import type { PickEnumerable, CheckSelect, QueryError, ExtraQueryOptions, ExtraMutationOptions } from '@zenstackhq/tanstack-query/runtime-v5';
import type { PolicyCrudKind } from '@zenstackhq/runtime'
import metadata from './__model_meta';
type DefaultError = QueryError;
import { useSuspenseModelQuery, useSuspenseInfiniteModelQuery } from '@zenstackhq/tanstack-query/runtime-v5/react';
import type { UseSuspenseQueryOptions, UseSuspenseInfiniteQueryOptions } from '@tanstack/react-query';

export function useCreateprofiles_notification_settings(options?: Omit<(UseMutationOptions<(profiles_notification_settings | undefined), DefaultError, Prisma.profiles_notification_settingsCreateArgs> & ExtraMutationOptions), 'mutationFn'>) {
    const { endpoint, fetch } = getHooksContext();
    const _mutation =
        useModelMutation<Prisma.profiles_notification_settingsCreateArgs, DefaultError, profiles_notification_settings, true>('profiles_notification_settings', 'POST', `${endpoint}/profiles_notification_settings/create`, metadata, options, fetch, true)
        ;
    const mutation = {
        ..._mutation,
        mutateAsync: async <T extends Prisma.profiles_notification_settingsCreateArgs>(
            args: Prisma.SelectSubset<T, Prisma.profiles_notification_settingsCreateArgs>,
            options?: Omit<(UseMutationOptions<(CheckSelect<T, profiles_notification_settings, Prisma.profiles_notification_settingsGetPayload<T>> | undefined), DefaultError, Prisma.SelectSubset<T, Prisma.profiles_notification_settingsCreateArgs>> & ExtraMutationOptions), 'mutationFn'>
        ) => {
            return (await _mutation.mutateAsync(
                args,
                options as any
            )) as (CheckSelect<T, profiles_notification_settings, Prisma.profiles_notification_settingsGetPayload<T>> | undefined);
        },
    };
    return mutation;
}

export function useCreateManyprofiles_notification_settings(options?: Omit<(UseMutationOptions<Prisma.BatchPayload, DefaultError, Prisma.profiles_notification_settingsCreateManyArgs> & ExtraMutationOptions), 'mutationFn'>) {
    const { endpoint, fetch } = getHooksContext();
    const _mutation =
        useModelMutation<Prisma.profiles_notification_settingsCreateManyArgs, DefaultError, Prisma.BatchPayload, false>('profiles_notification_settings', 'POST', `${endpoint}/profiles_notification_settings/createMany`, metadata, options, fetch, false)
        ;
    const mutation = {
        ..._mutation,
        mutateAsync: async <T extends Prisma.profiles_notification_settingsCreateManyArgs>(
            args: Prisma.SelectSubset<T, Prisma.profiles_notification_settingsCreateManyArgs>,
            options?: Omit<(UseMutationOptions<Prisma.BatchPayload, DefaultError, Prisma.SelectSubset<T, Prisma.profiles_notification_settingsCreateManyArgs>> & ExtraMutationOptions), 'mutationFn'>
        ) => {
            return (await _mutation.mutateAsync(
                args,
                options as any
            )) as Prisma.BatchPayload;
        },
    };
    return mutation;
}

export function useFindManyprofiles_notification_settings<TArgs extends Prisma.profiles_notification_settingsFindManyArgs, TQueryFnData = Array<Prisma.profiles_notification_settingsGetPayload<TArgs> & { $optimistic?: boolean }>, TData = TQueryFnData, TError = DefaultError>(args?: Prisma.SelectSubset<TArgs, Prisma.profiles_notification_settingsFindManyArgs>, options?: (Omit<UseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useModelQuery<TQueryFnData, TData, TError>('profiles_notification_settings', `${endpoint}/profiles_notification_settings/findMany`, args, options, fetch);
}

export function useInfiniteFindManyprofiles_notification_settings<TArgs extends Prisma.profiles_notification_settingsFindManyArgs, TQueryFnData = Array<Prisma.profiles_notification_settingsGetPayload<TArgs>>, TData = TQueryFnData, TError = DefaultError>(args?: Prisma.SelectSubset<TArgs, Prisma.profiles_notification_settingsFindManyArgs>, options?: Omit<UseInfiniteQueryOptions<TQueryFnData, TError, InfiniteData<TData>>, 'queryKey' | 'initialPageParam'>) {
    options = options ?? { getNextPageParam: () => null };
    const { endpoint, fetch } = getHooksContext();
    return useInfiniteModelQuery<TQueryFnData, TData, TError>('profiles_notification_settings', `${endpoint}/profiles_notification_settings/findMany`, args, options, fetch);
}

export function useSuspenseFindManyprofiles_notification_settings<TArgs extends Prisma.profiles_notification_settingsFindManyArgs, TQueryFnData = Array<Prisma.profiles_notification_settingsGetPayload<TArgs> & { $optimistic?: boolean }>, TData = TQueryFnData, TError = DefaultError>(args?: Prisma.SelectSubset<TArgs, Prisma.profiles_notification_settingsFindManyArgs>, options?: (Omit<UseSuspenseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useSuspenseModelQuery<TQueryFnData, TData, TError>('profiles_notification_settings', `${endpoint}/profiles_notification_settings/findMany`, args, options, fetch);
}

export function useSuspenseInfiniteFindManyprofiles_notification_settings<TArgs extends Prisma.profiles_notification_settingsFindManyArgs, TQueryFnData = Array<Prisma.profiles_notification_settingsGetPayload<TArgs>>, TData = TQueryFnData, TError = DefaultError>(args?: Prisma.SelectSubset<TArgs, Prisma.profiles_notification_settingsFindManyArgs>, options?: Omit<UseSuspenseInfiniteQueryOptions<TQueryFnData, TError, InfiniteData<TData>>, 'queryKey' | 'initialPageParam'>) {
    options = options ?? { getNextPageParam: () => null };
    const { endpoint, fetch } = getHooksContext();
    return useSuspenseInfiniteModelQuery<TQueryFnData, TData, TError>('profiles_notification_settings', `${endpoint}/profiles_notification_settings/findMany`, args, options, fetch);
}

export function useFindUniqueprofiles_notification_settings<TArgs extends Prisma.profiles_notification_settingsFindUniqueArgs, TQueryFnData = Prisma.profiles_notification_settingsGetPayload<TArgs> & { $optimistic?: boolean }, TData = TQueryFnData, TError = DefaultError>(args: Prisma.SelectSubset<TArgs, Prisma.profiles_notification_settingsFindUniqueArgs>, options?: (Omit<UseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useModelQuery<TQueryFnData, TData, TError>('profiles_notification_settings', `${endpoint}/profiles_notification_settings/findUnique`, args, options, fetch);
}

export function useSuspenseFindUniqueprofiles_notification_settings<TArgs extends Prisma.profiles_notification_settingsFindUniqueArgs, TQueryFnData = Prisma.profiles_notification_settingsGetPayload<TArgs> & { $optimistic?: boolean }, TData = TQueryFnData, TError = DefaultError>(args: Prisma.SelectSubset<TArgs, Prisma.profiles_notification_settingsFindUniqueArgs>, options?: (Omit<UseSuspenseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useSuspenseModelQuery<TQueryFnData, TData, TError>('profiles_notification_settings', `${endpoint}/profiles_notification_settings/findUnique`, args, options, fetch);
}

export function useFindFirstprofiles_notification_settings<TArgs extends Prisma.profiles_notification_settingsFindFirstArgs, TQueryFnData = Prisma.profiles_notification_settingsGetPayload<TArgs> & { $optimistic?: boolean }, TData = TQueryFnData, TError = DefaultError>(args?: Prisma.SelectSubset<TArgs, Prisma.profiles_notification_settingsFindFirstArgs>, options?: (Omit<UseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useModelQuery<TQueryFnData, TData, TError>('profiles_notification_settings', `${endpoint}/profiles_notification_settings/findFirst`, args, options, fetch);
}

export function useSuspenseFindFirstprofiles_notification_settings<TArgs extends Prisma.profiles_notification_settingsFindFirstArgs, TQueryFnData = Prisma.profiles_notification_settingsGetPayload<TArgs> & { $optimistic?: boolean }, TData = TQueryFnData, TError = DefaultError>(args?: Prisma.SelectSubset<TArgs, Prisma.profiles_notification_settingsFindFirstArgs>, options?: (Omit<UseSuspenseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useSuspenseModelQuery<TQueryFnData, TData, TError>('profiles_notification_settings', `${endpoint}/profiles_notification_settings/findFirst`, args, options, fetch);
}

export function useUpdateprofiles_notification_settings(options?: Omit<(UseMutationOptions<(profiles_notification_settings | undefined), DefaultError, Prisma.profiles_notification_settingsUpdateArgs> & ExtraMutationOptions), 'mutationFn'>) {
    const { endpoint, fetch } = getHooksContext();
    const _mutation =
        useModelMutation<Prisma.profiles_notification_settingsUpdateArgs, DefaultError, profiles_notification_settings, true>('profiles_notification_settings', 'PUT', `${endpoint}/profiles_notification_settings/update`, metadata, options, fetch, true)
        ;
    const mutation = {
        ..._mutation,
        mutateAsync: async <T extends Prisma.profiles_notification_settingsUpdateArgs>(
            args: Prisma.SelectSubset<T, Prisma.profiles_notification_settingsUpdateArgs>,
            options?: Omit<(UseMutationOptions<(CheckSelect<T, profiles_notification_settings, Prisma.profiles_notification_settingsGetPayload<T>> | undefined), DefaultError, Prisma.SelectSubset<T, Prisma.profiles_notification_settingsUpdateArgs>> & ExtraMutationOptions), 'mutationFn'>
        ) => {
            return (await _mutation.mutateAsync(
                args,
                options as any
            )) as (CheckSelect<T, profiles_notification_settings, Prisma.profiles_notification_settingsGetPayload<T>> | undefined);
        },
    };
    return mutation;
}

export function useUpdateManyprofiles_notification_settings(options?: Omit<(UseMutationOptions<Prisma.BatchPayload, DefaultError, Prisma.profiles_notification_settingsUpdateManyArgs> & ExtraMutationOptions), 'mutationFn'>) {
    const { endpoint, fetch } = getHooksContext();
    const _mutation =
        useModelMutation<Prisma.profiles_notification_settingsUpdateManyArgs, DefaultError, Prisma.BatchPayload, false>('profiles_notification_settings', 'PUT', `${endpoint}/profiles_notification_settings/updateMany`, metadata, options, fetch, false)
        ;
    const mutation = {
        ..._mutation,
        mutateAsync: async <T extends Prisma.profiles_notification_settingsUpdateManyArgs>(
            args: Prisma.SelectSubset<T, Prisma.profiles_notification_settingsUpdateManyArgs>,
            options?: Omit<(UseMutationOptions<Prisma.BatchPayload, DefaultError, Prisma.SelectSubset<T, Prisma.profiles_notification_settingsUpdateManyArgs>> & ExtraMutationOptions), 'mutationFn'>
        ) => {
            return (await _mutation.mutateAsync(
                args,
                options as any
            )) as Prisma.BatchPayload;
        },
    };
    return mutation;
}

export function useUpsertprofiles_notification_settings(options?: Omit<(UseMutationOptions<(profiles_notification_settings | undefined), DefaultError, Prisma.profiles_notification_settingsUpsertArgs> & ExtraMutationOptions), 'mutationFn'>) {
    const { endpoint, fetch } = getHooksContext();
    const _mutation =
        useModelMutation<Prisma.profiles_notification_settingsUpsertArgs, DefaultError, profiles_notification_settings, true>('profiles_notification_settings', 'POST', `${endpoint}/profiles_notification_settings/upsert`, metadata, options, fetch, true)
        ;
    const mutation = {
        ..._mutation,
        mutateAsync: async <T extends Prisma.profiles_notification_settingsUpsertArgs>(
            args: Prisma.SelectSubset<T, Prisma.profiles_notification_settingsUpsertArgs>,
            options?: Omit<(UseMutationOptions<(CheckSelect<T, profiles_notification_settings, Prisma.profiles_notification_settingsGetPayload<T>> | undefined), DefaultError, Prisma.SelectSubset<T, Prisma.profiles_notification_settingsUpsertArgs>> & ExtraMutationOptions), 'mutationFn'>
        ) => {
            return (await _mutation.mutateAsync(
                args,
                options as any
            )) as (CheckSelect<T, profiles_notification_settings, Prisma.profiles_notification_settingsGetPayload<T>> | undefined);
        },
    };
    return mutation;
}

export function useDeleteprofiles_notification_settings(options?: Omit<(UseMutationOptions<(profiles_notification_settings | undefined), DefaultError, Prisma.profiles_notification_settingsDeleteArgs> & ExtraMutationOptions), 'mutationFn'>) {
    const { endpoint, fetch } = getHooksContext();
    const _mutation =
        useModelMutation<Prisma.profiles_notification_settingsDeleteArgs, DefaultError, profiles_notification_settings, true>('profiles_notification_settings', 'DELETE', `${endpoint}/profiles_notification_settings/delete`, metadata, options, fetch, true)
        ;
    const mutation = {
        ..._mutation,
        mutateAsync: async <T extends Prisma.profiles_notification_settingsDeleteArgs>(
            args: Prisma.SelectSubset<T, Prisma.profiles_notification_settingsDeleteArgs>,
            options?: Omit<(UseMutationOptions<(CheckSelect<T, profiles_notification_settings, Prisma.profiles_notification_settingsGetPayload<T>> | undefined), DefaultError, Prisma.SelectSubset<T, Prisma.profiles_notification_settingsDeleteArgs>> & ExtraMutationOptions), 'mutationFn'>
        ) => {
            return (await _mutation.mutateAsync(
                args,
                options as any
            )) as (CheckSelect<T, profiles_notification_settings, Prisma.profiles_notification_settingsGetPayload<T>> | undefined);
        },
    };
    return mutation;
}

export function useDeleteManyprofiles_notification_settings(options?: Omit<(UseMutationOptions<Prisma.BatchPayload, DefaultError, Prisma.profiles_notification_settingsDeleteManyArgs> & ExtraMutationOptions), 'mutationFn'>) {
    const { endpoint, fetch } = getHooksContext();
    const _mutation =
        useModelMutation<Prisma.profiles_notification_settingsDeleteManyArgs, DefaultError, Prisma.BatchPayload, false>('profiles_notification_settings', 'DELETE', `${endpoint}/profiles_notification_settings/deleteMany`, metadata, options, fetch, false)
        ;
    const mutation = {
        ..._mutation,
        mutateAsync: async <T extends Prisma.profiles_notification_settingsDeleteManyArgs>(
            args: Prisma.SelectSubset<T, Prisma.profiles_notification_settingsDeleteManyArgs>,
            options?: Omit<(UseMutationOptions<Prisma.BatchPayload, DefaultError, Prisma.SelectSubset<T, Prisma.profiles_notification_settingsDeleteManyArgs>> & ExtraMutationOptions), 'mutationFn'>
        ) => {
            return (await _mutation.mutateAsync(
                args,
                options as any
            )) as Prisma.BatchPayload;
        },
    };
    return mutation;
}

export function useAggregateProfiles_notification_settings<TArgs extends Prisma.Profiles_notification_settingsAggregateArgs, TQueryFnData = Prisma.GetProfiles_notification_settingsAggregateType<TArgs>, TData = TQueryFnData, TError = DefaultError>(args: Prisma.SelectSubset<TArgs, Prisma.Profiles_notification_settingsAggregateArgs>, options?: (Omit<UseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useModelQuery<TQueryFnData, TData, TError>('Profiles_notification_settings', `${endpoint}/profiles_notification_settings/aggregate`, args, options, fetch);
}

export function useSuspenseAggregateProfiles_notification_settings<TArgs extends Prisma.Profiles_notification_settingsAggregateArgs, TQueryFnData = Prisma.GetProfiles_notification_settingsAggregateType<TArgs>, TData = TQueryFnData, TError = DefaultError>(args: Prisma.SelectSubset<TArgs, Prisma.Profiles_notification_settingsAggregateArgs>, options?: (Omit<UseSuspenseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useSuspenseModelQuery<TQueryFnData, TData, TError>('Profiles_notification_settings', `${endpoint}/profiles_notification_settings/aggregate`, args, options, fetch);
}

export function useGroupByprofiles_notification_settings<TArgs extends Prisma.profiles_notification_settingsGroupByArgs, HasSelectOrTake extends Prisma.Or<Prisma.Extends<'skip', Prisma.Keys<TArgs>>, Prisma.Extends<'take', Prisma.Keys<TArgs>>>, OrderByArg extends Prisma.True extends HasSelectOrTake ? { orderBy: Prisma.profiles_notification_settingsGroupByArgs['orderBy'] } : { orderBy?: Prisma.profiles_notification_settingsGroupByArgs['orderBy'] }, OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<TArgs['orderBy']>>>, ByFields extends Prisma.MaybeTupleToUnion<TArgs['by']>, ByValid extends Prisma.Has<ByFields, OrderFields>, HavingFields extends Prisma.GetHavingFields<TArgs['having']>, HavingValid extends Prisma.Has<ByFields, HavingFields>, ByEmpty extends TArgs['by'] extends never[] ? Prisma.True : Prisma.False, InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
        ? never
        : P extends string
        ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
        : [
            Error,
            'Field ',
            P,
            ` in "having" needs to be provided in "by"`,
        ]
    }[HavingFields]
    : 'take' extends Prisma.Keys<TArgs>
    ? 'orderBy' extends Prisma.Keys<TArgs>
    ? ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
        ? never
        : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
    }[OrderFields]
    : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<TArgs>
    ? 'orderBy' extends Prisma.Keys<TArgs>
    ? ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
        ? never
        : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
    }[OrderFields]
    : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
        ? never
        : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
    }[OrderFields], TQueryFnData = {} extends InputErrors ?
    Array<PickEnumerable<Prisma.Profiles_notification_settingsGroupByOutputType, TArgs['by']> &
    {
        [P in ((keyof TArgs) & (keyof Prisma.Profiles_notification_settingsGroupByOutputType))]: P extends '_count'
        ? TArgs[P] extends boolean
        ? number
        : Prisma.GetScalarType<TArgs[P], Prisma.Profiles_notification_settingsGroupByOutputType[P]>
        : Prisma.GetScalarType<TArgs[P], Prisma.Profiles_notification_settingsGroupByOutputType[P]>
    }
    > : InputErrors, TData = TQueryFnData, TError = DefaultError>(args: Prisma.SelectSubset<TArgs, Prisma.SubsetIntersection<TArgs, Prisma.profiles_notification_settingsGroupByArgs, OrderByArg> & InputErrors>, options?: (Omit<UseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useModelQuery<TQueryFnData, TData, TError>('profiles_notification_settings', `${endpoint}/profiles_notification_settings/groupBy`, args, options, fetch);
}

export function useSuspenseGroupByprofiles_notification_settings<TArgs extends Prisma.profiles_notification_settingsGroupByArgs, HasSelectOrTake extends Prisma.Or<Prisma.Extends<'skip', Prisma.Keys<TArgs>>, Prisma.Extends<'take', Prisma.Keys<TArgs>>>, OrderByArg extends Prisma.True extends HasSelectOrTake ? { orderBy: Prisma.profiles_notification_settingsGroupByArgs['orderBy'] } : { orderBy?: Prisma.profiles_notification_settingsGroupByArgs['orderBy'] }, OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<TArgs['orderBy']>>>, ByFields extends Prisma.MaybeTupleToUnion<TArgs['by']>, ByValid extends Prisma.Has<ByFields, OrderFields>, HavingFields extends Prisma.GetHavingFields<TArgs['having']>, HavingValid extends Prisma.Has<ByFields, HavingFields>, ByEmpty extends TArgs['by'] extends never[] ? Prisma.True : Prisma.False, InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
        ? never
        : P extends string
        ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
        : [
            Error,
            'Field ',
            P,
            ` in "having" needs to be provided in "by"`,
        ]
    }[HavingFields]
    : 'take' extends Prisma.Keys<TArgs>
    ? 'orderBy' extends Prisma.Keys<TArgs>
    ? ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
        ? never
        : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
    }[OrderFields]
    : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<TArgs>
    ? 'orderBy' extends Prisma.Keys<TArgs>
    ? ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
        ? never
        : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
    }[OrderFields]
    : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
        ? never
        : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
    }[OrderFields], TQueryFnData = {} extends InputErrors ?
    Array<PickEnumerable<Prisma.Profiles_notification_settingsGroupByOutputType, TArgs['by']> &
    {
        [P in ((keyof TArgs) & (keyof Prisma.Profiles_notification_settingsGroupByOutputType))]: P extends '_count'
        ? TArgs[P] extends boolean
        ? number
        : Prisma.GetScalarType<TArgs[P], Prisma.Profiles_notification_settingsGroupByOutputType[P]>
        : Prisma.GetScalarType<TArgs[P], Prisma.Profiles_notification_settingsGroupByOutputType[P]>
    }
    > : InputErrors, TData = TQueryFnData, TError = DefaultError>(args: Prisma.SelectSubset<TArgs, Prisma.SubsetIntersection<TArgs, Prisma.profiles_notification_settingsGroupByArgs, OrderByArg> & InputErrors>, options?: (Omit<UseSuspenseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useSuspenseModelQuery<TQueryFnData, TData, TError>('profiles_notification_settings', `${endpoint}/profiles_notification_settings/groupBy`, args, options, fetch);
}

export function useCountprofiles_notification_settings<TArgs extends Prisma.profiles_notification_settingsCountArgs, TQueryFnData = TArgs extends { select: any; } ? TArgs['select'] extends true ? number : Prisma.GetScalarType<TArgs['select'], Prisma.Profiles_notification_settingsCountAggregateOutputType> : number, TData = TQueryFnData, TError = DefaultError>(args?: Prisma.SelectSubset<TArgs, Prisma.profiles_notification_settingsCountArgs>, options?: (Omit<UseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useModelQuery<TQueryFnData, TData, TError>('profiles_notification_settings', `${endpoint}/profiles_notification_settings/count`, args, options, fetch);
}

export function useSuspenseCountprofiles_notification_settings<TArgs extends Prisma.profiles_notification_settingsCountArgs, TQueryFnData = TArgs extends { select: any; } ? TArgs['select'] extends true ? number : Prisma.GetScalarType<TArgs['select'], Prisma.Profiles_notification_settingsCountAggregateOutputType> : number, TData = TQueryFnData, TError = DefaultError>(args?: Prisma.SelectSubset<TArgs, Prisma.profiles_notification_settingsCountArgs>, options?: (Omit<UseSuspenseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useSuspenseModelQuery<TQueryFnData, TData, TError>('profiles_notification_settings', `${endpoint}/profiles_notification_settings/count`, args, options, fetch);
}

export function useCheckprofiles_notification_settings<TError = DefaultError>(args: { operation: PolicyCrudKind; where?: { id?: string; user_id?: string; push_enabled?: boolean; push_new_requests?: boolean; push_new_messages?: boolean; push_status_changes?: boolean; email_enabled?: boolean; email_new_requests?: boolean; email_new_messages?: boolean; email_digest?: boolean; email_digest_frequency?: string; quiet_hours_enabled?: boolean; quiet_hours_start?: string; quiet_hours_end?: string }; }, options?: (Omit<UseQueryOptions<boolean, TError, boolean>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useModelQuery<boolean, boolean, TError>('profiles_notification_settings', `${endpoint}/profiles_notification_settings/check`, args, options, fetch);
}
