/******************************************************************************
 * This file was generated by ZenStack CLI.
 ******************************************************************************/

/* eslint-disable */

import type { Prisma, profiles_push_subscriptions } from "@prisma/client";
import type { UseMutationOptions, UseQueryOptions, UseInfiniteQueryOptions, InfiniteData } from '@tanstack/react-query';
import { getHooksContext } from '@zenstackhq/tanstack-query/runtime-v5/react';
import { useModelQuery, useInfiniteModelQuery, useModelMutation } from '@zenstackhq/tanstack-query/runtime-v5/react';
import type { PickEnumerable, CheckSelect, QueryError, ExtraQueryOptions, ExtraMutationOptions } from '@zenstackhq/tanstack-query/runtime-v5';
import type { PolicyCrudKind } from '@zenstackhq/runtime'
import metadata from './__model_meta';
type DefaultError = QueryError;
import { useSuspenseModelQuery, useSuspenseInfiniteModelQuery } from '@zenstackhq/tanstack-query/runtime-v5/react';
import type { UseSuspenseQueryOptions, UseSuspenseInfiniteQueryOptions } from '@tanstack/react-query';

export function useCreateprofiles_push_subscriptions(options?: Omit<(UseMutationOptions<(profiles_push_subscriptions | undefined), DefaultError, Prisma.profiles_push_subscriptionsCreateArgs> & ExtraMutationOptions), 'mutationFn'>) {
    const { endpoint, fetch } = getHooksContext();
    const _mutation =
        useModelMutation<Prisma.profiles_push_subscriptionsCreateArgs, DefaultError, profiles_push_subscriptions, true>('profiles_push_subscriptions', 'POST', `${endpoint}/profiles_push_subscriptions/create`, metadata, options, fetch, true)
        ;
    const mutation = {
        ..._mutation,
        mutateAsync: async <T extends Prisma.profiles_push_subscriptionsCreateArgs>(
            args: Prisma.SelectSubset<T, Prisma.profiles_push_subscriptionsCreateArgs>,
            options?: Omit<(UseMutationOptions<(CheckSelect<T, profiles_push_subscriptions, Prisma.profiles_push_subscriptionsGetPayload<T>> | undefined), DefaultError, Prisma.SelectSubset<T, Prisma.profiles_push_subscriptionsCreateArgs>> & ExtraMutationOptions), 'mutationFn'>
        ) => {
            return (await _mutation.mutateAsync(
                args,
                options as any
            )) as (CheckSelect<T, profiles_push_subscriptions, Prisma.profiles_push_subscriptionsGetPayload<T>> | undefined);
        },
    };
    return mutation;
}

export function useCreateManyprofiles_push_subscriptions(options?: Omit<(UseMutationOptions<Prisma.BatchPayload, DefaultError, Prisma.profiles_push_subscriptionsCreateManyArgs> & ExtraMutationOptions), 'mutationFn'>) {
    const { endpoint, fetch } = getHooksContext();
    const _mutation =
        useModelMutation<Prisma.profiles_push_subscriptionsCreateManyArgs, DefaultError, Prisma.BatchPayload, false>('profiles_push_subscriptions', 'POST', `${endpoint}/profiles_push_subscriptions/createMany`, metadata, options, fetch, false)
        ;
    const mutation = {
        ..._mutation,
        mutateAsync: async <T extends Prisma.profiles_push_subscriptionsCreateManyArgs>(
            args: Prisma.SelectSubset<T, Prisma.profiles_push_subscriptionsCreateManyArgs>,
            options?: Omit<(UseMutationOptions<Prisma.BatchPayload, DefaultError, Prisma.SelectSubset<T, Prisma.profiles_push_subscriptionsCreateManyArgs>> & ExtraMutationOptions), 'mutationFn'>
        ) => {
            return (await _mutation.mutateAsync(
                args,
                options as any
            )) as Prisma.BatchPayload;
        },
    };
    return mutation;
}

export function useFindManyprofiles_push_subscriptions<TArgs extends Prisma.profiles_push_subscriptionsFindManyArgs, TQueryFnData = Array<Prisma.profiles_push_subscriptionsGetPayload<TArgs> & { $optimistic?: boolean }>, TData = TQueryFnData, TError = DefaultError>(args?: Prisma.SelectSubset<TArgs, Prisma.profiles_push_subscriptionsFindManyArgs>, options?: (Omit<UseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useModelQuery<TQueryFnData, TData, TError>('profiles_push_subscriptions', `${endpoint}/profiles_push_subscriptions/findMany`, args, options, fetch);
}

export function useInfiniteFindManyprofiles_push_subscriptions<TArgs extends Prisma.profiles_push_subscriptionsFindManyArgs, TQueryFnData = Array<Prisma.profiles_push_subscriptionsGetPayload<TArgs>>, TData = TQueryFnData, TError = DefaultError>(args?: Prisma.SelectSubset<TArgs, Prisma.profiles_push_subscriptionsFindManyArgs>, options?: Omit<UseInfiniteQueryOptions<TQueryFnData, TError, InfiniteData<TData>>, 'queryKey' | 'initialPageParam'>) {
    options = options ?? { getNextPageParam: () => null };
    const { endpoint, fetch } = getHooksContext();
    return useInfiniteModelQuery<TQueryFnData, TData, TError>('profiles_push_subscriptions', `${endpoint}/profiles_push_subscriptions/findMany`, args, options, fetch);
}

export function useSuspenseFindManyprofiles_push_subscriptions<TArgs extends Prisma.profiles_push_subscriptionsFindManyArgs, TQueryFnData = Array<Prisma.profiles_push_subscriptionsGetPayload<TArgs> & { $optimistic?: boolean }>, TData = TQueryFnData, TError = DefaultError>(args?: Prisma.SelectSubset<TArgs, Prisma.profiles_push_subscriptionsFindManyArgs>, options?: (Omit<UseSuspenseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useSuspenseModelQuery<TQueryFnData, TData, TError>('profiles_push_subscriptions', `${endpoint}/profiles_push_subscriptions/findMany`, args, options, fetch);
}

export function useSuspenseInfiniteFindManyprofiles_push_subscriptions<TArgs extends Prisma.profiles_push_subscriptionsFindManyArgs, TQueryFnData = Array<Prisma.profiles_push_subscriptionsGetPayload<TArgs>>, TData = TQueryFnData, TError = DefaultError>(args?: Prisma.SelectSubset<TArgs, Prisma.profiles_push_subscriptionsFindManyArgs>, options?: Omit<UseSuspenseInfiniteQueryOptions<TQueryFnData, TError, InfiniteData<TData>>, 'queryKey' | 'initialPageParam'>) {
    options = options ?? { getNextPageParam: () => null };
    const { endpoint, fetch } = getHooksContext();
    return useSuspenseInfiniteModelQuery<TQueryFnData, TData, TError>('profiles_push_subscriptions', `${endpoint}/profiles_push_subscriptions/findMany`, args, options, fetch);
}

export function useFindUniqueprofiles_push_subscriptions<TArgs extends Prisma.profiles_push_subscriptionsFindUniqueArgs, TQueryFnData = Prisma.profiles_push_subscriptionsGetPayload<TArgs> & { $optimistic?: boolean }, TData = TQueryFnData, TError = DefaultError>(args: Prisma.SelectSubset<TArgs, Prisma.profiles_push_subscriptionsFindUniqueArgs>, options?: (Omit<UseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useModelQuery<TQueryFnData, TData, TError>('profiles_push_subscriptions', `${endpoint}/profiles_push_subscriptions/findUnique`, args, options, fetch);
}

export function useSuspenseFindUniqueprofiles_push_subscriptions<TArgs extends Prisma.profiles_push_subscriptionsFindUniqueArgs, TQueryFnData = Prisma.profiles_push_subscriptionsGetPayload<TArgs> & { $optimistic?: boolean }, TData = TQueryFnData, TError = DefaultError>(args: Prisma.SelectSubset<TArgs, Prisma.profiles_push_subscriptionsFindUniqueArgs>, options?: (Omit<UseSuspenseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useSuspenseModelQuery<TQueryFnData, TData, TError>('profiles_push_subscriptions', `${endpoint}/profiles_push_subscriptions/findUnique`, args, options, fetch);
}

export function useFindFirstprofiles_push_subscriptions<TArgs extends Prisma.profiles_push_subscriptionsFindFirstArgs, TQueryFnData = Prisma.profiles_push_subscriptionsGetPayload<TArgs> & { $optimistic?: boolean }, TData = TQueryFnData, TError = DefaultError>(args?: Prisma.SelectSubset<TArgs, Prisma.profiles_push_subscriptionsFindFirstArgs>, options?: (Omit<UseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useModelQuery<TQueryFnData, TData, TError>('profiles_push_subscriptions', `${endpoint}/profiles_push_subscriptions/findFirst`, args, options, fetch);
}

export function useSuspenseFindFirstprofiles_push_subscriptions<TArgs extends Prisma.profiles_push_subscriptionsFindFirstArgs, TQueryFnData = Prisma.profiles_push_subscriptionsGetPayload<TArgs> & { $optimistic?: boolean }, TData = TQueryFnData, TError = DefaultError>(args?: Prisma.SelectSubset<TArgs, Prisma.profiles_push_subscriptionsFindFirstArgs>, options?: (Omit<UseSuspenseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useSuspenseModelQuery<TQueryFnData, TData, TError>('profiles_push_subscriptions', `${endpoint}/profiles_push_subscriptions/findFirst`, args, options, fetch);
}

export function useUpdateprofiles_push_subscriptions(options?: Omit<(UseMutationOptions<(profiles_push_subscriptions | undefined), DefaultError, Prisma.profiles_push_subscriptionsUpdateArgs> & ExtraMutationOptions), 'mutationFn'>) {
    const { endpoint, fetch } = getHooksContext();
    const _mutation =
        useModelMutation<Prisma.profiles_push_subscriptionsUpdateArgs, DefaultError, profiles_push_subscriptions, true>('profiles_push_subscriptions', 'PUT', `${endpoint}/profiles_push_subscriptions/update`, metadata, options, fetch, true)
        ;
    const mutation = {
        ..._mutation,
        mutateAsync: async <T extends Prisma.profiles_push_subscriptionsUpdateArgs>(
            args: Prisma.SelectSubset<T, Prisma.profiles_push_subscriptionsUpdateArgs>,
            options?: Omit<(UseMutationOptions<(CheckSelect<T, profiles_push_subscriptions, Prisma.profiles_push_subscriptionsGetPayload<T>> | undefined), DefaultError, Prisma.SelectSubset<T, Prisma.profiles_push_subscriptionsUpdateArgs>> & ExtraMutationOptions), 'mutationFn'>
        ) => {
            return (await _mutation.mutateAsync(
                args,
                options as any
            )) as (CheckSelect<T, profiles_push_subscriptions, Prisma.profiles_push_subscriptionsGetPayload<T>> | undefined);
        },
    };
    return mutation;
}

export function useUpdateManyprofiles_push_subscriptions(options?: Omit<(UseMutationOptions<Prisma.BatchPayload, DefaultError, Prisma.profiles_push_subscriptionsUpdateManyArgs> & ExtraMutationOptions), 'mutationFn'>) {
    const { endpoint, fetch } = getHooksContext();
    const _mutation =
        useModelMutation<Prisma.profiles_push_subscriptionsUpdateManyArgs, DefaultError, Prisma.BatchPayload, false>('profiles_push_subscriptions', 'PUT', `${endpoint}/profiles_push_subscriptions/updateMany`, metadata, options, fetch, false)
        ;
    const mutation = {
        ..._mutation,
        mutateAsync: async <T extends Prisma.profiles_push_subscriptionsUpdateManyArgs>(
            args: Prisma.SelectSubset<T, Prisma.profiles_push_subscriptionsUpdateManyArgs>,
            options?: Omit<(UseMutationOptions<Prisma.BatchPayload, DefaultError, Prisma.SelectSubset<T, Prisma.profiles_push_subscriptionsUpdateManyArgs>> & ExtraMutationOptions), 'mutationFn'>
        ) => {
            return (await _mutation.mutateAsync(
                args,
                options as any
            )) as Prisma.BatchPayload;
        },
    };
    return mutation;
}

export function useUpsertprofiles_push_subscriptions(options?: Omit<(UseMutationOptions<(profiles_push_subscriptions | undefined), DefaultError, Prisma.profiles_push_subscriptionsUpsertArgs> & ExtraMutationOptions), 'mutationFn'>) {
    const { endpoint, fetch } = getHooksContext();
    const _mutation =
        useModelMutation<Prisma.profiles_push_subscriptionsUpsertArgs, DefaultError, profiles_push_subscriptions, true>('profiles_push_subscriptions', 'POST', `${endpoint}/profiles_push_subscriptions/upsert`, metadata, options, fetch, true)
        ;
    const mutation = {
        ..._mutation,
        mutateAsync: async <T extends Prisma.profiles_push_subscriptionsUpsertArgs>(
            args: Prisma.SelectSubset<T, Prisma.profiles_push_subscriptionsUpsertArgs>,
            options?: Omit<(UseMutationOptions<(CheckSelect<T, profiles_push_subscriptions, Prisma.profiles_push_subscriptionsGetPayload<T>> | undefined), DefaultError, Prisma.SelectSubset<T, Prisma.profiles_push_subscriptionsUpsertArgs>> & ExtraMutationOptions), 'mutationFn'>
        ) => {
            return (await _mutation.mutateAsync(
                args,
                options as any
            )) as (CheckSelect<T, profiles_push_subscriptions, Prisma.profiles_push_subscriptionsGetPayload<T>> | undefined);
        },
    };
    return mutation;
}

export function useDeleteprofiles_push_subscriptions(options?: Omit<(UseMutationOptions<(profiles_push_subscriptions | undefined), DefaultError, Prisma.profiles_push_subscriptionsDeleteArgs> & ExtraMutationOptions), 'mutationFn'>) {
    const { endpoint, fetch } = getHooksContext();
    const _mutation =
        useModelMutation<Prisma.profiles_push_subscriptionsDeleteArgs, DefaultError, profiles_push_subscriptions, true>('profiles_push_subscriptions', 'DELETE', `${endpoint}/profiles_push_subscriptions/delete`, metadata, options, fetch, true)
        ;
    const mutation = {
        ..._mutation,
        mutateAsync: async <T extends Prisma.profiles_push_subscriptionsDeleteArgs>(
            args: Prisma.SelectSubset<T, Prisma.profiles_push_subscriptionsDeleteArgs>,
            options?: Omit<(UseMutationOptions<(CheckSelect<T, profiles_push_subscriptions, Prisma.profiles_push_subscriptionsGetPayload<T>> | undefined), DefaultError, Prisma.SelectSubset<T, Prisma.profiles_push_subscriptionsDeleteArgs>> & ExtraMutationOptions), 'mutationFn'>
        ) => {
            return (await _mutation.mutateAsync(
                args,
                options as any
            )) as (CheckSelect<T, profiles_push_subscriptions, Prisma.profiles_push_subscriptionsGetPayload<T>> | undefined);
        },
    };
    return mutation;
}

export function useDeleteManyprofiles_push_subscriptions(options?: Omit<(UseMutationOptions<Prisma.BatchPayload, DefaultError, Prisma.profiles_push_subscriptionsDeleteManyArgs> & ExtraMutationOptions), 'mutationFn'>) {
    const { endpoint, fetch } = getHooksContext();
    const _mutation =
        useModelMutation<Prisma.profiles_push_subscriptionsDeleteManyArgs, DefaultError, Prisma.BatchPayload, false>('profiles_push_subscriptions', 'DELETE', `${endpoint}/profiles_push_subscriptions/deleteMany`, metadata, options, fetch, false)
        ;
    const mutation = {
        ..._mutation,
        mutateAsync: async <T extends Prisma.profiles_push_subscriptionsDeleteManyArgs>(
            args: Prisma.SelectSubset<T, Prisma.profiles_push_subscriptionsDeleteManyArgs>,
            options?: Omit<(UseMutationOptions<Prisma.BatchPayload, DefaultError, Prisma.SelectSubset<T, Prisma.profiles_push_subscriptionsDeleteManyArgs>> & ExtraMutationOptions), 'mutationFn'>
        ) => {
            return (await _mutation.mutateAsync(
                args,
                options as any
            )) as Prisma.BatchPayload;
        },
    };
    return mutation;
}

export function useAggregateProfiles_push_subscriptions<TArgs extends Prisma.Profiles_push_subscriptionsAggregateArgs, TQueryFnData = Prisma.GetProfiles_push_subscriptionsAggregateType<TArgs>, TData = TQueryFnData, TError = DefaultError>(args: Prisma.SelectSubset<TArgs, Prisma.Profiles_push_subscriptionsAggregateArgs>, options?: (Omit<UseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useModelQuery<TQueryFnData, TData, TError>('Profiles_push_subscriptions', `${endpoint}/profiles_push_subscriptions/aggregate`, args, options, fetch);
}

export function useSuspenseAggregateProfiles_push_subscriptions<TArgs extends Prisma.Profiles_push_subscriptionsAggregateArgs, TQueryFnData = Prisma.GetProfiles_push_subscriptionsAggregateType<TArgs>, TData = TQueryFnData, TError = DefaultError>(args: Prisma.SelectSubset<TArgs, Prisma.Profiles_push_subscriptionsAggregateArgs>, options?: (Omit<UseSuspenseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useSuspenseModelQuery<TQueryFnData, TData, TError>('Profiles_push_subscriptions', `${endpoint}/profiles_push_subscriptions/aggregate`, args, options, fetch);
}

export function useGroupByprofiles_push_subscriptions<TArgs extends Prisma.profiles_push_subscriptionsGroupByArgs, HasSelectOrTake extends Prisma.Or<Prisma.Extends<'skip', Prisma.Keys<TArgs>>, Prisma.Extends<'take', Prisma.Keys<TArgs>>>, OrderByArg extends Prisma.True extends HasSelectOrTake ? { orderBy: Prisma.profiles_push_subscriptionsGroupByArgs['orderBy'] } : { orderBy?: Prisma.profiles_push_subscriptionsGroupByArgs['orderBy'] }, OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<TArgs['orderBy']>>>, ByFields extends Prisma.MaybeTupleToUnion<TArgs['by']>, ByValid extends Prisma.Has<ByFields, OrderFields>, HavingFields extends Prisma.GetHavingFields<TArgs['having']>, HavingValid extends Prisma.Has<ByFields, HavingFields>, ByEmpty extends TArgs['by'] extends never[] ? Prisma.True : Prisma.False, InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
        ? never
        : P extends string
        ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
        : [
            Error,
            'Field ',
            P,
            ` in "having" needs to be provided in "by"`,
        ]
    }[HavingFields]
    : 'take' extends Prisma.Keys<TArgs>
    ? 'orderBy' extends Prisma.Keys<TArgs>
    ? ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
        ? never
        : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
    }[OrderFields]
    : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<TArgs>
    ? 'orderBy' extends Prisma.Keys<TArgs>
    ? ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
        ? never
        : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
    }[OrderFields]
    : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
        ? never
        : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
    }[OrderFields], TQueryFnData = {} extends InputErrors ?
    Array<PickEnumerable<Prisma.Profiles_push_subscriptionsGroupByOutputType, TArgs['by']> &
    {
        [P in ((keyof TArgs) & (keyof Prisma.Profiles_push_subscriptionsGroupByOutputType))]: P extends '_count'
        ? TArgs[P] extends boolean
        ? number
        : Prisma.GetScalarType<TArgs[P], Prisma.Profiles_push_subscriptionsGroupByOutputType[P]>
        : Prisma.GetScalarType<TArgs[P], Prisma.Profiles_push_subscriptionsGroupByOutputType[P]>
    }
    > : InputErrors, TData = TQueryFnData, TError = DefaultError>(args: Prisma.SelectSubset<TArgs, Prisma.SubsetIntersection<TArgs, Prisma.profiles_push_subscriptionsGroupByArgs, OrderByArg> & InputErrors>, options?: (Omit<UseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useModelQuery<TQueryFnData, TData, TError>('profiles_push_subscriptions', `${endpoint}/profiles_push_subscriptions/groupBy`, args, options, fetch);
}

export function useSuspenseGroupByprofiles_push_subscriptions<TArgs extends Prisma.profiles_push_subscriptionsGroupByArgs, HasSelectOrTake extends Prisma.Or<Prisma.Extends<'skip', Prisma.Keys<TArgs>>, Prisma.Extends<'take', Prisma.Keys<TArgs>>>, OrderByArg extends Prisma.True extends HasSelectOrTake ? { orderBy: Prisma.profiles_push_subscriptionsGroupByArgs['orderBy'] } : { orderBy?: Prisma.profiles_push_subscriptionsGroupByArgs['orderBy'] }, OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<TArgs['orderBy']>>>, ByFields extends Prisma.MaybeTupleToUnion<TArgs['by']>, ByValid extends Prisma.Has<ByFields, OrderFields>, HavingFields extends Prisma.GetHavingFields<TArgs['having']>, HavingValid extends Prisma.Has<ByFields, HavingFields>, ByEmpty extends TArgs['by'] extends never[] ? Prisma.True : Prisma.False, InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
        ? never
        : P extends string
        ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
        : [
            Error,
            'Field ',
            P,
            ` in "having" needs to be provided in "by"`,
        ]
    }[HavingFields]
    : 'take' extends Prisma.Keys<TArgs>
    ? 'orderBy' extends Prisma.Keys<TArgs>
    ? ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
        ? never
        : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
    }[OrderFields]
    : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<TArgs>
    ? 'orderBy' extends Prisma.Keys<TArgs>
    ? ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
        ? never
        : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
    }[OrderFields]
    : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
        ? never
        : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
    }[OrderFields], TQueryFnData = {} extends InputErrors ?
    Array<PickEnumerable<Prisma.Profiles_push_subscriptionsGroupByOutputType, TArgs['by']> &
    {
        [P in ((keyof TArgs) & (keyof Prisma.Profiles_push_subscriptionsGroupByOutputType))]: P extends '_count'
        ? TArgs[P] extends boolean
        ? number
        : Prisma.GetScalarType<TArgs[P], Prisma.Profiles_push_subscriptionsGroupByOutputType[P]>
        : Prisma.GetScalarType<TArgs[P], Prisma.Profiles_push_subscriptionsGroupByOutputType[P]>
    }
    > : InputErrors, TData = TQueryFnData, TError = DefaultError>(args: Prisma.SelectSubset<TArgs, Prisma.SubsetIntersection<TArgs, Prisma.profiles_push_subscriptionsGroupByArgs, OrderByArg> & InputErrors>, options?: (Omit<UseSuspenseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useSuspenseModelQuery<TQueryFnData, TData, TError>('profiles_push_subscriptions', `${endpoint}/profiles_push_subscriptions/groupBy`, args, options, fetch);
}

export function useCountprofiles_push_subscriptions<TArgs extends Prisma.profiles_push_subscriptionsCountArgs, TQueryFnData = TArgs extends { select: any; } ? TArgs['select'] extends true ? number : Prisma.GetScalarType<TArgs['select'], Prisma.Profiles_push_subscriptionsCountAggregateOutputType> : number, TData = TQueryFnData, TError = DefaultError>(args?: Prisma.SelectSubset<TArgs, Prisma.profiles_push_subscriptionsCountArgs>, options?: (Omit<UseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useModelQuery<TQueryFnData, TData, TError>('profiles_push_subscriptions', `${endpoint}/profiles_push_subscriptions/count`, args, options, fetch);
}

export function useSuspenseCountprofiles_push_subscriptions<TArgs extends Prisma.profiles_push_subscriptionsCountArgs, TQueryFnData = TArgs extends { select: any; } ? TArgs['select'] extends true ? number : Prisma.GetScalarType<TArgs['select'], Prisma.Profiles_push_subscriptionsCountAggregateOutputType> : number, TData = TQueryFnData, TError = DefaultError>(args?: Prisma.SelectSubset<TArgs, Prisma.profiles_push_subscriptionsCountArgs>, options?: (Omit<UseSuspenseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useSuspenseModelQuery<TQueryFnData, TData, TError>('profiles_push_subscriptions', `${endpoint}/profiles_push_subscriptions/count`, args, options, fetch);
}

export function useCheckprofiles_push_subscriptions<TError = DefaultError>(args: { operation: PolicyCrudKind; where?: { id?: string; user_id?: string; endpoint?: string; p256dh?: string; auth?: string }; }, options?: (Omit<UseQueryOptions<boolean, TError, boolean>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useModelQuery<boolean, boolean, TError>('profiles_push_subscriptions', `${endpoint}/profiles_push_subscriptions/check`, args, options, fetch);
}
