/******************************************************************************
 * This file was generated by ZenStack CLI.
 ******************************************************************************/

/* eslint-disable */

import type { Prisma, user_favorites } from "@prisma/client";
import type { UseMutationOptions, UseQueryOptions, UseInfiniteQueryOptions, InfiniteData } from '@tanstack/react-query';
import { getHooksContext } from '@zenstackhq/tanstack-query/runtime-v5/react';
import { useModelQuery, useInfiniteModelQuery, useModelMutation } from '@zenstackhq/tanstack-query/runtime-v5/react';
import type { PickEnumerable, CheckSelect, QueryError, ExtraQueryOptions, ExtraMutationOptions } from '@zenstackhq/tanstack-query/runtime-v5';
import type { PolicyCrudKind } from '@zenstackhq/runtime'
import metadata from './__model_meta';
type DefaultError = QueryError;
import { useSuspenseModelQuery, useSuspenseInfiniteModelQuery } from '@zenstackhq/tanstack-query/runtime-v5/react';
import type { UseSuspenseQueryOptions, UseSuspenseInfiniteQueryOptions } from '@tanstack/react-query';

export function useCreateuser_favorites(options?: Omit<(UseMutationOptions<(user_favorites | undefined), DefaultError, Prisma.user_favoritesCreateArgs> & ExtraMutationOptions), 'mutationFn'>) {
    const { endpoint, fetch } = getHooksContext();
    const _mutation =
        useModelMutation<Prisma.user_favoritesCreateArgs, DefaultError, user_favorites, true>('user_favorites', 'POST', `${endpoint}/user_favorites/create`, metadata, options, fetch, true)
        ;
    const mutation = {
        ..._mutation,
        mutateAsync: async <T extends Prisma.user_favoritesCreateArgs>(
            args: Prisma.SelectSubset<T, Prisma.user_favoritesCreateArgs>,
            options?: Omit<(UseMutationOptions<(CheckSelect<T, user_favorites, Prisma.user_favoritesGetPayload<T>> | undefined), DefaultError, Prisma.SelectSubset<T, Prisma.user_favoritesCreateArgs>> & ExtraMutationOptions), 'mutationFn'>
        ) => {
            return (await _mutation.mutateAsync(
                args,
                options as any
            )) as (CheckSelect<T, user_favorites, Prisma.user_favoritesGetPayload<T>> | undefined);
        },
    };
    return mutation;
}

export function useCreateManyuser_favorites(options?: Omit<(UseMutationOptions<Prisma.BatchPayload, DefaultError, Prisma.user_favoritesCreateManyArgs> & ExtraMutationOptions), 'mutationFn'>) {
    const { endpoint, fetch } = getHooksContext();
    const _mutation =
        useModelMutation<Prisma.user_favoritesCreateManyArgs, DefaultError, Prisma.BatchPayload, false>('user_favorites', 'POST', `${endpoint}/user_favorites/createMany`, metadata, options, fetch, false)
        ;
    const mutation = {
        ..._mutation,
        mutateAsync: async <T extends Prisma.user_favoritesCreateManyArgs>(
            args: Prisma.SelectSubset<T, Prisma.user_favoritesCreateManyArgs>,
            options?: Omit<(UseMutationOptions<Prisma.BatchPayload, DefaultError, Prisma.SelectSubset<T, Prisma.user_favoritesCreateManyArgs>> & ExtraMutationOptions), 'mutationFn'>
        ) => {
            return (await _mutation.mutateAsync(
                args,
                options as any
            )) as Prisma.BatchPayload;
        },
    };
    return mutation;
}

export function useFindManyuser_favorites<TArgs extends Prisma.user_favoritesFindManyArgs, TQueryFnData = Array<Prisma.user_favoritesGetPayload<TArgs> & { $optimistic?: boolean }>, TData = TQueryFnData, TError = DefaultError>(args?: Prisma.SelectSubset<TArgs, Prisma.user_favoritesFindManyArgs>, options?: (Omit<UseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useModelQuery<TQueryFnData, TData, TError>('user_favorites', `${endpoint}/user_favorites/findMany`, args, options, fetch);
}

export function useInfiniteFindManyuser_favorites<TArgs extends Prisma.user_favoritesFindManyArgs, TQueryFnData = Array<Prisma.user_favoritesGetPayload<TArgs>>, TData = TQueryFnData, TError = DefaultError>(args?: Prisma.SelectSubset<TArgs, Prisma.user_favoritesFindManyArgs>, options?: Omit<UseInfiniteQueryOptions<TQueryFnData, TError, InfiniteData<TData>>, 'queryKey' | 'initialPageParam'>) {
    options = options ?? { getNextPageParam: () => null };
    const { endpoint, fetch } = getHooksContext();
    return useInfiniteModelQuery<TQueryFnData, TData, TError>('user_favorites', `${endpoint}/user_favorites/findMany`, args, options, fetch);
}

export function useSuspenseFindManyuser_favorites<TArgs extends Prisma.user_favoritesFindManyArgs, TQueryFnData = Array<Prisma.user_favoritesGetPayload<TArgs> & { $optimistic?: boolean }>, TData = TQueryFnData, TError = DefaultError>(args?: Prisma.SelectSubset<TArgs, Prisma.user_favoritesFindManyArgs>, options?: (Omit<UseSuspenseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useSuspenseModelQuery<TQueryFnData, TData, TError>('user_favorites', `${endpoint}/user_favorites/findMany`, args, options, fetch);
}

export function useSuspenseInfiniteFindManyuser_favorites<TArgs extends Prisma.user_favoritesFindManyArgs, TQueryFnData = Array<Prisma.user_favoritesGetPayload<TArgs>>, TData = TQueryFnData, TError = DefaultError>(args?: Prisma.SelectSubset<TArgs, Prisma.user_favoritesFindManyArgs>, options?: Omit<UseSuspenseInfiniteQueryOptions<TQueryFnData, TError, InfiniteData<TData>>, 'queryKey' | 'initialPageParam'>) {
    options = options ?? { getNextPageParam: () => null };
    const { endpoint, fetch } = getHooksContext();
    return useSuspenseInfiniteModelQuery<TQueryFnData, TData, TError>('user_favorites', `${endpoint}/user_favorites/findMany`, args, options, fetch);
}

export function useFindUniqueuser_favorites<TArgs extends Prisma.user_favoritesFindUniqueArgs, TQueryFnData = Prisma.user_favoritesGetPayload<TArgs> & { $optimistic?: boolean }, TData = TQueryFnData, TError = DefaultError>(args: Prisma.SelectSubset<TArgs, Prisma.user_favoritesFindUniqueArgs>, options?: (Omit<UseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useModelQuery<TQueryFnData, TData, TError>('user_favorites', `${endpoint}/user_favorites/findUnique`, args, options, fetch);
}

export function useSuspenseFindUniqueuser_favorites<TArgs extends Prisma.user_favoritesFindUniqueArgs, TQueryFnData = Prisma.user_favoritesGetPayload<TArgs> & { $optimistic?: boolean }, TData = TQueryFnData, TError = DefaultError>(args: Prisma.SelectSubset<TArgs, Prisma.user_favoritesFindUniqueArgs>, options?: (Omit<UseSuspenseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useSuspenseModelQuery<TQueryFnData, TData, TError>('user_favorites', `${endpoint}/user_favorites/findUnique`, args, options, fetch);
}

export function useFindFirstuser_favorites<TArgs extends Prisma.user_favoritesFindFirstArgs, TQueryFnData = Prisma.user_favoritesGetPayload<TArgs> & { $optimistic?: boolean }, TData = TQueryFnData, TError = DefaultError>(args?: Prisma.SelectSubset<TArgs, Prisma.user_favoritesFindFirstArgs>, options?: (Omit<UseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useModelQuery<TQueryFnData, TData, TError>('user_favorites', `${endpoint}/user_favorites/findFirst`, args, options, fetch);
}

export function useSuspenseFindFirstuser_favorites<TArgs extends Prisma.user_favoritesFindFirstArgs, TQueryFnData = Prisma.user_favoritesGetPayload<TArgs> & { $optimistic?: boolean }, TData = TQueryFnData, TError = DefaultError>(args?: Prisma.SelectSubset<TArgs, Prisma.user_favoritesFindFirstArgs>, options?: (Omit<UseSuspenseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useSuspenseModelQuery<TQueryFnData, TData, TError>('user_favorites', `${endpoint}/user_favorites/findFirst`, args, options, fetch);
}

export function useUpdateuser_favorites(options?: Omit<(UseMutationOptions<(user_favorites | undefined), DefaultError, Prisma.user_favoritesUpdateArgs> & ExtraMutationOptions), 'mutationFn'>) {
    const { endpoint, fetch } = getHooksContext();
    const _mutation =
        useModelMutation<Prisma.user_favoritesUpdateArgs, DefaultError, user_favorites, true>('user_favorites', 'PUT', `${endpoint}/user_favorites/update`, metadata, options, fetch, true)
        ;
    const mutation = {
        ..._mutation,
        mutateAsync: async <T extends Prisma.user_favoritesUpdateArgs>(
            args: Prisma.SelectSubset<T, Prisma.user_favoritesUpdateArgs>,
            options?: Omit<(UseMutationOptions<(CheckSelect<T, user_favorites, Prisma.user_favoritesGetPayload<T>> | undefined), DefaultError, Prisma.SelectSubset<T, Prisma.user_favoritesUpdateArgs>> & ExtraMutationOptions), 'mutationFn'>
        ) => {
            return (await _mutation.mutateAsync(
                args,
                options as any
            )) as (CheckSelect<T, user_favorites, Prisma.user_favoritesGetPayload<T>> | undefined);
        },
    };
    return mutation;
}

export function useUpdateManyuser_favorites(options?: Omit<(UseMutationOptions<Prisma.BatchPayload, DefaultError, Prisma.user_favoritesUpdateManyArgs> & ExtraMutationOptions), 'mutationFn'>) {
    const { endpoint, fetch } = getHooksContext();
    const _mutation =
        useModelMutation<Prisma.user_favoritesUpdateManyArgs, DefaultError, Prisma.BatchPayload, false>('user_favorites', 'PUT', `${endpoint}/user_favorites/updateMany`, metadata, options, fetch, false)
        ;
    const mutation = {
        ..._mutation,
        mutateAsync: async <T extends Prisma.user_favoritesUpdateManyArgs>(
            args: Prisma.SelectSubset<T, Prisma.user_favoritesUpdateManyArgs>,
            options?: Omit<(UseMutationOptions<Prisma.BatchPayload, DefaultError, Prisma.SelectSubset<T, Prisma.user_favoritesUpdateManyArgs>> & ExtraMutationOptions), 'mutationFn'>
        ) => {
            return (await _mutation.mutateAsync(
                args,
                options as any
            )) as Prisma.BatchPayload;
        },
    };
    return mutation;
}

export function useUpsertuser_favorites(options?: Omit<(UseMutationOptions<(user_favorites | undefined), DefaultError, Prisma.user_favoritesUpsertArgs> & ExtraMutationOptions), 'mutationFn'>) {
    const { endpoint, fetch } = getHooksContext();
    const _mutation =
        useModelMutation<Prisma.user_favoritesUpsertArgs, DefaultError, user_favorites, true>('user_favorites', 'POST', `${endpoint}/user_favorites/upsert`, metadata, options, fetch, true)
        ;
    const mutation = {
        ..._mutation,
        mutateAsync: async <T extends Prisma.user_favoritesUpsertArgs>(
            args: Prisma.SelectSubset<T, Prisma.user_favoritesUpsertArgs>,
            options?: Omit<(UseMutationOptions<(CheckSelect<T, user_favorites, Prisma.user_favoritesGetPayload<T>> | undefined), DefaultError, Prisma.SelectSubset<T, Prisma.user_favoritesUpsertArgs>> & ExtraMutationOptions), 'mutationFn'>
        ) => {
            return (await _mutation.mutateAsync(
                args,
                options as any
            )) as (CheckSelect<T, user_favorites, Prisma.user_favoritesGetPayload<T>> | undefined);
        },
    };
    return mutation;
}

export function useDeleteuser_favorites(options?: Omit<(UseMutationOptions<(user_favorites | undefined), DefaultError, Prisma.user_favoritesDeleteArgs> & ExtraMutationOptions), 'mutationFn'>) {
    const { endpoint, fetch } = getHooksContext();
    const _mutation =
        useModelMutation<Prisma.user_favoritesDeleteArgs, DefaultError, user_favorites, true>('user_favorites', 'DELETE', `${endpoint}/user_favorites/delete`, metadata, options, fetch, true)
        ;
    const mutation = {
        ..._mutation,
        mutateAsync: async <T extends Prisma.user_favoritesDeleteArgs>(
            args: Prisma.SelectSubset<T, Prisma.user_favoritesDeleteArgs>,
            options?: Omit<(UseMutationOptions<(CheckSelect<T, user_favorites, Prisma.user_favoritesGetPayload<T>> | undefined), DefaultError, Prisma.SelectSubset<T, Prisma.user_favoritesDeleteArgs>> & ExtraMutationOptions), 'mutationFn'>
        ) => {
            return (await _mutation.mutateAsync(
                args,
                options as any
            )) as (CheckSelect<T, user_favorites, Prisma.user_favoritesGetPayload<T>> | undefined);
        },
    };
    return mutation;
}

export function useDeleteManyuser_favorites(options?: Omit<(UseMutationOptions<Prisma.BatchPayload, DefaultError, Prisma.user_favoritesDeleteManyArgs> & ExtraMutationOptions), 'mutationFn'>) {
    const { endpoint, fetch } = getHooksContext();
    const _mutation =
        useModelMutation<Prisma.user_favoritesDeleteManyArgs, DefaultError, Prisma.BatchPayload, false>('user_favorites', 'DELETE', `${endpoint}/user_favorites/deleteMany`, metadata, options, fetch, false)
        ;
    const mutation = {
        ..._mutation,
        mutateAsync: async <T extends Prisma.user_favoritesDeleteManyArgs>(
            args: Prisma.SelectSubset<T, Prisma.user_favoritesDeleteManyArgs>,
            options?: Omit<(UseMutationOptions<Prisma.BatchPayload, DefaultError, Prisma.SelectSubset<T, Prisma.user_favoritesDeleteManyArgs>> & ExtraMutationOptions), 'mutationFn'>
        ) => {
            return (await _mutation.mutateAsync(
                args,
                options as any
            )) as Prisma.BatchPayload;
        },
    };
    return mutation;
}

export function useAggregateUser_favorites<TArgs extends Prisma.User_favoritesAggregateArgs, TQueryFnData = Prisma.GetUser_favoritesAggregateType<TArgs>, TData = TQueryFnData, TError = DefaultError>(args: Prisma.SelectSubset<TArgs, Prisma.User_favoritesAggregateArgs>, options?: (Omit<UseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useModelQuery<TQueryFnData, TData, TError>('User_favorites', `${endpoint}/user_favorites/aggregate`, args, options, fetch);
}

export function useSuspenseAggregateUser_favorites<TArgs extends Prisma.User_favoritesAggregateArgs, TQueryFnData = Prisma.GetUser_favoritesAggregateType<TArgs>, TData = TQueryFnData, TError = DefaultError>(args: Prisma.SelectSubset<TArgs, Prisma.User_favoritesAggregateArgs>, options?: (Omit<UseSuspenseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useSuspenseModelQuery<TQueryFnData, TData, TError>('User_favorites', `${endpoint}/user_favorites/aggregate`, args, options, fetch);
}

export function useGroupByuser_favorites<TArgs extends Prisma.user_favoritesGroupByArgs, HasSelectOrTake extends Prisma.Or<Prisma.Extends<'skip', Prisma.Keys<TArgs>>, Prisma.Extends<'take', Prisma.Keys<TArgs>>>, OrderByArg extends Prisma.True extends HasSelectOrTake ? { orderBy: Prisma.user_favoritesGroupByArgs['orderBy'] } : { orderBy?: Prisma.user_favoritesGroupByArgs['orderBy'] }, OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<TArgs['orderBy']>>>, ByFields extends Prisma.MaybeTupleToUnion<TArgs['by']>, ByValid extends Prisma.Has<ByFields, OrderFields>, HavingFields extends Prisma.GetHavingFields<TArgs['having']>, HavingValid extends Prisma.Has<ByFields, HavingFields>, ByEmpty extends TArgs['by'] extends never[] ? Prisma.True : Prisma.False, InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
        ? never
        : P extends string
        ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
        : [
            Error,
            'Field ',
            P,
            ` in "having" needs to be provided in "by"`,
        ]
    }[HavingFields]
    : 'take' extends Prisma.Keys<TArgs>
    ? 'orderBy' extends Prisma.Keys<TArgs>
    ? ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
        ? never
        : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
    }[OrderFields]
    : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<TArgs>
    ? 'orderBy' extends Prisma.Keys<TArgs>
    ? ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
        ? never
        : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
    }[OrderFields]
    : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
        ? never
        : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
    }[OrderFields], TQueryFnData = {} extends InputErrors ?
    Array<PickEnumerable<Prisma.User_favoritesGroupByOutputType, TArgs['by']> &
    {
        [P in ((keyof TArgs) & (keyof Prisma.User_favoritesGroupByOutputType))]: P extends '_count'
        ? TArgs[P] extends boolean
        ? number
        : Prisma.GetScalarType<TArgs[P], Prisma.User_favoritesGroupByOutputType[P]>
        : Prisma.GetScalarType<TArgs[P], Prisma.User_favoritesGroupByOutputType[P]>
    }
    > : InputErrors, TData = TQueryFnData, TError = DefaultError>(args: Prisma.SelectSubset<TArgs, Prisma.SubsetIntersection<TArgs, Prisma.user_favoritesGroupByArgs, OrderByArg> & InputErrors>, options?: (Omit<UseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useModelQuery<TQueryFnData, TData, TError>('user_favorites', `${endpoint}/user_favorites/groupBy`, args, options, fetch);
}

export function useSuspenseGroupByuser_favorites<TArgs extends Prisma.user_favoritesGroupByArgs, HasSelectOrTake extends Prisma.Or<Prisma.Extends<'skip', Prisma.Keys<TArgs>>, Prisma.Extends<'take', Prisma.Keys<TArgs>>>, OrderByArg extends Prisma.True extends HasSelectOrTake ? { orderBy: Prisma.user_favoritesGroupByArgs['orderBy'] } : { orderBy?: Prisma.user_favoritesGroupByArgs['orderBy'] }, OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<TArgs['orderBy']>>>, ByFields extends Prisma.MaybeTupleToUnion<TArgs['by']>, ByValid extends Prisma.Has<ByFields, OrderFields>, HavingFields extends Prisma.GetHavingFields<TArgs['having']>, HavingValid extends Prisma.Has<ByFields, HavingFields>, ByEmpty extends TArgs['by'] extends never[] ? Prisma.True : Prisma.False, InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
        ? never
        : P extends string
        ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
        : [
            Error,
            'Field ',
            P,
            ` in "having" needs to be provided in "by"`,
        ]
    }[HavingFields]
    : 'take' extends Prisma.Keys<TArgs>
    ? 'orderBy' extends Prisma.Keys<TArgs>
    ? ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
        ? never
        : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
    }[OrderFields]
    : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<TArgs>
    ? 'orderBy' extends Prisma.Keys<TArgs>
    ? ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
        ? never
        : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
    }[OrderFields]
    : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
        ? never
        : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
    }[OrderFields], TQueryFnData = {} extends InputErrors ?
    Array<PickEnumerable<Prisma.User_favoritesGroupByOutputType, TArgs['by']> &
    {
        [P in ((keyof TArgs) & (keyof Prisma.User_favoritesGroupByOutputType))]: P extends '_count'
        ? TArgs[P] extends boolean
        ? number
        : Prisma.GetScalarType<TArgs[P], Prisma.User_favoritesGroupByOutputType[P]>
        : Prisma.GetScalarType<TArgs[P], Prisma.User_favoritesGroupByOutputType[P]>
    }
    > : InputErrors, TData = TQueryFnData, TError = DefaultError>(args: Prisma.SelectSubset<TArgs, Prisma.SubsetIntersection<TArgs, Prisma.user_favoritesGroupByArgs, OrderByArg> & InputErrors>, options?: (Omit<UseSuspenseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useSuspenseModelQuery<TQueryFnData, TData, TError>('user_favorites', `${endpoint}/user_favorites/groupBy`, args, options, fetch);
}

export function useCountuser_favorites<TArgs extends Prisma.user_favoritesCountArgs, TQueryFnData = TArgs extends { select: any; } ? TArgs['select'] extends true ? number : Prisma.GetScalarType<TArgs['select'], Prisma.User_favoritesCountAggregateOutputType> : number, TData = TQueryFnData, TError = DefaultError>(args?: Prisma.SelectSubset<TArgs, Prisma.user_favoritesCountArgs>, options?: (Omit<UseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useModelQuery<TQueryFnData, TData, TError>('user_favorites', `${endpoint}/user_favorites/count`, args, options, fetch);
}

export function useSuspenseCountuser_favorites<TArgs extends Prisma.user_favoritesCountArgs, TQueryFnData = TArgs extends { select: any; } ? TArgs['select'] extends true ? number : Prisma.GetScalarType<TArgs['select'], Prisma.User_favoritesCountAggregateOutputType> : number, TData = TQueryFnData, TError = DefaultError>(args?: Prisma.SelectSubset<TArgs, Prisma.user_favoritesCountArgs>, options?: (Omit<UseSuspenseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useSuspenseModelQuery<TQueryFnData, TData, TError>('user_favorites', `${endpoint}/user_favorites/count`, args, options, fetch);
}

export function useCheckuser_favorites<TError = DefaultError>(args: { operation: PolicyCrudKind; where?: { id?: string; user_id?: string; listing_id?: string }; }, options?: (Omit<UseQueryOptions<boolean, TError, boolean>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useModelQuery<boolean, boolean, TError>('user_favorites', `${endpoint}/user_favorites/check`, args, options, fetch);
}
