/******************************************************************************
 * This file was generated by ZenStack CLI.
 ******************************************************************************/

/* eslint-disable */

import type { Prisma, WorkExperience } from "@prisma/client";
import type { UseMutationOptions, UseQueryOptions, UseInfiniteQueryOptions, InfiniteData } from '@tanstack/react-query';
import { getHooksContext } from '@zenstackhq/tanstack-query/runtime-v5/react';
import { useModelQuery, useInfiniteModelQuery, useModelMutation } from '@zenstackhq/tanstack-query/runtime-v5/react';
import type { PickEnumerable, CheckSelect, QueryError, ExtraQueryOptions, ExtraMutationOptions } from '@zenstackhq/tanstack-query/runtime-v5';
import type { PolicyCrudKind } from '@zenstackhq/runtime'
import metadata from './__model_meta';
type DefaultError = QueryError;
import { useSuspenseModelQuery, useSuspenseInfiniteModelQuery } from '@zenstackhq/tanstack-query/runtime-v5/react';
import type { UseSuspenseQueryOptions, UseSuspenseInfiniteQueryOptions } from '@tanstack/react-query';

export function useCreateWorkExperience(options?: Omit<(UseMutationOptions<(WorkExperience | undefined), DefaultError, Prisma.WorkExperienceCreateArgs> & ExtraMutationOptions), 'mutationFn'>) {
    const { endpoint, fetch } = getHooksContext();
    const _mutation =
        useModelMutation<Prisma.WorkExperienceCreateArgs, DefaultError, WorkExperience, true>('WorkExperience', 'POST', `${endpoint}/workExperience/create`, metadata, options, fetch, true)
        ;
    const mutation = {
        ..._mutation,
        mutateAsync: async <T extends Prisma.WorkExperienceCreateArgs>(
            args: Prisma.SelectSubset<T, Prisma.WorkExperienceCreateArgs>,
            options?: Omit<(UseMutationOptions<(CheckSelect<T, WorkExperience, Prisma.WorkExperienceGetPayload<T>> | undefined), DefaultError, Prisma.SelectSubset<T, Prisma.WorkExperienceCreateArgs>> & ExtraMutationOptions), 'mutationFn'>
        ) => {
            return (await _mutation.mutateAsync(
                args,
                options as any
            )) as (CheckSelect<T, WorkExperience, Prisma.WorkExperienceGetPayload<T>> | undefined);
        },
    };
    return mutation;
}

export function useCreateManyWorkExperience(options?: Omit<(UseMutationOptions<Prisma.BatchPayload, DefaultError, Prisma.WorkExperienceCreateManyArgs> & ExtraMutationOptions), 'mutationFn'>) {
    const { endpoint, fetch } = getHooksContext();
    const _mutation =
        useModelMutation<Prisma.WorkExperienceCreateManyArgs, DefaultError, Prisma.BatchPayload, false>('WorkExperience', 'POST', `${endpoint}/workExperience/createMany`, metadata, options, fetch, false)
        ;
    const mutation = {
        ..._mutation,
        mutateAsync: async <T extends Prisma.WorkExperienceCreateManyArgs>(
            args: Prisma.SelectSubset<T, Prisma.WorkExperienceCreateManyArgs>,
            options?: Omit<(UseMutationOptions<Prisma.BatchPayload, DefaultError, Prisma.SelectSubset<T, Prisma.WorkExperienceCreateManyArgs>> & ExtraMutationOptions), 'mutationFn'>
        ) => {
            return (await _mutation.mutateAsync(
                args,
                options as any
            )) as Prisma.BatchPayload;
        },
    };
    return mutation;
}

export function useFindManyWorkExperience<TArgs extends Prisma.WorkExperienceFindManyArgs, TQueryFnData = Array<Prisma.WorkExperienceGetPayload<TArgs> & { $optimistic?: boolean }>, TData = TQueryFnData, TError = DefaultError>(args?: Prisma.SelectSubset<TArgs, Prisma.WorkExperienceFindManyArgs>, options?: (Omit<UseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useModelQuery<TQueryFnData, TData, TError>('WorkExperience', `${endpoint}/workExperience/findMany`, args, options, fetch);
}

export function useInfiniteFindManyWorkExperience<TArgs extends Prisma.WorkExperienceFindManyArgs, TQueryFnData = Array<Prisma.WorkExperienceGetPayload<TArgs>>, TData = TQueryFnData, TError = DefaultError>(args?: Prisma.SelectSubset<TArgs, Prisma.WorkExperienceFindManyArgs>, options?: Omit<UseInfiniteQueryOptions<TQueryFnData, TError, InfiniteData<TData>>, 'queryKey' | 'initialPageParam'>) {
    options = options ?? { getNextPageParam: () => null };
    const { endpoint, fetch } = getHooksContext();
    return useInfiniteModelQuery<TQueryFnData, TData, TError>('WorkExperience', `${endpoint}/workExperience/findMany`, args, options, fetch);
}

export function useSuspenseFindManyWorkExperience<TArgs extends Prisma.WorkExperienceFindManyArgs, TQueryFnData = Array<Prisma.WorkExperienceGetPayload<TArgs> & { $optimistic?: boolean }>, TData = TQueryFnData, TError = DefaultError>(args?: Prisma.SelectSubset<TArgs, Prisma.WorkExperienceFindManyArgs>, options?: (Omit<UseSuspenseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useSuspenseModelQuery<TQueryFnData, TData, TError>('WorkExperience', `${endpoint}/workExperience/findMany`, args, options, fetch);
}

export function useSuspenseInfiniteFindManyWorkExperience<TArgs extends Prisma.WorkExperienceFindManyArgs, TQueryFnData = Array<Prisma.WorkExperienceGetPayload<TArgs>>, TData = TQueryFnData, TError = DefaultError>(args?: Prisma.SelectSubset<TArgs, Prisma.WorkExperienceFindManyArgs>, options?: Omit<UseSuspenseInfiniteQueryOptions<TQueryFnData, TError, InfiniteData<TData>>, 'queryKey' | 'initialPageParam'>) {
    options = options ?? { getNextPageParam: () => null };
    const { endpoint, fetch } = getHooksContext();
    return useSuspenseInfiniteModelQuery<TQueryFnData, TData, TError>('WorkExperience', `${endpoint}/workExperience/findMany`, args, options, fetch);
}

export function useFindUniqueWorkExperience<TArgs extends Prisma.WorkExperienceFindUniqueArgs, TQueryFnData = Prisma.WorkExperienceGetPayload<TArgs> & { $optimistic?: boolean }, TData = TQueryFnData, TError = DefaultError>(args: Prisma.SelectSubset<TArgs, Prisma.WorkExperienceFindUniqueArgs>, options?: (Omit<UseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useModelQuery<TQueryFnData, TData, TError>('WorkExperience', `${endpoint}/workExperience/findUnique`, args, options, fetch);
}

export function useSuspenseFindUniqueWorkExperience<TArgs extends Prisma.WorkExperienceFindUniqueArgs, TQueryFnData = Prisma.WorkExperienceGetPayload<TArgs> & { $optimistic?: boolean }, TData = TQueryFnData, TError = DefaultError>(args: Prisma.SelectSubset<TArgs, Prisma.WorkExperienceFindUniqueArgs>, options?: (Omit<UseSuspenseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useSuspenseModelQuery<TQueryFnData, TData, TError>('WorkExperience', `${endpoint}/workExperience/findUnique`, args, options, fetch);
}

export function useFindFirstWorkExperience<TArgs extends Prisma.WorkExperienceFindFirstArgs, TQueryFnData = Prisma.WorkExperienceGetPayload<TArgs> & { $optimistic?: boolean }, TData = TQueryFnData, TError = DefaultError>(args?: Prisma.SelectSubset<TArgs, Prisma.WorkExperienceFindFirstArgs>, options?: (Omit<UseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useModelQuery<TQueryFnData, TData, TError>('WorkExperience', `${endpoint}/workExperience/findFirst`, args, options, fetch);
}

export function useSuspenseFindFirstWorkExperience<TArgs extends Prisma.WorkExperienceFindFirstArgs, TQueryFnData = Prisma.WorkExperienceGetPayload<TArgs> & { $optimistic?: boolean }, TData = TQueryFnData, TError = DefaultError>(args?: Prisma.SelectSubset<TArgs, Prisma.WorkExperienceFindFirstArgs>, options?: (Omit<UseSuspenseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useSuspenseModelQuery<TQueryFnData, TData, TError>('WorkExperience', `${endpoint}/workExperience/findFirst`, args, options, fetch);
}

export function useUpdateWorkExperience(options?: Omit<(UseMutationOptions<(WorkExperience | undefined), DefaultError, Prisma.WorkExperienceUpdateArgs> & ExtraMutationOptions), 'mutationFn'>) {
    const { endpoint, fetch } = getHooksContext();
    const _mutation =
        useModelMutation<Prisma.WorkExperienceUpdateArgs, DefaultError, WorkExperience, true>('WorkExperience', 'PUT', `${endpoint}/workExperience/update`, metadata, options, fetch, true)
        ;
    const mutation = {
        ..._mutation,
        mutateAsync: async <T extends Prisma.WorkExperienceUpdateArgs>(
            args: Prisma.SelectSubset<T, Prisma.WorkExperienceUpdateArgs>,
            options?: Omit<(UseMutationOptions<(CheckSelect<T, WorkExperience, Prisma.WorkExperienceGetPayload<T>> | undefined), DefaultError, Prisma.SelectSubset<T, Prisma.WorkExperienceUpdateArgs>> & ExtraMutationOptions), 'mutationFn'>
        ) => {
            return (await _mutation.mutateAsync(
                args,
                options as any
            )) as (CheckSelect<T, WorkExperience, Prisma.WorkExperienceGetPayload<T>> | undefined);
        },
    };
    return mutation;
}

export function useUpdateManyWorkExperience(options?: Omit<(UseMutationOptions<Prisma.BatchPayload, DefaultError, Prisma.WorkExperienceUpdateManyArgs> & ExtraMutationOptions), 'mutationFn'>) {
    const { endpoint, fetch } = getHooksContext();
    const _mutation =
        useModelMutation<Prisma.WorkExperienceUpdateManyArgs, DefaultError, Prisma.BatchPayload, false>('WorkExperience', 'PUT', `${endpoint}/workExperience/updateMany`, metadata, options, fetch, false)
        ;
    const mutation = {
        ..._mutation,
        mutateAsync: async <T extends Prisma.WorkExperienceUpdateManyArgs>(
            args: Prisma.SelectSubset<T, Prisma.WorkExperienceUpdateManyArgs>,
            options?: Omit<(UseMutationOptions<Prisma.BatchPayload, DefaultError, Prisma.SelectSubset<T, Prisma.WorkExperienceUpdateManyArgs>> & ExtraMutationOptions), 'mutationFn'>
        ) => {
            return (await _mutation.mutateAsync(
                args,
                options as any
            )) as Prisma.BatchPayload;
        },
    };
    return mutation;
}

export function useUpsertWorkExperience(options?: Omit<(UseMutationOptions<(WorkExperience | undefined), DefaultError, Prisma.WorkExperienceUpsertArgs> & ExtraMutationOptions), 'mutationFn'>) {
    const { endpoint, fetch } = getHooksContext();
    const _mutation =
        useModelMutation<Prisma.WorkExperienceUpsertArgs, DefaultError, WorkExperience, true>('WorkExperience', 'POST', `${endpoint}/workExperience/upsert`, metadata, options, fetch, true)
        ;
    const mutation = {
        ..._mutation,
        mutateAsync: async <T extends Prisma.WorkExperienceUpsertArgs>(
            args: Prisma.SelectSubset<T, Prisma.WorkExperienceUpsertArgs>,
            options?: Omit<(UseMutationOptions<(CheckSelect<T, WorkExperience, Prisma.WorkExperienceGetPayload<T>> | undefined), DefaultError, Prisma.SelectSubset<T, Prisma.WorkExperienceUpsertArgs>> & ExtraMutationOptions), 'mutationFn'>
        ) => {
            return (await _mutation.mutateAsync(
                args,
                options as any
            )) as (CheckSelect<T, WorkExperience, Prisma.WorkExperienceGetPayload<T>> | undefined);
        },
    };
    return mutation;
}

export function useDeleteWorkExperience(options?: Omit<(UseMutationOptions<(WorkExperience | undefined), DefaultError, Prisma.WorkExperienceDeleteArgs> & ExtraMutationOptions), 'mutationFn'>) {
    const { endpoint, fetch } = getHooksContext();
    const _mutation =
        useModelMutation<Prisma.WorkExperienceDeleteArgs, DefaultError, WorkExperience, true>('WorkExperience', 'DELETE', `${endpoint}/workExperience/delete`, metadata, options, fetch, true)
        ;
    const mutation = {
        ..._mutation,
        mutateAsync: async <T extends Prisma.WorkExperienceDeleteArgs>(
            args: Prisma.SelectSubset<T, Prisma.WorkExperienceDeleteArgs>,
            options?: Omit<(UseMutationOptions<(CheckSelect<T, WorkExperience, Prisma.WorkExperienceGetPayload<T>> | undefined), DefaultError, Prisma.SelectSubset<T, Prisma.WorkExperienceDeleteArgs>> & ExtraMutationOptions), 'mutationFn'>
        ) => {
            return (await _mutation.mutateAsync(
                args,
                options as any
            )) as (CheckSelect<T, WorkExperience, Prisma.WorkExperienceGetPayload<T>> | undefined);
        },
    };
    return mutation;
}

export function useDeleteManyWorkExperience(options?: Omit<(UseMutationOptions<Prisma.BatchPayload, DefaultError, Prisma.WorkExperienceDeleteManyArgs> & ExtraMutationOptions), 'mutationFn'>) {
    const { endpoint, fetch } = getHooksContext();
    const _mutation =
        useModelMutation<Prisma.WorkExperienceDeleteManyArgs, DefaultError, Prisma.BatchPayload, false>('WorkExperience', 'DELETE', `${endpoint}/workExperience/deleteMany`, metadata, options, fetch, false)
        ;
    const mutation = {
        ..._mutation,
        mutateAsync: async <T extends Prisma.WorkExperienceDeleteManyArgs>(
            args: Prisma.SelectSubset<T, Prisma.WorkExperienceDeleteManyArgs>,
            options?: Omit<(UseMutationOptions<Prisma.BatchPayload, DefaultError, Prisma.SelectSubset<T, Prisma.WorkExperienceDeleteManyArgs>> & ExtraMutationOptions), 'mutationFn'>
        ) => {
            return (await _mutation.mutateAsync(
                args,
                options as any
            )) as Prisma.BatchPayload;
        },
    };
    return mutation;
}

export function useAggregateWorkExperience<TArgs extends Prisma.WorkExperienceAggregateArgs, TQueryFnData = Prisma.GetWorkExperienceAggregateType<TArgs>, TData = TQueryFnData, TError = DefaultError>(args: Prisma.SelectSubset<TArgs, Prisma.WorkExperienceAggregateArgs>, options?: (Omit<UseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useModelQuery<TQueryFnData, TData, TError>('WorkExperience', `${endpoint}/workExperience/aggregate`, args, options, fetch);
}

export function useSuspenseAggregateWorkExperience<TArgs extends Prisma.WorkExperienceAggregateArgs, TQueryFnData = Prisma.GetWorkExperienceAggregateType<TArgs>, TData = TQueryFnData, TError = DefaultError>(args: Prisma.SelectSubset<TArgs, Prisma.WorkExperienceAggregateArgs>, options?: (Omit<UseSuspenseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useSuspenseModelQuery<TQueryFnData, TData, TError>('WorkExperience', `${endpoint}/workExperience/aggregate`, args, options, fetch);
}

export function useGroupByWorkExperience<TArgs extends Prisma.WorkExperienceGroupByArgs, HasSelectOrTake extends Prisma.Or<Prisma.Extends<'skip', Prisma.Keys<TArgs>>, Prisma.Extends<'take', Prisma.Keys<TArgs>>>, OrderByArg extends Prisma.True extends HasSelectOrTake ? { orderBy: Prisma.WorkExperienceGroupByArgs['orderBy'] } : { orderBy?: Prisma.WorkExperienceGroupByArgs['orderBy'] }, OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<TArgs['orderBy']>>>, ByFields extends Prisma.MaybeTupleToUnion<TArgs['by']>, ByValid extends Prisma.Has<ByFields, OrderFields>, HavingFields extends Prisma.GetHavingFields<TArgs['having']>, HavingValid extends Prisma.Has<ByFields, HavingFields>, ByEmpty extends TArgs['by'] extends never[] ? Prisma.True : Prisma.False, InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
        ? never
        : P extends string
        ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
        : [
            Error,
            'Field ',
            P,
            ` in "having" needs to be provided in "by"`,
        ]
    }[HavingFields]
    : 'take' extends Prisma.Keys<TArgs>
    ? 'orderBy' extends Prisma.Keys<TArgs>
    ? ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
        ? never
        : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
    }[OrderFields]
    : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<TArgs>
    ? 'orderBy' extends Prisma.Keys<TArgs>
    ? ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
        ? never
        : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
    }[OrderFields]
    : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
        ? never
        : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
    }[OrderFields], TQueryFnData = {} extends InputErrors ?
    Array<PickEnumerable<Prisma.WorkExperienceGroupByOutputType, TArgs['by']> &
    {
        [P in ((keyof TArgs) & (keyof Prisma.WorkExperienceGroupByOutputType))]: P extends '_count'
        ? TArgs[P] extends boolean
        ? number
        : Prisma.GetScalarType<TArgs[P], Prisma.WorkExperienceGroupByOutputType[P]>
        : Prisma.GetScalarType<TArgs[P], Prisma.WorkExperienceGroupByOutputType[P]>
    }
    > : InputErrors, TData = TQueryFnData, TError = DefaultError>(args: Prisma.SelectSubset<TArgs, Prisma.SubsetIntersection<TArgs, Prisma.WorkExperienceGroupByArgs, OrderByArg> & InputErrors>, options?: (Omit<UseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useModelQuery<TQueryFnData, TData, TError>('WorkExperience', `${endpoint}/workExperience/groupBy`, args, options, fetch);
}

export function useSuspenseGroupByWorkExperience<TArgs extends Prisma.WorkExperienceGroupByArgs, HasSelectOrTake extends Prisma.Or<Prisma.Extends<'skip', Prisma.Keys<TArgs>>, Prisma.Extends<'take', Prisma.Keys<TArgs>>>, OrderByArg extends Prisma.True extends HasSelectOrTake ? { orderBy: Prisma.WorkExperienceGroupByArgs['orderBy'] } : { orderBy?: Prisma.WorkExperienceGroupByArgs['orderBy'] }, OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<TArgs['orderBy']>>>, ByFields extends Prisma.MaybeTupleToUnion<TArgs['by']>, ByValid extends Prisma.Has<ByFields, OrderFields>, HavingFields extends Prisma.GetHavingFields<TArgs['having']>, HavingValid extends Prisma.Has<ByFields, HavingFields>, ByEmpty extends TArgs['by'] extends never[] ? Prisma.True : Prisma.False, InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
        ? never
        : P extends string
        ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
        : [
            Error,
            'Field ',
            P,
            ` in "having" needs to be provided in "by"`,
        ]
    }[HavingFields]
    : 'take' extends Prisma.Keys<TArgs>
    ? 'orderBy' extends Prisma.Keys<TArgs>
    ? ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
        ? never
        : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
    }[OrderFields]
    : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<TArgs>
    ? 'orderBy' extends Prisma.Keys<TArgs>
    ? ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
        ? never
        : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
    }[OrderFields]
    : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
        ? never
        : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
    }[OrderFields], TQueryFnData = {} extends InputErrors ?
    Array<PickEnumerable<Prisma.WorkExperienceGroupByOutputType, TArgs['by']> &
    {
        [P in ((keyof TArgs) & (keyof Prisma.WorkExperienceGroupByOutputType))]: P extends '_count'
        ? TArgs[P] extends boolean
        ? number
        : Prisma.GetScalarType<TArgs[P], Prisma.WorkExperienceGroupByOutputType[P]>
        : Prisma.GetScalarType<TArgs[P], Prisma.WorkExperienceGroupByOutputType[P]>
    }
    > : InputErrors, TData = TQueryFnData, TError = DefaultError>(args: Prisma.SelectSubset<TArgs, Prisma.SubsetIntersection<TArgs, Prisma.WorkExperienceGroupByArgs, OrderByArg> & InputErrors>, options?: (Omit<UseSuspenseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useSuspenseModelQuery<TQueryFnData, TData, TError>('WorkExperience', `${endpoint}/workExperience/groupBy`, args, options, fetch);
}

export function useCountWorkExperience<TArgs extends Prisma.WorkExperienceCountArgs, TQueryFnData = TArgs extends { select: any; } ? TArgs['select'] extends true ? number : Prisma.GetScalarType<TArgs['select'], Prisma.WorkExperienceCountAggregateOutputType> : number, TData = TQueryFnData, TError = DefaultError>(args?: Prisma.SelectSubset<TArgs, Prisma.WorkExperienceCountArgs>, options?: (Omit<UseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useModelQuery<TQueryFnData, TData, TError>('WorkExperience', `${endpoint}/workExperience/count`, args, options, fetch);
}

export function useSuspenseCountWorkExperience<TArgs extends Prisma.WorkExperienceCountArgs, TQueryFnData = TArgs extends { select: any; } ? TArgs['select'] extends true ? number : Prisma.GetScalarType<TArgs['select'], Prisma.WorkExperienceCountAggregateOutputType> : number, TData = TQueryFnData, TError = DefaultError>(args?: Prisma.SelectSubset<TArgs, Prisma.WorkExperienceCountArgs>, options?: (Omit<UseSuspenseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useSuspenseModelQuery<TQueryFnData, TData, TError>('WorkExperience', `${endpoint}/workExperience/count`, args, options, fetch);
}

export function useCheckWorkExperience<TError = DefaultError>(args: { operation: PolicyCrudKind; where?: { id?: string; company?: string; position?: string; startDate?: string; endDate?: string; isCurrent?: boolean; userId?: string }; }, options?: (Omit<UseQueryOptions<boolean, TError, boolean>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useModelQuery<boolean, boolean, TError>('WorkExperience', `${endpoint}/workExperience/check`, args, options, fetch);
}
